### PR TITLE
GRIB_API cleanup

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by GillesDuvert** [comment]
... and replace grib and grib_api with eccodes everywhere possible? for clarity?

**Comment by slayoo** [comment]
Gilles, I doubt it would improve clarity. Inside ECCODES, nothing has changed (still grib_abi.h, still grib-prefixed routine names). IDL also prefixes the routines with GRIB_. Users want to read GRIB files, and they do not care if the handling is with ECCODES or anything else - like with graphics formats and ImageMagick.

**Comment by slayoo** [comment]
https://www.l3harrisgeospatial.com/docs/GRIB_Routines.html

**Comment by GillesDuvert** [comment]
Ok, thanks @slayoo for the explanation.

**Comment by opoplawski** [comment]
So the problem with this is that eccodes does not support all of the architectures that Fedora does, and so we compile against grib_api on those.  I'm going to revert the essential part of this for now on Fedora.  The other option is that we simply drop support for those architectures for gdl.

**Comment by opoplawski** [comment]
At the moment those arches are i686, armv7hl, s390x.

**Comment by slayoo** [comment]
Thanks @opoplawski 
Perhaps let's just disable GRIB support in GDL on those platforms on Fedora?

**Comment by opoplawski** [comment]
That's certainly a possibility as well.

**Comment by GillesDuvert** [comment]
but is not https://github.com/gnudatalanguage/gdl/pull/1054 a solution?

**Pull request merged**
