### PR TITLE
Close 1809

### PR DESCRIPTION
**Pull request by GillesDuvert**
note this has also temporarily removed:

1. use of MPI on OSX
2. test_obj_new
3. test_xyztick_get

to make build clearer.
It is expected that future PRs will reinstall those options and tests.

### CODE REVIEW

**Comment by GillesDuvert** [comment]
OK, OpenMPI IS NOT the culprit to the OSX failure and can be reenabled. Just the first victim, leaving its own forensic log.

**Comment by alaingdl** [comment]
I am OK to release it, and solve later the details for OSX

I don't see how I will be able to merge my PR #1816 :(

**Comment by slayoo** [comment]
@GillesDuvert IIUC, GitHub has made arm64 the default now for `macos-latest`. So we have the same failures as in #1788.
Let me change `macos-latest` to `macos-12` in the workflow files here to get back to previous setup.

**Comment by GillesDuvert** [comment]
> @GillesDuvert IIUC, GitHub has made arm64 the default now for `macos-latest`. So we have the same failures as in #1788. Let me change `macos-latest` to `macos-12` in the workflow files here to get back to previous setup.

@slayoo indeed, this looks way better. In this case we could reenable OpenMP on macos12. MPI is now enabled for 'headless' only, which is probably reasonable, even if it was not really a problem. 

There is still a warning on CI page that I do not understand, as there is no 'node.js 20' stuff left in our code.

> **[build-windows (debug, x86_64, Debug)](https://github.com/gnudatalanguage/gdl/actions/runs/8845263876/job/24288822574)** 
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 
> actions/setup-python@v4. For more information see: 
> https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by slayoo** [comment]
> There is still a warning on CI page that I do not understand, as there is no 'node.js 20' stuff left in our code.

The node.js warnings stem from code outside of our repo - from what's behind some of the workflow steps we reuse from external sources... but where is this particular warning displayed?

**Comment by GillesDuvert** [comment]
annotations box in https://github.com/gnudatalanguage/gdl/actions/runs/8845263876

**Comment by slayoo** [comment]
this should help with the warning: https://github.com/gnudatalanguage/gdl/pull/1824

**Pull request merged**
