### PR TITLE
Patch HASH for /foldcase, tostruct(); file_link for WIN32

### PR DESCRIPTION
**Pull request by maynardGK**
The /recursive keyword for HASH::TOSTRUCT is implemented.  Also foldcase property
is now effective.  Test_hash is a bit more extensive.
  FILE_LINK built-in C++ function works in unix systems but for WIN32 the same library
procedure is not available; links are possible, however, so for the WIN32 builds the
internal function is disabled and a dummy procedure is placed in src/pro that returns
the same message the built-in would.

Greg Jung (aka maynardGK)
gvjung@gmail.com

### CODE REVIEW

**Comment by slayoo** [comment]
Thanks!
Could we enable the test_hash test (and any of the file tests) on Appveyor?

**Comment by maynardGK** [comment]
@slayoo yes the file_tests that came in the file_etc branch should all be fine. 

test_file_info and test_fil;e_basename are not ready for WIN32.

Some tests stayed behind in teststuite/file_etc   which should only hold the 
'test_file_t_XXX" procedures that use spawn extensively.  Nevertheless a copy of
test_file_search and of test_file_test stayed in directory. 

test_hash
test_file_copy
test_file_delete
test_file_move
test_file_search
test_file_test

**Comment by slayoo** [comment]
thanks! trying with those tests enabled. travis cancelled manually as nothing new to be tested there

**Comment by slayoo** [comment]
fifty fifty :)

```
        Start  66: test_file_copy.pro
 66/107 Test  #66: test_file_copy.pro ...............***Exception: SegFault  0.04 sec
        Start  67: test_file_delete.pro
 67/107 Test  #67: test_file_delete.pro .............   Passed    0.13 sec
       Start  68: test_file_move.pro
 68/107 Test  #68: test_file_move.pro ...............***Exception: SegFault  0.01 sec
        Start  69: test_file_search.pro
 69/107 Test  #69: test_file_search.pro .............   Passed    0.24 sec
        Start  70: test_file_test.pro
 70/107 Test  #70: test_file_test.pro ...............***Exception: SegFault  0.01 sec
...
        Start  72: test_hash.pro
 72/107 Test  #72: test_hash.pro ....................   Passed    0.14 sec
```

There is no additional info in the log unfortunatelly

**Pull request merged**
