### PR TITLE
Try speedup where()

### PR DESCRIPTION
**Pull request by GillesDuvert**
New version, on par with IDL speed.

### CODE REVIEW

**Review by maynardGK — COMMENTED** [review]
This looks fine except for the compilation errors in the gcc or clang travis builds.
I merged and test-built a windows version in order to prove that it works as expected.

The other travis error is the same encountered by the #478
 (#478 is the same as #431)
 The command "if [ -v CODECOV ]; then make codecov; else make check; fi" exited with 2.

Since #478 has extensive changes to list.cpp it would be much simpler to incorporate #478 into master prior to bringing in the changes here, which affect list.cpp only modestly.

**Comment by maynardGK** [comment]
Note: PR #478 is the same as #431

**Comment by alaingdl** [comment]
Good news : I made some tests in performance (3 machines) with pretty good results, except on OSX.

I also made tests with large inputs arrays, assuming its triggering the OpenMP version ...
I got consistent results (initial array and re-ordered copys of the original array)
[to be put in testsuite/ ASAP]

**Comment by alaingdl** [comment]
@GillesDuvert 
Bad news : in CI I can reproduce [the problem](https://travis-ci.org/gnudatalanguage/gdl/jobs/440830880) when Eigen3 is not activated. 

in _includefirst.hpp_ adding 
```
#include <cstddef>
#include <cstdlib>
```
help to remove some messages, but I found no solution to remove : 

/tmp/gnudatalanguage/gdl/src/includefirst.hpp: In function ‘void* gdlAlignedRealloc(void*, std::size_t, std::size_t)’:
/tmp/gnudatalanguage/gdl/src/includefirst.hpp:90:27: error: ‘newsize’ was not declared in this scope
  return std::realloc(ptr, newsize);

**Comment by alaingdl** [comment]
@GillesDuvert I got it, it is just a typo !! s/newsize/new_size/

**Comment by GillesDuvert** [comment]
Well, as Travis is here to test what I cannot/wantnot test locally.
Hope we can merge this PR once this (petty) problem is solved.
I have noted the comment by @maynardGK and will make global tests.

**Comment by alaingdl** [comment]
@maynardGK  I am very sorry but I would prefer *not* to wait for your modifications on HASH() & LIST() because at least two teams are _waiting_ for improvements on WHERE()

**Comment by GillesDuvert** [comment]
Actually, gdAlinedXXXX is not aligning anything at all when not using Eigen::. This is bad, as we need aligned allocs even in the absence of Eigen:: (?? who would want a GDL without Eigen:: ?? you tell me!).
Several solutions are available, none of them are bound to work on every machine/os. Having  machine/os indpendent  gdlAlignedMalloc and Realloc woudl be a plus.

**Comment by alaingdl** [comment]
@GillesDuvert 

when OpenMP is desactivated, I have problem due to

```
int thread_id = omp_get_thread_num(); //MINMAX_THREAD_NUM;
```
(multiples occurence, cannot compile)

in similar code _minmax_include.cpp_, you put 
```
int thread_id = MINMAX_THREAD_NUM;
```

Should I do it like that ?!

**Comment by GillesDuvert** [comment]
yes, I forgot this issue. You could keep the same #define logic and use some `WHERE_THREAD_NUM=1`
But the case "1 thread" is explicitely written outside of the threaded part, so putting all the theraded code between `#ifdef _OPENMP` and `#endif` should do the job cleanly.

**Comment by maynardGK** [comment]
@alaingdl There is no wait, hash and list are done. #431 
As bonus, it will also create a usable win32 distro.

**Comment by alaingdl** [comment]
I need to go further to test some cases on OSX & Linux, not clear why AppVeyor build failed since compilation i OK

**Comment by alaingdl** [comment]
this version should be OK with and without OpenMP

**Pull request merged**
