### PR TITLE
Use size_t for string positions

### PR DESCRIPTION
**Pull request by opoplawski**

### CODE REVIEW

**Comment by slayoo** [comment]
the change in the .g antlr input file is not reflected in a generated file

**Comment by slayoo** [comment]
Alain, I suggest reverting as this one includes changes to generated files only, and not to the .g grammar files.

**Comment by slayoo** [comment]
Sorry, vice versa - change in .g file is not reflected in a relevant generated file, right?

**Comment by opoplawski** [comment]
I guess I would argue that generated files should not be in git but should be generated for releases only.

**Comment by GillesDuvert** [comment]
Hm, we have many contributors that change GDL\*pp files (and FMT\*pp files) , and that is good, but the bottleneck is to insure these improvements are backported to the .g files at some point. OTH, it is just too easy to forget that .g files **may** have changed on GH... Not having the .g files on GH, or, rather, having these files elsewhere on GH is probably a beginning of solution, especially if there would be some way of making gnudatalanguage/gdl (here) depend from gnudatalanguage/antlr (there).

The other related topic is that the GDL\*pp files should be, eventually, recreated from the .g files by the packagers (#45) . And that "stock antlr" and not the content of the antlr subdirectory should be used by them. This points to an evolution of our CMake. Volunteers?

And, besides, as you wanted to ask, yes, there seems to be a way to have gdl parsing speed multiplied by a huge amount... And gdl files are antlr 2, not even antlr 3... So there **will** be some work on .g files in the future.

**Comment by slayoo** [comment]
Why would not having .g files in the repo help in any way? Orion suggested not to keep the generated files. I would then add suggestion not to store the antlr header files either... (but I'm almost certain Marc mentioned once that they are actually a modified version).

**Comment by GillesDuvert** [comment]
they are a modified version, but I've played with antlr a lot, especially with stock antlr and that did not seem to make any difference at the time...
And, yes, I misread @opoplawski comment, but I fail to see how removing the GDL\*files is going to make life easier for contributors who at the very least should have antlr2.7 on their machine... If any, the current situation with its drawbacks is bearable. But someone can make an experiment on a clone of gdl and tell us.

**Comment by slayoo** [comment]
btw, the antlr website mentions "ANTLR v2 to v3 converter (in progress and only marginally useful)": http://www.antlr3.org/download/v2v3-0.2.tar.gz

**Comment by GillesDuvert** [comment]
Hi, @slayoo , thanks for the tip. I'll give a try.

**Pull request merged**
