### PR TITLE
tentatively solve #1474

### PR DESCRIPTION
**Pull request by GillesDuvert**

### CODE REVIEW

**Comment by slayoo** [comment]
@GillesDuvert @acoulais @brandy125 it would be great to include a test with this PR (one that fails without this change, and passes with the change applied) Thanks!

**Comment by alaingdl** [comment]
The good news : successfully tested (with my script) on Debian 10 & U22.04

The bad news : unable to compile GDL with current Brew with the build script or with CMake. I do have a plplot dylib but not OK :(

**Comment by GillesDuvert** [comment]
This patch does not totally solve #1474.
There are still a number of differences between IDL and GDL when it comes to read/write files that can be modified **externally** (NB: externally is the point. GDL behaves OK when it modifies a file internally.)
As always,  it is best (but time-consuming :smile:  ) to start from the example reported by the user, but explore in a test file all the possible outcomes. Here, the example lacks the fact that **writing** to an externally  modified file does not produce identical results on IDL and GDL.

**Comment by slayoo** [comment]
Merci, @GillesDuvert!

**Comment by GillesDuvert** [comment]
> The good news : successfully tested (with my script) on Debian 10 & U22.04
> 
> The bad news : unable to compile GDL with current Brew with the build script or with CMake. I do have a plplot dylib but not OK :(

Homebrew's last version seems buggy: cannot permit to use a modified formula to rebuild plplot. So: `build_gdl.sh` uses scriptlet "`brew_enable_wxwidgets`" for nothing (formula used is not the modified one but a cached one), and thus no dynamic drivers, and thus no GDL. 
On MacPort side, idem, and would need yet another trick to  recompile plplot with the correct options within MacPorts.
Wonder why they do not provide these options from the start.
We should have asked homebrew and MacPorts for a version of plplot with dynamic drivers and wxwidgets a long time ago.

Besides, on arm64, MacPorts or Homebrew gcc is not working, and we must use clang. But clang somehow makes the creation/destruction of GDL objects very slow (probably an error in the legacy GDL code, who knows?) so GDL is not satisfactorily fast.

This is IMHO a serious concern as GDL contributors, whatever their skills and implication, are not supposed to fight Homebrew, MacPorts and clang, but to add new useful commands to GDL.

**Comment by GillesDuvert** [comment]
On Windows I see that we have found an INTERNAL BUG of MINGW that must be reported!

[100%] Linking CXX executable gdl.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: internal error: aborting at ../../binutils-2.40/ld/ldlang.c:527 in compare_section
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: **please report this bug**

**Comment by GillesDuvert** [comment]
1. bug above reported
2. macOS build solved by #1510

**Pull request merged**
