### PR TITLE
LA_SVD

### PR DESCRIPTION
**Pull request by algorab-dream**
First version of LA_SVD

### CODE REVIEW

**Comment by slayoo** [comment]
Thanks!
Please do include a test routine so that the newly added code has some example usage in the repository and is covered with a test under continuous integration (to check if future changes to GDL do not introduce regressions).

**Comment by alaingdl** [comment]
Thanks. @bouloukaouze will add some tests and also have to consider the (d)complex types ...

**Comment by slayoo** [comment]
@bouloukaouze note that the last commit is in this PR - I guess it was meant to be on a separate branch. It would also be great to make a PR to the 1.0 branch

**Comment by GillesDuvert** [comment]
hi @bouloukaouze,
concerning file_lines, your new code seems restricted to non-compressed UNIX files. To insure full compatibility (earlier behaviour) it is still needed to use gzread, etc if the file is compressed.
Besides, a 'line' is not always '\n'. It can be ('\r' or '\r\n' and should be tested on all platforms).
Making two cases, if (compressed) old code else new code (with '\r','\r\n') should do the job.

**Comment by GillesDuvert** [comment]
conflicts since I've patched 'file' in #1090  to speed increase and preserve compressed file handling (and windows line termination as well).
This PR can be merged as soon as its last commit (https://github.com/gnudatalanguage/gdl/pull/1040/commits/cc374c667975b5edfdae59c8b4257c86a5564790) is reverted

**Comment by GillesDuvert** [comment]
done after removing https://github.com/gnudatalanguage/gdl/commit/cc374c667975b5edfdae59c8b4257c86a5564790 's conflicts

**Pull request closed without merging**
