### PR TITLE
WIP: Solve charsize problems, allows P.FONT to work in PLOT windows.

### PR DESCRIPTION
**Pull request by GillesDuvert**
Also corrects an XYOUTS bug, and sets correctly some sytem variables (path etc)

### CODE REVIEW

**Comment by alaingdl** [comment]
See from here, PATH inside GDL is now not working any more :warning: 
(`HELP, /path ` don't contain something)

**Comment by GillesDuvert** [comment]
works for me, that is what is strange.
can you test with 
```
$ unset IDL_DIR
$ unset IDL_STARTUP
```
before?
The changes on the PATH-related things in https://github.com/gnudatalanguage/gdl/pull/1275/commits/ad7a9255f40095f634e5450c2201f049ec011e85 are there to insure GDL works on all machines without resorting to enviromnent variables, especially on Windows.
... And they are necessary to the 'next step', going around the bugs in the plplot drivers...

**Comment by GillesDuvert** [comment]
actually, the output of HELP,/SYS may be useful

**Comment by GillesDuvert** [comment]
... I always compile with -DPYTHON=OFF . this may be it.

**Comment by alaingdl** [comment]
No change after _unset_
What do you want to know in `GDL> help,/sys`
I have
` !PATH          STRING    = ''`

I will try without Python now

**Comment by alaingdl** [comment]
> ... I always compile with -DPYTHON=OFF . this may be it.

In fact it was compiled with -DPYTHON=OFF

**Comment by GillesDuvert** [comment]
```
GDL> help,/sys
 !C             LONG      =            0
 !COLOR         STRUCT    = -> !COLOR Array[1]
 !CONST         STRUCT    = -> !CONST Array[1]
 !CPU           STRUCT    = -> !CPU Array[1]
 !D             STRUCT    = -> !DEVICE Array[1]
 !DIR           STRING    = '/usr/local/share/gnudatalanguage'
 !DPI           DOUBLE    =        3.1415927
 !DTOR          FLOAT     =     0.0174533
 !EDIT_INPUT    INT       =        1
 !ERR           LONG      =            0
 !ERROR         LONG      =            0
 !ERROR_STATE   STRUCT    = -> !ERROR_STATE Array[1]
 !ERR_STRING    STRING    = ''
 !EXCEPT        INT       =        1
 !FALSE         BYTE      =    0
 !GDL           STRUCT    = -> !GNUDATALANGUAGE Array[1]
 !GDL_MAPS_DIR  STRING    = '/usr/local/share/gnudatalanguage/resource/maps'
 !GDL_WARNING   LONG      =            1
 !HELP_PATH     STRING    = ''
 !JOURNAL       LONG      =            0
 !MAKE_DLL      STRUCT    = -> !MAKE_DLL Array[1]
 !MAP           STRUCT    = -> !MAP Array[1]
 !MORE          INT       =        1
 !MOUSE         STRUCT    = -> !MOUSE Array[1]
 !NULL          UNDEFINED = !NULL
 !ORDER         LONG      =            0
 !P             STRUCT    = -> !PLT Array[1]
 !PATH          STRING    = '/usr/local/share/gnudatalanguage/lib/map:/usr/local/share/gnudatalanguage/lib/CMprocedures:/usr/local/share/gnudatalanguage/lib/envi:/usr/local/share/gnudatalanguage/li'...
 !PI            FLOAT     =       3.14159
 !PROMPT        STRING    = 'GDL> '
 !QUIET         LONG      =            0
 !RADEG         FLOAT     =       57.2958
 !STIME         STRING    = ''
 !TRUE          BYTE      =    1
 !VALUES        STRUCT    = -> !VALUES Array[1]
 !VERSION       STRUCT    = -> !VERSION Array[1]
 !WARN          STRUCT    = -> !WARN Array[1]
 !X             STRUCT    = -> !AXIS Array[1]
 !Y             STRUCT    = -> !AXIS Array[1]
 !Z             STRUCT    = -> !AXIS Array[1]

```

**Comment by alaingdl** [comment]
Same outputs that you except except for !PATH

What is strange is that the paths are visibles when starting _gdl_ with _./quick_start_GDL.sh_

```
coulais@caler:~/GDL_PR/Le220222/gdl/build1$ ./quick_start_GDL.sh 
Running current GDL with CMAKE_SOURCE_DIR/src/pro and CMAKE_SOURCE_DIR/testsuite in GDL_PATH
+/obs/coulais/GDL_PR/Le220222/gdl/src/pro/:+/obs/coulais/GDL_PR/Le220222/gdl/testsuite/
Gtk-Message: 11:19:54.021: Failed to load module "canberra-gtk-module"
  GDL - GNU Data Language, Version 1.0.1 Git
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): +/obs/coulais/GDL_PR/Le220222/gdl/src/pro/:+/obs/coulais/GDL_PR/Le220222/gdl/testsuite/
- Using WxWidgets as graphics library (windows and widgets).
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL> print, !path

GDL> 
```

And yes, CMAKE_SOURCE_DIR is well defined (and exists !) in Makefile :
Makefile:CMAKE_SOURCE_DIR = /obs/coulais/GDL_PR/Le220222/gdl

What I did to compile (in a new sub-dir) : 

```
git clone https://github.com/gnudatalanguage/gdl
cd gdl
git fetch origin pull/1275/head
git checkout FETCH_HEAD
mkdir build1; cd build1
cmake .. -DQHULL=off -DPYTHON=off
```

**Comment by GillesDuvert** [comment]
OK, @alaingdl pease test anew, but this seems 100% OK

**Comment by alaingdl** [comment]
Sorry, I was off this afternoon.

See from quick & dirty tests : 
-- starting "quick_start_GDL.sh" is back with good !PATH
-- yes, speed seems to be 3 to 5 time faster *but* I have to check it carefully !

Bravo !
A.

**Comment by GillesDuvert** [comment]
the problem with plplot driver will hopefully be solved by the next PR

**Pull request merged**
