### PR TITLE
WIP: Appveyor: streamline build, make more artifacts.

### PR DESCRIPTION
**Pull request by maynardGK**
This will reduce the GDL build to a bare minimum.
 fortran is not needed in plplot.
wxwidgets is not needed yet.
the artifact gdl_build.zip contains a build/ directory of the cmake output

### CODE REVIEW

**Comment by slayoo** [comment]
@maynardGK if these changes concern only Appveyor and Windows, perhaps it's worth to switch the Travis builds off temporarily for this branch (e.g. by renaming .travis.yml to .travis.yml.off or alike). Thanks

**Comment by maynardGK** [comment]
@slayoo I don't see any controls I have on travis. - No files in git tree with that name, no web buttons.
Appveyor scripts are so very fragile!  I'll close and re-open later

**Comment by slayoo** [comment]
```
$ git mv .travis.yml .travis.yml.off
```
should do, HTH!
Big thanks for fighting with Appveyor!

**Comment by maynardGK** [comment]
d833622 Appveyor failed after successful build, all tests caught exceptions. - log14.txt
first travis build is good, closing for now.
583372c $env:PATH=$env:PATH;C:/projects/gdl/mingw/mingw32/lib
C:/projects/gdl/mingw/mingw32/lib : The term 'C:/projects/gdl/mingw/mingw32/lib' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
b231f05 yet again exception exits
path: C:/projects/gdl/mingw/mingw32/lib;C:/projects/gdl/mingw/mingw32/bin;C:\ ... etc

daab59f again, same thing.

 
d3d5e4d reverting... but not quite.  Failed on make check - probably wrong directory
Everything is Ok
set PATH=%PATH%;C:/projects/gdl/win32libs/lib;c:\projects\gdl\mingw\mingw32\lib
set PATH=%PATH%;C:/projects/gdl/win32libs/bin;c:\projects\gdl\mingw\mingw32\bin
set PATH=%PATH%;C:/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev1/mingw32/i686-w64-mingw32/lib
mingw32-make check
mingw32-make: *** No rule to make target 'check'.  Stop.
Command exited with code 2
cat c:\projects\gdl\build\testsuite\Testing\Temporary\LastTest.log

**Comment by maynardGK** [comment]
b231f05 yet again exception exits
 path:  C:/projects/gdl/mingw/mingw32/lib;C:/projects/gdl/mingw/mingw32/bin;C:\ ... etc

**Comment by maynardGK** [comment]
0af1de3
100% tests passed, 0 tests failed out of 104
Total Test time (real) =  32.62 sec
[100%] Built target check
Reversion works.  Now to find which package make GDL sick.
We're already downloading GSL. add to that zlib and libpng for next.
3db7413 had downloading problems. Also eigen3 was not built for win32lib nor d-loaded.

Then swap out/in eigen try this now.
dd2e1b5 can't get tested, exceptions. go back take out zlib, libpng verify reversion

795155c zlib download failed.
Extracting archive: zlib-1.2.3-lib.zip
7z : ERROR: zlib-1.2.3-lib.zip
At line:87 char:3
+   7z x zlib-1.2.3-lib.zip
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: zlib-1.2.3-lib.zip:String) [], RemoteException

get zlib from repo 

Then readline6/systre/tre .vs. readline5

**Comment by maynardGK** [comment]
0100d46 That fail was another fluke. plplot didn't get loaded from SF re-done, it succeeds.
Suggesting that libpng is poisoning the build.  let's add more:

376114c eigen3 in from repo instead of being built.
ok! Now to find where Libpng goes wrong.  This was 1.6.34-1   02-Oct-2017 11:35
next is -libpng-1.6.17-2-any.pkg.tar.xz      30-Jun-2015 07:29 Good!
Now -libpng-1.6.24-1-any.pkg.tar.xz      29-Aug-2016 04:04 Still before gcc6.3
 if that works, the last I'll try is libpng-1.6.29-1-any.pkg.tar.xz.sig  22-Mar-2017 07:21 which is last of gcc6.3. 29-1 didn't work, back at 24-1. - which works.
gcc6.3 started usage 12-Jan 2017
26-1-any.pkg.tar.xz      21-Oct-2016 05:31 is gcc 6.2.0-2 since 24-Sep 2016

**Comment by maynardGK** [comment]
This built ok. Most of the tests added (re-inserted) are tests of routines from file.cpp mostly getting segfaults in copy, move, test, lines.  Add to that the woes of building using up-to-date readline and
support libraries; I'[m disinclined to update my own msys/mingw which is vintage gcc 5.3.0

00:08:08] 95% tests passed, 6 tests failed out of 110
[00:08:08] 
[00:08:08] Total Test time (real) =  33.52 sec
[00:08:08] 
[00:08:08] The following tests FAILED:
[00:08:08] 	 66 - test_file_copy.pro (SEGFAULT)
[00:08:08] 	 68 - test_file_lines.pro (SEGFAULT)
[00:08:08] 	 69 - test_file_move.pro (SEGFAULT)
[00:08:08] 	 71 - test_file_test.pro (SEGFAULT)
[00:08:08] 	 72 - test_file_which.pro (Failed)
[00:08:08] 	 89 - test_obj_isa.pro (Failed)
[00:08:08] Errors while running CTest

**Comment by slayoo** [comment]
@maynardGK should we submit the plplot patch upstream?

**Comment by maynardGK** [comment]
@slayoo I've made a new commit in tests_1 PR that has the conclusions here.

**Pull request closed without merging**
