### PR TITLE
Improved DILATE and ERODE

### PR DESCRIPTION
**Pull request by rexso**
The DILATE and ERODE implementations have now been improved by reducing the depth of some loops.

### CODE REVIEW

**Comment by alaingdl** [comment]
Hi. I do not understand why the Travis runs for OSX are reported as failed ?
https://travis-ci.org/gnudatalanguage/gdl/jobs/429530685

**Comment by slayoo** [comment]
Alain, that's because of #460 (the "darwin" -> "mac os x" issue introduced in #457)
As of now master branch CI fails, hence any PR will have negative CI result

**Comment by rexso** [comment]
Appveyor failing seems to be unrelated to the PR as well:

```
Extracting archive: pcre-7.0-lib.zip
7z : ERROR: pcre-7.0-lib.zip
At line:72 char:3
+   7z x pcre-7.0-lib.zip
+   ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: pcre-7.0-lib.zip:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Can not open the file as archive
```

**Comment by slayoo** [comment]
Appveyor build restarted

**Comment by slayoo** [comment]
helped

**Comment by slayoo** [comment]
closed and reopened to trigger build against current master (OSX probelm should be fixed)

**Comment by rexso** [comment]
OSX problem seems to be fixed indeed. One of the linux builds failed due to timeout however.

**Comment by slayoo** [comment]
all CI ok now

**Comment by rexso** [comment]
Looks good :+1:

**Comment by alaingdl** [comment]
I see no reason to delay that. Please remember I already rename the internal code ERODE & DILATE and, after few tests, they are working only on plain 2D images ...

(I do not make tests on results & bench up to now)

**Pull request merged**
