### PR TITLE
close #1781 (TICK_GET error)

### LINKED ISSUE #1781: strange error message for [X|Y|Z]TICK_GET when using Coyote library
Can anybody check if this is a GDL problem or a Coyote library problem?

```
GDL> x=findgen(100) & y=x^2
GDL> cgzplot,x,y
```

gives the following error message:
```
CGPLOT--> PLOT: Internal GDL error for [X|Y|Z]TICK_GET, please report
```

### PR DESCRIPTION
**Pull request by GillesDuvert**
oops getLabelingValues was wrongly clearing values.
Also, insure only the 1st axis values are reported

### CODE REVIEW

**Comment by alaingdl** [comment]
As shown by new test file in #1786 `test_xyztick_get.pro` this PR is not fully ok :(
(bon courage @GillesDuvert )

**Comment by alaingdl** [comment]
Hi Gilles

(we have a /debug in `test_xyztick_get.pro` to print, the expected versus the computed ticks)

for me we still few works on that :
```
GDL> plot, findgen(63)-500, xtick_g=x1, ytick_g=y1
GDL> print, x1, y1
       0.0000000       10.000000       20.000000       30.000000       40.000000       50.000000
       60.000000       70.000000
      -500.00000      -490.00000      -480.00000      -470.00000      -460.00000      -450.00000
      -440.00000      -430.00000

IDL> plot, findgen(63)-500, xtick_g=x1, ytick_g=y1
IDL> print, x1, y1
       0.0000000       20.000000       40.000000       60.000000       80.000000
      -500.00000      -480.00000      -460.00000      -440.00000      -420.00000
```
(derived from the 3d case (SURFACE))

the good point is we have a way to make automatic tests on that ...

Those ranges were OK since years (at least from gdl-1.0.1git220829 to gdl-1.0.3git230929)

**Comment by alaingdl** [comment]
but #1701 is even worse !
thanks @GillesDuvert the code survives now to the updated tests `test_xyztick_get` !

just a detail : 
```
/home/gdl/GDL/TestPR1785/gdl/src/plotting.cpp: In function ‘void lib::doOurOwnFormat(PLFLT, char*, PLINT, PLPointer)’:
/home/gdl/GDL/TestPR1785/gdl/src/plotting.cpp:1542:38: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 4 has type ‘__gnu_cxx::__promote_2<int, double, double, double>::__type’ {aka ‘double’} [-Wformat=]
 1542 |           snprintf(label, length, "%.*f", pow(10, value), prec);
      |                                    ~~^~   ~~~~~~~~~~~~~~
      |                                      |       |
      |                                      int     __gnu_cxx::__promote_2<int, double, double, double>::__type {aka double}
/home/gdl/GDL/TestPR1785/gdl/src/plotting.cpp:1542:39: warning: format ‘%f’ expects argument of type ‘double’, but argument 5 has type ‘int’ [-Wformat=]
 1542 |           snprintf(label, length, "%.*f", pow(10, value), prec);
      |                                    ~~~^                   ~~~~
      |                                       |                   |
      |                                       double              int
      |                                    %.*d
[ 27%] Linking CXX executable gdl
[100%] Built target gdl
```

**Comment by GillesDuvert** [comment]
> but #1701 is even worse ! thanks @GillesDuvert the code survives now to the updated tests `test_xyztick_get` !
> 
> just a detail :
> 
> ```
> /home/gdl/GDL/TestPR1785/gdl/src/plotting.cpp: In function ‘void lib::doOurOwnFormat(PLFLT, char*, PLINT, PLPointer)’:
> /home/gdl/GDL/TestPR1785/gdl/src/plotting.cpp:1542:38: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 4 has type ‘__gnu_cxx::__promote_2<int, double, double, double>::__type’ {aka ‘double’} [-Wformat=]
>  1542 |           snprintf(label, length, "%.*f", pow(10, value), prec);
>       |                                    ~~^~   ~~~~~~~~~~~~~~
>       |                                      |       |
>       |                                      int     __gnu_cxx::__promote_2<int, double, double, double>::__type {aka double}
> /home/gdl/GDL/TestPR1785/gdl/src/plotting.cpp:1542:39: warning: format ‘%f’ expects argument of type ‘double’, but argument 5 has type ‘int’ [-Wformat=]
>  1542 |           snprintf(label, length, "%.*f", pow(10, value), prec);
>       |                                    ~~~^                   ~~~~
>       |                                       |                   |
>       |                                       double              int
>       |                                    %.*d
> [ 27%] Linking CXX executable gdl
> [100%] Built target gdl
> ```

done, and it was important.

**Pull request merged**
