### PR TITLE
Add H5T_COMPOUND support to 'h5d_read_fun()'

### PR DESCRIPTION
**Pull request by ogressel**
I branched this off from the previous pull request (#1170), hope that's okay... is there a better way doing this, maybe via cherry-picking?

The tutorial for creating structures in the HACKING file is rather basic, can someone please check that my implementation conforms to GDL standards in that regard?

Thanks.

### CODE REVIEW

**Comment by slayoo** [comment]
Thanks a lot @ogressel

In the Github Actions logs, the newly added test actually fails:
```
         Start 103: test_hdf5.pro
103/193 Test #103: test_hdf5.pro ......................Subprocess aborted***Exception:   1.68 sec
```

this was not being detected by our CI scripts earlier, but following last week's changes, it should be detected (and rd-flagged) now, and also additional output should be printed, let me then close & reopen to trigger build with the new CI scripts.

**Comment by slayoo** [comment]
So here's some more info from the logs:
```
102/190 Test #102: test_hdf5.pro ......................Subprocess aborted***Exception:   0.90 sec
Unable to init server: Could not connect: Connection refused
15:34:28: Error: Unable to initialize GTK+, is DISPLAY set properly?
WARNING: wxWidgets not initializing, widget-related commands will not be available.
% Compiled module: TEST_HDF5.
% Compiled module: FILE_SEARCH_FOR_TESTSUITE.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
gdl: /home/runner/work/gdl/gdl/src/dimension.hpp:79: dimension::dimension(SizeT): Assertion `d0 != 0' failed.
[fv-az200-620:09853] *** Process received signal ***
[fv-az200-620:09853] Signal: Aborted (6)
[fv-az200-620:09853] Signal code:  (-6)
```

**Comment by GillesDuvert** [comment]
...meaning that a dimension() is zero, e.g.,uncheck at line 348 of hdf5_fun ?
... this is an asser() should not appear if compiled -DNDEBUG

**Comment by ogressel** [comment]
I am explicitly catching the 'rank==0' case now, which should take care of the assertion. Just realizing that this will also affect my other pull request... so something will have to get merged/rebased to make that build properly.

**Comment by ogressel** [comment]
I have now moved the previous commit upstream to the `addh5s_select_hyperslab` branch.

**Comment by slayoo** [comment]
@ogressel after merging the two other PRs, there's a merge conflict here - could you please have a look.
Big kudos for improving the HDF5 support! Thank you!

**Comment by ogressel** [comment]
Thanks. I already encountered these when trying to rebase the branch yesterday. Fortunately, they were trivial to fix (but a good reminder to be super pedantic when committing changes). Sorry for the force push, there is probably a more elegant way to do this...

**Pull request merged**
