### PR TITLE
Help_pro refurbishment and code cleanup: gdlhelp.cpp

### PR DESCRIPTION
**Pull request by maynardGK**
The help routine had been included with the basic_pro set of routines
and it grew to become the largest single routine with the most keywords.
It grew in increments and so is a challenge to decipher.
These changes put much of the formatting code in subroutines called from
help_pro, allowing the flow and logic of help_pro to be more approachable.
pretty much the same as it was.

Some new features of help will  also be present:
   Output=<variable> is implemented in many more places.
   names = <reg expression> used with other output to restrict the matches found.
   HEAP numerates object and pointer heap, also more detail if FULL is specified.
   COMMON will list all common blocks anywhere in program
         The method commonPtrs of class DSubUD is added in dpro.hpp
   OBJECT, METHODS keywords for use with objects.
   DEBUG  will set or unset a debug flag that persists for session.

Other behavior changes:
 - For undefined variables, no output is generated unless /FULL keyword is also present.
 - the /STRUCT keyword, which is in effect if a structure is the sole parameter, will
  invoke a recursive description of any sub-structures.  The one-line description
  will always be present, before the detailed structure listing.

testsuite/test_help.pro is a very rudimentary start of several features.

gdlhelp_fin
Greg Jung (maynardGK)
gvjung@gmail.com

### CODE REVIEW

**Comment by maynardGK** [comment]
I can confirm the failure in Opensuse with TEST_ANGLES.pro for cause unrelated to help routine.
In Windows, test_angles doesn't fail. (Also similar test failures - more of them, and not test_angles.pro) on the basic_fun branch (and no corresponding failures in the windows 7 build, using MINGW32).

**Comment by maynardGK** [comment]
commit 1ad64af may have fixed the test_angles failure if the LEVEL keyword section code, which was executed (at that time) before every standard parameter list, caused memory allocation errors due to the error (?) fixed in commit de6ba6c.  Why, ever, test_tic_toc failed is unexplained.

**Comment by slayoo** [comment]
Closing and reopening to trigger codecov and appveyor runs

**Comment by maynardGK** [comment]
Status as I close and re-open this, it seems to be stuck on appveryor.

continuous-integration/appveyor/pr Pending — Waiting for AppVeyor build to complete
Codacy/PR Quality Review — Up to standards. A positive pull request.
continuous-integration/travis-ci/pr — The Travis CI build passed
This branch has no conflicts with the base branch

**Comment by GillesDuvert** [comment]
closing & reopening to retrigger tests after all the changes in master

**Comment by GillesDuvert** [comment]
Unfortunately GDLInterpreter only was changed, although this file is reconstructed from the ANTLR sources. It will take some time to align this version to the ANTLR sources.

**Comment by maynardGK** [comment]
@GillesDuvert gdlc.g and gdlc.i.g are completed among the several branch PRs I have made, and 
so I have combined all of the inter-related branches into a new branch, "combo", which built with only minor conflicts and one patch to GDLParser.hpp which is reflected in gdlc.g of that branch.
  From opensuse leap 42.x the "make check" completed well, failing on those test already failing:
7% tests passed, 7 tests failed out of 211
Total Test time (real) = 140.14 sec
The following tests FAILED:
         94 - test_fft_leak.pro (Failed)
         97 - test_file_delete.pro (Failed)
        142 - test_n_tags.pro (Failed)
        152 - test_parse_url.pro (Failed)
        175 - test_resolve_routine.pro (Failed)
        177 - test_rounding.pro (Failed)
        199 - test_total.pro (Failed)

**Pull request closed without merging**
