### PR TITLE
add test_write_csv.pro

### PR DESCRIPTION
**Pull request by brbarker**
Added "test_write_csv.pro" to testsuite and this is a record for that

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you, yet this branch (brbarker:patch-3) does not contain the ``text_write_csv.pro`` file. You can add the file to this branch by going to https://github.com/brbarker/gdl/new/patch-3/testsuite and clicking on "Add file" in the right hand side of the screen as in this screenshot: 
image

**Comment by slayoo** [comment]
the test was not run because there's a typo: ``text_write_csv``, should be ``test_write_csv``. I've just corrected it.

**Comment by brbarker** [comment]
Thank you. Sorry about that. I'll be more careful.

**Comment by slayoo** [comment]
Now, it is run, but it succeeds (even though the fix is not yet in place):
```
        Start 194: test_write_csv.pro
194/194 Test #194: test_write_csv.pro .................   Passed    0.48 sec
```
How to change the test file so that it triggers the error?

**Comment by brbarker** [comment]
It shouldn't need any changes. The test_write_csv triggers it on my machine. I've attached a screenshot so you can see.
Error_Shot

**Comment by slayoo** [comment]
Ah, indeed, sorry, we need to enclose it within something like ```  if execute(...) ne 1 then exit, status=1```

**Comment by brbarker** [comment]
Okay, you're going to have to help me out here. I'm sorry. I was looking at other bug test files to see what you mean, but I couldn't decide. I've attached a picture with two options of what I think you want. I think it would help if I understood what this `if statement` was doing. What is it testing?
Issue_work

**Comment by slayoo** [comment]
Definitely, the second option is what we need here.
The `IF` checks the return value of `execute` (https://www.l3harrisgeospatial.com/docs/execute.html) which will not be 1 if the  code fails.
Thanks!
Sylwester

**Comment by brbarker** [comment]
Okay, awesome. I just edited the test file that I uploaded so that it is written like the second option.

**Comment by slayoo** [comment]
Still, ``execute`` requires its argument to be a string, .e.g. ``execute("print, 123")``

**Comment by brbarker** [comment]
Okay, I missed the string, but I just added it.

**Comment by slayoo** [comment]
the quotes within string need to be escaped - just corrected it

**Comment by slayoo** [comment]
now in the logs we can see:
```
        Start 194: test_write_csv.pro
194/194 Test #194: test_write_csv.pro .................***Failed    0.47 sec

```
success! thank you!

(the "Failed" should change to "Passed" after we merge the fix)

**Comment by slayoo** [comment]
fix merged: https://github.com/gnudatalanguage/gdl/pull/1179
let's close & reopen to trigger a build with the updated GDL code

**Comment by slayoo** [comment]
```
        Start 194: test_write_csv.pro
194/194 Test #194: test_write_csv.pro .................   Passed    0.46 sec
```
Hurray! Thank you @brbarker

**Comment by brbarker** [comment]
Thank you for your help @slayoo! I see you've been doing work while I was in class today, so I appreciate it! Is there anything else that needs to be done on my end?

**Comment by slayoo** [comment]
Both the fix and the test are now merged and will be part of the upcoming release.
Please do report any other issues you come across, thanks again

**Pull request merged**
