### PR TITLE
file_etc branch now has all file.cpp improvements.

### PR DESCRIPTION
**Pull request by maynardGK**
These procedures are to be used to retest performance of the
file_copy, file_delete, file_move, etc. that were based on IDL
 procedures and using the spawn command.  These functions are now
invoked directly from compiled C++ code.  Because the compiled routines
 take precedence, the old procedures can only be invoked with different
names and so file_copy, file_delete, and file_move are reproduced as file_T_copy, etc.

The corresponding test routine is also provided (i.e. test_file_t_copy).
Under normal circumstances, routines from this directory will be compiled
in preference to the routines of the same name in the testsuite directory
 that holds them. Some modifications were made to make them operable
 in a windows-based GDL (invoked via command line from an MSYS shell).

Greg Jung (aka maynardGK)
gvjung@gmail.com

### CODE REVIEW

**Comment by slayoo** [comment]
CI failed above due to a network error while downloading a package - restared.

**Comment by slayoo** [comment]
Thanks!

Some questions:
- there is no change to Makefile.am, hence no new tests are added to "make check" workflow - is it OK?
- these new files are copied into testsuite, but the old files are left in src/pro - is it OK?

**Comment by GillesDuvert** [comment]
@maynardGK 
Hi! You say that file_copy, file_move and file_delete are now in C++ code, but that's not the case?

**Comment by maynardGK** [comment]
On Tue, Apr 10, 2018 at 4:25 AM, GillesDuvert <notifications@github.com>
wrote:

> @maynardGK <https://github.com/maynardGK>
> Hi! You say that file_copy, file_move and file_delete are now in C++ code,
> but that's not the case?
>

 No but they will be. So, the comment is ahead of time.
 I want to set up the testing procedures  to be in place once the file_XXXX routines are in.
Greg

**Comment by maynardGK** [comment]
I will be pushing a new commit on this branch, the test_file_T_XXXX routines did not have 
the correct procedure name.

**Comment by maynardGK** [comment]
I am working on more commits, test_file_t_copy,  test_file_t_delete,  test_file_t_move should still be working on Linux, and also will work with GDL running windows via an MSYS shell. 
 The current test_file_search, & etc do not take consideration for windows (mostly for weird filnames that are not legal in Windows), so these will also be fixed.

**Comment by maynardGK** [comment]
I don't know how that conflict got here - it indicates the file_lines routine which hasn't been
applied yet, and I excluded (?) it from the commit.   I suppose it was added and master:src/file.cpp was updated while I was working on it.
 https://githowto.com/resolving_conflicts
 In any case, I commented out the file_lines block as this is another yet new addition and should get its own commit.  I made a short featureless file_lines.pro and stuck it in testsuite in order that the test routines would run.

**Comment by maynardGK** [comment]
I re-inserted file_lines routine that already had support in file.hpp, libinit.cpp but I changed libinit.cpp to not include it, so that it can enjoy its own separate commit (including a testsuite/test_file_lines.pro!). A working FILE_LINES procedure, that can work with a vector string of filenames, is provided in testsuite/file_lines.pro

**Comment by maynardGK** [comment]
The  test_file_move and  test_wordexp do not show failure on my linux.

**Comment by slayoo** [comment]
Here's a list of error messages for the failing tests (from the icc/Debug build):

```
% Compiled module: TEST_BUG_2876372.
% TEST_BUG_2876372: GSL Error #8: failed to allocate space for histogram ranges
% LA_TRIRED: Expression must be an array in this context: <Expression> <INT       (       1)>
```

```
% Compiled module: TEST_BUG_3376577.
% Compiled module: FILE_SEARCH_FOR_TESTSUITE.
% Compiled module: PATH_SEP.
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

```
% Compiled module: TEST_CALL_EXTERNAL.
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

```
% Compiled module: TEST_CONGRID.
% Compiled module: CONGRID.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_CONGRID_BASIC:   NO errors encountered during TEST_CONGRID_BASIC tests  
% Compiled module: ERRORS_CUMUL.
% TEST_CONGRID_BASIC:   NO errors encountered during TEST_CONGRID_BASIC tests  
% TEST_CONGRID_BASIC:   NO errors encountered during TEST_CONGRID_BASIC tests  
% TEST_CONGRID_BASIC:   NO errors encountered during TEST_CONGRID_BASIC tests  
% TEST_CONGRID_BASIC:   NO errors encountered during TEST_CONGRID_BASIC tests  
% TEST_CONGRID_BASIC:   NO errors encountered during TEST_CONGRID_BASIC tests  
% Compiled module: GET_IMAGE_FOR_TESTSUITE.
% Compiled module: FILE_SEARCH_FOR_TESTSUITE.
% Compiled module: PATH_SEP.
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

```
% Compiled module: TEST_FILE_MOVE.
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

```
% Compiled module: TEST_HDF5.
% Compiled module: FILE_SEARCH_FOR_TESTSUITE.
% Compiled module: PATH_SEP.
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

```
% Compiled module: TEST_POSTSCRIPT.
% Compiled module: GDL_IDL_FL.
% TEST_POSTSCRIPT_BASIC: writing file : GDL_ps_basic_1.ps
% TEST_POSTSCRIPT_BASIC: writing file : GDL_ps_basic_2.ps
% TEST_POSTSCRIPT_BASIC: writing file : GDL_ps_basic_3.ps
% TEST_POSTSCRIPT_BASIC: writing file : GDL_ps_basic_4_portrait.ps
% TEST_POSTSCRIPT_BASIC: writing file : GDL_ps_basic_4_land.ps
% TEST_POSTSCRIPT_APPLEMAN: writing file : GDL_appleman.ps
% Compiled module: APPLEMAN.
% Compiled module: LOADCT.
% LOADCT: Loading table BOW SPECIAL
% Compiled module: GET_IMAGE_FOR_TESTSUITE.
% Compiled module: FILE_SEARCH_FOR_TESTSUITE.
% Compiled module: PATH_SEP.
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

```
% Compiled module: TEST_WORDEXP.
% Compiled module: GDL_IDL_FL.
Working here : /tmp/test_GDL_WordExp
% Compiled module: PATH_SEP.
creating subdirs : normal/ spa ce/ q!mark/ mix,ing :s/
All subdirs were created
Creating some files in each subdirs : a1 a 2 a  3 a;4 a.5 a&6
All files have been created (Local)
% Compiled module: FILE_LINES.
All files have been created (Global)
% Compiled module: BANNER_FOR_TESTSUITE.
% TESTING FILE_BASENAME: 
  NO errors encountered during TESTING FILE_BASENAME tests  
% Compiled module: ERRORS_CUMUL.
% TESTING FILE_DIRNAME: 
  NO errors encountered during TESTING FILE_DIRNAME tests  
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

```
% Compiled module: TEST_XDR.
% Compiled module: PATH_SEP.
-quiet: /home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1170: int EnvT::KeywordIx(const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &): Assertion `val != -1' failed.
TEST EXITED FROM SIGNAL 6
```

HTH,
Sylwester

**Comment by maynardGK** [comment]
Thank you for that.  I believe what happened is, a line from "future" code has snuck into the code and
an unknown keyword has been table look-upped.  pro->FindVar(k) will return a "-1" if k is not a member
of the table and the envt:: routine at line 1170 of envt.cpp will pass this through an assert(val !- -1),
   I have modified envt.cpp so that this error is harmless, but it results in a 3-line diagnostic that indicates
where the issue is to be found (procedure/function name and lookup value). 
  I created a new branch, envt_keyword, for the fix to envt.cpp and a few minor patches, keeping it still close to 0.9.8 version. (other branches have bigger, unrelated changes to envt.cpp which will include the minor fixes), and I will submit a PR once I have built on Windows with these changes. To apply them to the larger branches (file_etc, gdlhelp_fin) I will change envt.cpp separately and commit on those.

**Comment by maynardGK** [comment]
And here it may be:
`
GDL> ff=file_search(".","test_obj_destroy.pro")
FILE_SEARCH  Key: ZERO_LENGTH
Invalid Keyword lookup (EnvT::KeywordIx) !
 Returning the wrong (but a valid) key index of zero
`

The initialized keyword was "ZERO" when it is supposed to be "ZERO_LENGTH" ( a shorthand for "test_zero_length").

**Comment by maynardGK** [comment]
This latest attempt, failed one test, "file_test"; my build on suse does -not- fail (see terminal output at end of message). This latest patch was quite trivial, yet the previous test series failed about 9 tests,
and running make check on a build of the master branch produces a similar list of failures:

- 
reg@linux-gc09:/f/github/gdlgit/testsuite> cat /d/bld/gdl/suse-branches/master_tests.ls 
The following tests FAILED:
         93 - test_fft_leak.pro (Failed)
         96 - test_file_delete.pro (Failed)
        103 - test_fix.pro (Failed)
        137 - test_n_tags.pro (Failed)
        143 - test_obj_isa.pro (Failed)
        145 - test_parse_url.pro (Failed)
        167 - test_resolve_routine.pro (Failed)
        169 - test_rounding.pro (Failed)
        191 - test_total.pro (Failed)
Errors while running CTest




`greg@linux-gc09:/d/bld/gdl/suse-gitbld> printenv | grep GDL
GDL_PATH=+/f/github/gdlgit
greg@linux-gc09:/d/bld/gdl/suse-gitbld> cd /f/github/gdlgit/testsuite/
greg@linux-gc09:/f/github/gdlgit/testsuite> ../src/gdl

  GDL - GNU Data Language, Version 0.9.8 svn

- For basic information type HELP,/INFO
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at:
  http://sourceforge.net/projects/gnudatalanguage/

GDL> test_file_test
% Compiled module: TEST_FILE_TEST.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FILE_TEST: =======================================================
% TEST_FILE_TEST: =                                                     =
% TEST_FILE_TEST: =  NO errors encountered during TEST_FILE_TEST tests  =
% TEST_FILE_TEST: =                                                     =
% TEST_FILE_TEST: =======================================================
GDL> exit
greg@linux-gc09:/f/github/gdlgit/testsuite> ls -lat ../src/gdl
lrwxrwxrwx 1 root root 74 Apr 20 19:29 ../src/gdl -> /d/bld/gdl/suse-branches/file_etc
`
in

**Comment by slayoo** [comment]
Will close and reopen to check this would trigger a Windows build

**Comment by slayoo** [comment]
Hurray! Building on Windows in progress

**Comment by slayoo** [comment]
closing and reopening to trigger test execution on appveyor

**Comment by maynardGK** [comment]
@slayoo @GillesDuvert This has been ready now, and now it has been recently de-conflicted to the current master.

**Comment by slayoo** [comment]
As of now, none of the *_file_* tests are run on Appveyor as they are disabled in appveyor.yml - could any of them be re-enabled with these changes?

**Comment by slayoo** [comment]
see e.g. https://ci.appveyor.com/project/slayoo/gdl/build/1.0.247#L7667

**Comment by slayoo** [comment]
The disabling is done here: https://github.com/gnudatalanguage/gdl/blob/master/appveyor.yml#L103

**Comment by GillesDuvert** [comment]
@maynardGK , could you make available in this PR  the changes in branch https://github.com/GillesDuvert/gdl/tree/maynard_s_files (last commit https://github.com/gnudatalanguage/gdl/commit/06abd69a10624d0bcb5dfd7f719f43cbbe64a04c) ? Mainly, it is to push the old procedures and tests in a subdirectory and take into account that PR #37 and #256 cover file_lines(). I believe that will do it. Many thanks!

**Comment by maynardGK** [comment]
Travis build errored:
==> Downloading https://homebrew.bintray.com/bottles/llvm-6.0.0.sierra.bottle.ta
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "llvm"
Download failed: https://homebrew.bintray.com/bottles/llvm-6.0.0.sierra.bottle.tar.gz

**Comment by maynardGK** [comment]
https://homebrew.bintray.com/bottles/llvm-6.0.0.sierra.bottle.tar.gz working for me now, close & re-open

**Pull request merged**
