### PR TITLE
Fixes to netCDF4 and hdf5

### PR DESCRIPTION
**Pull request by rsiddans**
Fixes to add missing NetCDF4 datatypes and fix bug reading some float types in HDF5

### CODE REVIEW

**Comment by rsiddans** [comment]
Related to issue #1922 and #1923

**Comment by rsiddans** [comment]
Also note I included the code change suggested in #1744 to hdf_fun.cpp, so that it can read (a single) variable length string.

There will remain limitations in both hdf and netcdf for reading arrays of strings (as opposed to char) - however I think string arrays are unusual to find in netcdf files. (Scalar strings attributes are very common though and these can now be read with these changes.)

**Comment by rsiddans** [comment]
Actually a couple of other changes are included in this code:
- keywords gzip+shuffle are added to ncdf_vardef (allowing internal compression to be enabled)
- there is a fix in map_proj_init.pro to remove a limit of 80 degrees, which should not apply to the default map projection (cylindrical) - In IDL by default map_set gives a map covering the full globe to +/-90 deg. The 80 degree limit is relevant for the mercator projection.

**Comment by GillesDuvert** [comment]
@rsiddans please remove plplot_config.h and plDevs.h from your PR. They should not be here, and I've no obvious mean to remove them .

**Comment by GillesDuvert** [comment]
and thanks!

**Comment by GillesDuvert** [comment]
@rsiddans sorry, I found how to delete the 'offending files' from here.

**Comment by rsiddans** [comment]
> @rsiddans sorry, I found how to delete the 'offending files' from here.

OK thanks - sorry not sure why those files were there & many thanks again for all the help.

**Comment by GillesDuvert** [comment]
@rsiddans additionnal thanks to have spotted the map_set problem.

**Pull request merged**
