### PR TITLE
Added implementation for TERMINAL_SIZE. No support for setting width/…

### PR DESCRIPTION
**Pull request by hillbergt**
…height yet though.

### CODE REVIEW

**Comment by GillesDuvert** [comment]
close and reopen, to be sure.

**Comment by GillesDuvert** [comment]
reopen, test compiles same ?

**Comment by maynardGK** [comment]
My guess is that TermHeight() is acquired accidentally when GCC is used with DEPS=FULL;
There's no assignment to lib:: in terminfo.cpp but how does a TermWidth() call (from gdl and from print) pass through?

**Comment by alaingdl** [comment]
related to what I did last week. Problem of missing TermHeight() should be solved

I will accept it now and check further

**Pull request merged**
