### PR TITLE
strip first char of version string for !GDL.RELEASE if it is "v"

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by alaingdl** [comment]
I need few time to do it quietly ! I hope to be able to review and test possible side effects this Monday

**Comment by slayoo** [comment]
thanks Alain

**Comment by alaingdl** [comment]
Since I change `gdl_version.pro` in #1786 it is OK for me to merge that.

**Comment by slayoo** [comment]
Thanks @alaingdl

**Pull request merged**
