### PR TITLE
Changing old parse_url() to parse_url_php() and adding a new parse_url() compatible with IDL

### PR DESCRIPTION
**Pull request by sflinois**
This change was made to address the issue : test_parse_url is failing #153
The parse_url() that was implemented was based on the php parse_url() which has some advantages. I kept it and renamed it parse_url_php(). I also renamed test_parse_url.pro into test_parse_url_php.pro.

I implemented a new parse_url() based on the IDL version of the function and created some tests in test_parse_url.pro

It is my first contribution to GDL, every feedback is appreciated !

### CODE REVIEW

**Comment by sflinois** [comment]
I should have asked before making the pull request, but i have some questions about codecov and how functions are implemented in GDL.

I'm not really sure how codecov work, I guess it uses the testsuite from GDL and check if the tests cover well the code. I don't really know.

I also did not put the test_parse_url_php.pro in the testsuite, since it was not compatible with IDL i thought it might cause problems. 
I also put the parse_url_php() function in basic_fun.cpp, i also don't know if there is any other place i should have put it.
Maybe the old parse_url should have juste been replaced and not changed to a different name

**Comment by slayoo** [comment]
@sflinois big thanks for the PR and apologies for delayed response.

Re codecov: one of the travis builds has the CODECOV env var set which triggers addition of additional code-usage-tracking flags for the compiler. Then, after execution of tests, the statistics are uploaded to codecov.io to generate the reports. For more details, please have a look at this commit in which the service was introduced: https://github.com/gnudatalanguage/gdl/commit/a437102b2d922cd8c6e437e9d633c9096151ebe5

I haven't had a look at your changes yet, but one key thing would be to re-enable execution of the url test file in the .travis.yml file. It is disabled there temporarily: https://github.com/gnudatalanguage/gdl/blob/master/.travis.yml#L52 (in order to enable Travis help us catch regressions - since this test was failing at "commit zero" on github, executing it would give always a failure for the whole CI run).

HTH, thanks again!
Sylwester

**Comment by slayoo** [comment]
Thanks!
+ I vote for removing the old PHP-based version

**Comment by slayoo** [comment]
Just one last comment: I suggest removing the comment block beginning with SA (which was meant to mean my initials ;)): https://github.com/gnudatalanguage/gdl/pull/283/files#diff-86f6cdbb810c527276cef16f6b0be541R8022
In particular, the code can only be based on IDL behaviour not on IDL code - and I hope this is the case here!
Thanks, S.

**Comment by sflinois** [comment]
Alright, i will remove the comment block with SA, sorry about that ^^
I found cases where PARSE_URL throws exceptions :
> GDL> parse_url("http://example/dir?query:port")
> InterpreterLoop: Exception: basic_string::_M_create
> GDL> parse_url("http://example/dir:port?query")
> InterpreterLoop: Exception: basic_string::_M_create
> GDL> parse_url("http://example:port?query/dir")
> InterpreterLoop: Exception: basic_string::_M_create

I'll rewrite the function and add the cases to the testsuite :)

**Comment by slayoo** [comment]
Thanks again!

**Pull request merged**
