### PR TITLE
Parallel minmax

### PR DESCRIPTION
**Pull request by GillesDuvert**
Done from a branch, as suggested by @slayoo , and hopefully will pass compilation with CLANG

### CODE REVIEW

**Comment by GillesDuvert** [comment]
Hi, I'm annoyed by "Codacy/PR Quality Review". #ifdef code is correct and cppcheck gives no error on this file.

**Comment by slayoo** [comment]
Gilles, just ignore it! :)

**Comment by slayoo** [comment]
Please note that the testsuite is as of now only executed on OSX on Travis, hence only on clang, hence without OpenMP. I hope to get the tests running also on other builds soon.

**Comment by slayoo** [comment]
From now on Travis will also execute tests for the Intel compiler build which includes OpenMP.

**Comment by slayoo** [comment]
The merge conflict is around here:
```
3474 <<<<<<< HEAD
3475     bool absSet = e->KeywordSet(absIx); // not KeywordPresent as it should be ignored if not set.
3476 =======
3477     bool absSet = e->KeywordPresent(absIx); // not KeywordPresent as it should be ignored if not set.
3478 >>>>>>> fd94847f1c70672ff85d8c34da7d9fcaecea5bef
```

**Comment by slayoo** [comment]
Also, test_minmax.pro is not included yet in the Makefile.am list so it does not get executed by "make check"

**Pull request closed without merging**
