### PR TITLE
WIP: Track failure of windows' build (appveyor) on hashlist branch

### PR DESCRIPTION
**Pull request by maynardGK**
Puzzle! The merge from master in commit c8a4268
resulted in a branch which no longer links in windows, ( in the 64-bit case ) and also has problems in one case of travis tests. Unfortunately there are a lot of modifications that the merge brought in so where to look? This commit begins as a reversion of that PR to the last, best working repo, 4127137.
  The merges following this all seem pretty harmless; the suspected change in CMakeLists.txt was already tested #431 to be non-effective.

### CODE REVIEW

**Comment by maynardGK** [comment]
@slayoo @alaingdl @GillesDuvert 
The Appveyor build no longer builds successfully as it did for 4127137 - leading to the conclusion that it is due to a damaging change in the appveyor build software. It only fails for the 64-bit compilation; I've verified at home that it doesn't have issues.

 Travis build xxx.4 does not work: 

The command "if [ -v CODECOV ]; then make codecov; else make check; fi" exited with 2.

**Comment by maynardGK** [comment]
This is PR #431

**Comment by maynardGK** [comment]
Even though platform was 630x8664 the GCC used was 7.3; resetting platform to 730x8664 and see what happens.

**Comment by maynardGK** [comment]
Platform for 64-bit should be 630x8664 until eigen3 comes out with a version that does not induce compiler warnings. Still, zlib functions are not being found in appveyor using gcc 6.3, 7.3, or 7.2.
In PR #431 the Appveyor build is restricted to i686: both Release and Debug builds are available for
use.  Closing this PR until further experimentation is required.

**Comment by maynardGK** [comment]
zlib functions should be visible now that an MSYS script is being run for cmake... before, using 
  #- cmd /K scripts\mingw-bldgdl
the cmake program was catching c:\ruby193\bin\zlib1.dll ahead of where it was supposed to be found.

**Comment by maynardGK** [comment]
@GillesDuvert The test_deriv segmentation fault occurs in 32-bit build not in 64-bit build,
it is happening at the "where()" call in UNIQ(deriv(x)) where x = findgen(100)

```
------------- Test on Constant lines -------------
derivation of lines should give constant
Should plot 3 lines
% Stop encountered: TEST_DERIV          67 F:\github\gdlgit\testsuite\test_deriv.pro
GDL> wdelete
GDL> plot,findgen(100)
GDL> wdelete
GDL> help,x
X               FLOAT     = Array[101]
GDL> plot,x
GDL> xx=deriv(x)
GDL> iux=where(xx ne shift(xx,-1))
GDL> print,iux
          -1
GDL> help,arr
ARR             UNDEFINED = <Undefined>
GDL> arr=xx
GDL> ix = where(arr ne shift(arr, -1))
GDL> help,ix
bash: line 1: 13720 Segmentation fault      /f/github/gdlgit/install/gdl/bin/gdl
```

**Comment by GillesDuvert** [comment]
@maynardGK , thanks for the info. Looks like an alignment problem on 32 bit machines. Did you enable Eigen::?

**Comment by maynardGK** [comment]
@GillesDuvert
 The where() function is causing segfaults here in the 32-bit build; make check is last run in https://ci.appveyor.com/project/slayoo/gdl/builds/19940118/job/8p1nf763lpthpo9j
For now, the "make check" is disabled so that a downloadable artifact can be created.

 I've got widgets to work except that the plplot build, either msys or mingw, does not complete when wxWidget device is included.  ( At home, I don't have a problem building plplot with wxWidgets.)
The patch used for wxWidgets-3.0.2 needs to be expanded for 3.0.3, 3.0.4 because the file it changes
acquires more functions.  So 3.0.2-17 is used. 

Eigen3-3.3.4 is loaded from msys2 repo and GCC 6.3 is used to compile:  Using a newer version of GCC
 causes many many eigen3 warnings, also if eigen3-3.3.5 were used.

Apart from getting where() fixed, the next priority on this branch is to build GraphicsMagick
in Appveyor so that the quantum can be controlled.  Support libraries for GM are ready in 
appveyor_1.msys but not used unless a build will be attempted.

**Comment by maynardGK** [comment]
This branch no longer can compile in 64-bits. In 32-bits, the code is bugged with a segfault.  I will close
it here and copy appveyor.yml, scripts/ to a new branch based on reversion to 4127137.

**Pull request closed without merging**
