### PR TITLE
new try at parallel minmax

### PR DESCRIPTION
**Pull request by GillesDuvert**
New try again. Working with branches is clearly not my cup of tea.

### CODE REVIEW

**Comment by GillesDuvert** [comment]
OK leaving the icc petty problem, all in all it works. To be merged.

**Comment by slayoo** [comment]
Any idea why test_bytscl.pro and test_modulo.pro both fail after merging it? Leaving this as is will make all CI runs report "red" in pull requests. If the failures are to be ignored, please add these two files to the list of travis-ingored scripts in .travis.yml (sed one-liners in before_install section). Thanks

**Comment by GillesDuvert** [comment]
no idea, and it is not expected that all tests will pass anyway. Sometimes these test do not even pass with IDL8. I suspect a problem with the test procedure, not the test_xxx.pro files themselves. I will not look into this mess. Switching to python-scripted tests seems more elegant, too. And we need more non-regression tests comparing listings with reference listings.
How to make the test on travis and at the same time report "green"?

**Comment by slayoo** [comment]
Here is a pull request disabling these two tests: https://github.com/gnudatalanguage/gdl/pull/158
Could you please also mark which of the post-migration SVN commits are covered with this PR: https://github.com/gnudatalanguage/gdl/issues/127
Thanks!
S.

**Comment by GillesDuvert** [comment]
As GH gdl trunk is always a lot of commits behind (for good cause), I still try to have SF's SVN up-to-date in my (clumsy) manner. Up-to-date with my most recent developments and those of others that I have tested (on my machine), be they for good or not.
AFAIK this PR: #127 covers r 4095,4094,4093,4092

**Pull request merged**
