### PR TITLE
Hash/List functions in finished form & Appveyor build beef up (incl. publishing downloadable builds)

### PR DESCRIPTION
**Pull request by maynardGK**
HASH and LIST improvements were to be a separate PR but they were tacked into the Windows' build.
 Mostly all of the properties of HASH and LIST are now implemented with this change, which has radical changes to the list__overloadleftbracket and rightbracket routines. In hash.cpp, the /recursive option of the TOSTRUCT method is not working. "ordered hash" has a property flag but is not implemented. 

Win_build:

   GDL is built in appveyor using mingw-w64 compiler and support libraries built with this
compiler.   The  **scripts/appveyor_1.msys** sequence obtains those, pre-built, needed from the msys repository **http://repo.msys2.org/mingw/i686/**.    Some of these distributions have been found to not be compatible with other elements of the appveyor build. So, "version upgrades" need to be tested methodically.

  **wxwidgets** and **graphicsmagick** are the next two behemoth support libraries to be integrated.

The previous **appveyor.yml** included a build of wxWidgets which uses mingw32-make (not the msys make) and results in library and include files suitable for use by the "Windows" option of CMAKE.  Due to incomplete development of this branch in the cmake and plplot scripts, it wasn't getting included in the plplot build.  This build is preserved in  **scripts/wxmake_mingw**.bat (a  CMD script).

To create a custom plplot library used with GDL we use the cmake generator "MSYS Makefiles" in **scripts/appveyor_plplot.msys** and build with MSYS "make: instead of building with "mingw32-make".  This script can also be used "in place" from a home system configured (using symbolic links) to look like your git directory is /c/project/gdl.  For this custom build of plplot, three minor patches are applied from this script using the files of **/c/projects/gdl/scripts/patch**.  Two of these patches involve the WIN device driver, a) correct the keyboard focus in both wingcc and wingdi, and b) align structures in wingdi so that it can be used in GDL identically to wingcc.  In the GDL cmake command, an entry for the plplot-driver selector USE_WINGDI_NOT_WINGCC swaps the (patched) wingdi.dll in place of wingcc. Improvements in axes and labelling can be noticed, but there is still no anti-aliasing of the plot line.

  Using MSYS,  cmake scripting uses "unix-style" to find wxWidgets via extensive use of the /bin/wx-config script.  This usage is improved in the plplot build with a minor patch creating a convenient way to locate the library outside of its usual (as pointed to by wx-config)  location. 
  wxWidgets is not yet included in the GDL build because 1) the mingw32-make version won't work 2) the MSYS script is untested - a crucial "sed"  in there is needed for wx-config to put it together right. 
 As yet untested but possibly more useful for progress at home, **scripts/appveyor_gdl.msys** would build GDL using MSYS make.  
 
GraphicsMagick (GM) comes from **http://repo.msys2.org/mingw/i686/**  in 8-bit quantum form, which  isn't very interesting and also provides new test failures downstream (READ_JPEG); most complain that they prefer a 32-bit quantum.  A script is made for that, which can be run on a home MSYS installation, but the Appveyor machine does not seem to have enough to handle it.  When that can happen, the alternative directory can be named in the GDL build script  **scripts/mingw-bldgdl.bat**. 

Greg Jung
gvjung@gmail.com

### CODE REVIEW

**Comment by maynardGK** [comment]
Hanging up on plplot download request to Sourceforge

**Comment by maynardGK** [comment]
Againstuck at plplot.  Give it a rest.

**Comment by maynardGK** [comment]
@slayoo this is debug run with test of alternative exit codes, as you suggest.

**Comment by slayoo** [comment]
@maynardGK just to make sure - as of now, there is still just one build done on Appveyor, no Debug/Release matrix

**Comment by maynardGK** [comment]
Correct. Release only.

**Comment by slayoo** [comment]
Intentionally?

**Comment by maynardGK** [comment]
Yes, until someone wants to run GDB for every code change - and if there is a need to do that,
then the script can be changed.  The more usual origin of error is the absence of support libraries, for which one needs to download a build and running it from explorer (and no help from other mingw32 libraries) will notify user which is next library missing.  In some cases, the user might have different versions than thn what is requested, and the downloaded (in gdl/bin) library collection can serve as a PATH resource.(i.e. currently the library geotiff-2 asks for libproj-13 although other geotiff-2 versions might ask for libproj-12 or even libproj-9).

**Comment by slayoo** [comment]
I vote for retaining Debug/Release build matrix (if needed, without artefact upload for Debug). 
One reason is detection of assert-triggered regressions.

**Comment by maynardGK** [comment]
Bad plplot download from sourceforge.

**Comment by slayoo** [comment]
btw, in a recent Travis build log (https://api.travis-ci.org/v3/job/409985085/log.txt), I've found this:
```
% Compiled module: TEST_DELVARRNEW.

Assertion failed: (i<sz), function operator[], file /Users/travis/build/gnudatalanguage/gdl/src/datalistt.hpp, line 124.
```

**Comment by maynardGK** [comment]
For some reason, appveyor_plplot.msys is failing to find wxWidgets correctly :
(The last time it worked correctly was build 546 commit 866acd0 )
in appveryor_1.msys:
			```
		wxname=wxWidgets-3.0.4
		cd /c/projects/gdl/win32libs
		curl -O -s http://repo.msys2.org/mingw/${arch}/mingw-w64-${arch}-${wxname}-1-any.pkg.tar.xz
		tar xf mingw-w64-${arch}-${wxname}-1-any.pkg.tar.xz
		# this is magic sauce that allows wxwidgets to meld into GDL:
		sed -e "s;-Wl,--subsystem,windows -mwindows;;" -i ./mingw32/bin/wx-config
		mv mingw32 ../mingw/${wxname}


cd /c/projects/gdl/win32libs
			if [[ -f plplot-5.13.0.tar.gz ]] ; then
				tar xf plplot-5.13.0.tar.gz
			echo " win32libs/plplot-5.13.0.tar.gz decompressed (to win32libs/plplot-5.13.0/ )"
				. ../scripts/patch/patch_plplot.sh
				else

win32libs/plplot-5.13.0.tar.gz decompressed (to win32libs/plplot-5.13.0/ )
patching file plplot-5.13.0/cmake/modules/FindwxWidgets.cmake
patching file plplot-5.13.0/drivers/wingcc.c
patching file plplot-5.13.0/drivers/wingdi.c
appveyor_plplot: Architecture =  i686
 mingw-w64-i686-wxWidgets-3.0.4-1-any.pkg.tar.xz downloaded to <>/mingw. 

			
			echo "mname = "$mname "MNAME="$MNAME ", WXNAME="$WXNAME
			
		if [[ -d "$WXNAME" ]] ; then
			echo " mingw/wxWidgets directory already prepped :"$WXNAME
			pwd
			ls ./$WXNAME
			else
			mkdir temp
			cd temp
			tar xf ../mingw-w64-${arch}-wxWidgets-3.0.4-1-any.pkg.tar.xz
			cd .. && mv temp/$mname ./wxWidgets-3.0.4 && rm -r temp
			fi

mname = mingw32 MNAME= , WXNAME=wxWidgets-3.0.4
 mingw/wxWidgets directory already prepped :wxWidgets-3.0.4
/c/projects/gdl/mingw
bin
include
lib
share

but plplot cmake build isn't picking it up.

**Comment by maynardGK** [comment]
For windows' not my windows7 (8.1 and maybe 10) there is a console issue with this build, maybe 
solved by replacing readline7 with readline6.3 - I confirm it is solved for Win8.1
Build 593 uses readline 7, not useful except for win7;
build 600 uses readline 6.3 - looking good on win7 and win8.1 (and by extension, win10).

**Comment by slayoo** [comment]
closing and reopening to trigger build with fixed travis/osx/homebreq/numpy issue (#444)

**Comment by slayoo** [comment]
ping re Debug/Release builds :)

**Comment by maynardGK** [comment]
I'm fine with adding back the Debug build - its a single character modification - what I tried to do that didn't work was to add a 64-bit build, which should work ok but I wasn't able to get if{}elseif{} to work as a substitute for the if{} construct; the symbols are used, however, to generate builds based on MINGW32 or MINGW64.

**Comment by slayoo** [comment]
please elaborate on the if-else problem - I'll try to help

**Comment by maynardGK** [comment]
(Update: the issue I had below has been resolved; see e60e1e2)

**Comment by maynardGK** [comment]
@slayoo there is no response from appveyor about previous fail; if this fails at 64-bit plz
just commit to master and then we make a separate PR to exclude that until appveyor gets it
straight.  Commit contains hash/list almost completely implemented and legacy routines are a sorry status.

**Comment by maynardGK** [comment]
@slayoo  @alaingdl  @GillesDuvert  
Puzzle!  The merge from master in commit c8a4268
https://github.com/gnudatalanguage/gdl/pull/431/commits/c8a42686a7f39ca6cb79e1842918e461ff817bc2
resulted in a  branch which no longer links in windows, ( in the 64-bit case ) and also has problems in one case of travis tests.  Unfortunately there are a lot of modifications that the merge brought in so where to look, how to reproduce the old functional PR (4127137)
and step through the history to find the offensive change.

Answer to this mystery: The expansive PATH included the ruby193 installation, ahead of my efforts
to put C:\projects\gdl\mingw\mingw64 and so the c:\ruby193\bin\zlib1.dll was found as the zlib library.

**Comment by GillesDuvert** [comment]
I know this PR was OK until yesterday. I did test the list and hash functions as OK. 
BUT all of a sudden this PR inherits of tests I made solely on my github (ex: `#06551f0` above). Also, other non commited changes such as the one by @bourgesl appear!
This is very confusing and dangerous. Contrary to what is written above ("Add more commits by pushing to the hashlist branch on maynardGK/gdl), it seems that every commit in every fork is participating to this, excuse the word, mess, and Travis runs again everytime!
Actually I was expecting to see (and review) in this PR only @maynardGK 's commits on his personal branch, nothing else. Is all this due to the recent GH failure?
I suggest to close this PR, ask (again) to @maynardGK to kindly reopen another (pristine) one. Or, rather, two, as it's really important to have a PR with only the list and hash functions per se (the few .cpp + test files) separated  from another PR holding the reste, the complex rewriting of the appveyor scripts.

**Comment by maynardGK** [comment]
@GillesDuvert 
when I checkout master & update (see below) I get a repo that was last merged June 22.
I'm trying to guess what is command to merge up-todate,
```
greg@Homerw7  /f/github/gdlgit
$ git merge https://github.com/gnudatalanguage/gdl
merge: https://github.com/gnudatalanguage/gdl - not something we can merge
```
This is what I used to get the updated master copy:
```
git checkout master
git fetch
git merge --ff-only origin/master
$ git log
commit a33bb5682cb5173cca8a97cb780702435330ec57
Merge: 863f654 c6c67d9
Author: Greg Jung <gvjung@gmail.com>
Date:   Fri Jun 22 17:59:43 2018 -0700

    Merge https://github.com/gnudatalanguage/gdl

commit c6c67d983e8e1861027f221c8540880d180fe513
Merge: 0493b6a 00174cd
Author: GillesDuvert <33936193+GillesDuvert@users.noreply.github.com>
Date:   Fri Jun 22 23:28:04 2018 +0200

    Merge pull request #397 from GillesDuvert/add_random_pool
```
Until you're done with it, I'll keep hands off of this PR.
I've brought in the where, where_inc, includefirst files to my home code, and the "where" bug I
was concerned with over on PR #478 isn't showing now.

**Comment by GillesDuvert** [comment]
Thank you @maynardGK, I probably messed with the master/branch inderection (her, my clone, my computer).
If you do no mind, I'll first update gnudatalanguage/gdl with all your commits that concern LIST and HASH.

**Comment by GillesDuvert** [comment]
For clarity (at least for me) most of the patches are resubmitted in #500 . The rest, appveyor-related scripts, will probably be replaced anyway by #478, and we'll close this PR (now conflicting)

**Pull request closed without merging**
