### PR TITLE
sorting out quick_start_GDL issue

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by slayoo** [comment]
@acoulais would this sort out the quick_start_GDL.sh problem?
It created a quick_start_GDL.sh file in the build directory with (hopefully) correct paths set

**Comment by slayoo** [comment]
@alaingdl would this sort out the quick_start_GDL.sh problem?
It created a quick_start_GDL.sh file in the build directory with (hopefully) correct paths set

**Comment by slayoo** [comment]
@pjb7687 The CI build is failing on Windows with a totally unrelated issue:
>
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/gdl.dir/basic_op.cpp.obj: section .xdata$_ZN5Eigen8internal17mapbase_evaluatorINS_5BlockIKNS_9TransposeINS_3MapINS_6MatrixItLin1ELin1ELi0ELin1ELin1EEELi16ENS_6StrideILi0ELi0EEEEEEELi1ELin1ELb1EEENS5_ItLi1ELin1ELi1ELi1ELin1EEEEC2ERKSC_: string table overflow at offset 10000124
C:\msys64\tmp\cctTnyhL.s: Assembler messages:
C:\msys64\tmp\cctTnyhL.s: Fatal error: CMakeFiles/gdl.dir/basic_op.cpp.obj: file too big


Any hints?
Thanks

**Comment by alaingdl** [comment]
Warm thanks to @slayoo  the situation now is even more convenient for me !

**Comment by slayoo** [comment]
great!

**Comment by pjb7687** [comment]
> @pjb7687 The CI build is failing on Windows with a totally unrelated issue:
> 
> > 
> 
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/gdl.dir/basic_op.cpp.obj: section .xdata$_ZN5Eigen8internal17mapbase_evaluatorINS_5BlockIKNS_9TransposeINS_3MapINS_6MatrixItLin1ELin1ELi0ELin1ELin1EEELi16ENS_6StrideILi0ELi0EEEEEEELi1ELin1ELb1EEENS5_ItLi1ELin1ELi1ELi1ELin1EEEEC2ERKSC_: string table overflow at offset 10000124 C:\msys64\tmp\cctTnyhL.s: Assembler messages: C:\msys64\tmp\cctTnyhL.s: Fatal error: CMakeFiles/gdl.dir/basic_op.cpp.obj: file too big
> 
> Any hints? Thanks

May I ask where can I see this error?

**Comment by slayoo** [comment]
It was in this PR's windows build, but apparently just rerunning fixed the problem

**Pull request merged**
