### PR TITLE
various minors changes

### PR DESCRIPTION
**Pull request by alaingdl**
* initial import of HANNING & GAUSSIAN_FUNCTION #737  (thanks JT)
* correcting GAUSSIAN_FUNCTION() to respect Odd/Even
* adding a test for GAUSSIAN_FUNCTION() 
* no test for HANNING() :( 
* correction of a bug for high dims. in POLYWARP() (thanks Igor)
* adding a test for POLYWARP()
* correct a detail in benchmark_info_os.pro to avoid failing on CentOS 7
* change the order in RECALL_COMMANDS() and also for HELP, /recall
* manage output for multipages for  HELP, /recall (To be generalized to others fields in HELP)
* now size (number of lines) of ternimal where GDL is running can be dynamicaly computed (when using Readline or Editline)
* two new keywords in GDL_STATUS

### CODE REVIEW

**Comment by slayoo** [comment]
image

**Comment by alaingdl** [comment]
Yes, thanks, I saw that. But the include should be done :(
```
grep terminfo gdlhelp.*
gdlhelp.cpp:#include "terminfo.hpp" 
```

unclear :(

may a side effect of Readline/Editline ?!

**Comment by alaingdl** [comment]
Travis, Clang python & numpy

Hi.

Could someone help me for this  PR ?

After I solved my problems in the case of MINI env., the process is stop in the case of Clang : 
numpy is not detected for python. AFAIK it is orthogonal to any contents & changes in my PR.

Thanks ! 
A.

**Comment by slayoo** [comment]
I'll look at it later today

**Comment by slayoo** [comment]
I guess the problem is here:

image

Homebrew started requireing Python 3.8 for numpy, and it gets installed... but GDL still uses Python 3.7

**Comment by slayoo** [comment]
image

**Comment by alaingdl** [comment]
bien vu ! I saw it was related to a Python issue & numpy but I have no idea how to solve it (I am paid today to lose time curing regressions issues between python & packages versions : a crazy full time job just because every week something in a big code is broken in python or packages) 

If you found a way, please don't realize now the PR, I am fixing few minors bugs appearing on nodes without X11 or nodes without "ssh -X"

**Comment by slayoo** [comment]
stopped working 20 days ago:
https://travis-ci.org/github/gnudatalanguage/gdl/builds/672873704

**Comment by alaingdl** [comment]
Travis issue just due to python, not GDL side issue

**Pull request merged**
