### PR TITLE
Container methods: "Equals" and "IsContained"

### PR DESCRIPTION
**Pull request by maynardGK**
container::Equals and :IsContained() didn't make it because of a typo in overload.
 Fix negative indeces access for container::get(position=jj).

test_container expanded to include ::get, ::move, and ::equals methods.

Greg Jung
gvjung@gmail.com

### CODE REVIEW

**Comment by alaingdl** [comment]
Could you check why "appveyor" failed ?

Thanks to have add some test.

**Comment by slayoo** [comment]
Seems it was a network problem when downloading dependencies - just restarted the build

**Comment by slayoo** [comment]
green!

**Comment by slayoo** [comment]
save for the coverage :(
note that test_container.pro is not listed in Makefile.am

**Pull request merged**
