### PR TITLE
adding Tomas Hillberg to co-author list

### PR DESCRIPTION
**Pull request by slayoo**
@hillbergt (CC: @pjb7687), we are drafting a paper about GDL to be submitted to the J. Open Source Software.
This PR adds your name to the co-author list, please confirm.

The current draft of the paper can be generated at: https://whedon.theoj.org/
(repo: https://github.com/gnudatalanguage/gdl.git branch: master)
Any comments to the paper draft text very welcome.
Thanks,
Sylwester

### CODE REVIEW

**Comment by slayoo** [comment]
@hillbergt, ping :) please confirm

**Comment by slayoo** [comment]
@hillbergt, please let us know if you confirm to be included in the author list of GDL short "paper" to be submitted to the Journal of Open Source Software, thanks

**Comment by hillbergt** [comment]
> @hillbergt, please let us know if you confirm to be included in the author list of GDL short "paper" to be submitted to the Journal of Open Source Software, thanks

@slayoo Yes, I confirm being added to the author list.
I replied via e-mail over a week ago, but now I see that the sender was a github-notification mail, so the reply probably got lost in the machinery. Sorry about the delay. :-)

**Comment by slayoo** [comment]
Thanks!

**Pull request merged**
