### PR TITLE
Various minor compiler warning patches

### LINKED ISSUE #347: clang warning (enumeration value 'GDL_UNDEF' not handled in switch)
```
/home/slayoo/devel/gdl/src/basic_fun_jmg.cpp:848:12: warning: enumeration value 'GDL_UNDEF' not handled in switch [-Wswitch]
    switch(type) {
           ^
```

### LINKED ISSUE #348: clang warning (add explicit braces to avoid dangling else)
```
basic_pro.cpp:2196:56: warning: add explicit braces to avoid dangling else [-Wdangling-else]
        if (!quiet) e->Throw("Not found: " + proFile); else return;
```

### LINKED ISSUE #350: clang warning (control may reach end of non-void function)
```
hash.cpp:200:3: warning: control may reach end of non-void function [-Wreturn-type]
  }
  ^
```

### LINKED ISSUE #351: clang warning ('&&' within '||')
```
list.cpp:1720:43: warning: '&&' within '||' [-Wlogical-op-parentheses]
              || ( theType == GDL_DOUBLE) && (resultType == GDL_COMPLEX) )
              ~~ ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
list.cpp:1720:43: note: place parentheses around the '&&' expression to silence this warning
              || ( theType == GDL_DOUBLE) && (resultType == GDL_COMPLEX) )
                                          ^
                 (            
```

### LINKED ISSUE #352: clang warning (dangling else ... expanded from macro 'MAKE_LONGGDL')
```
list.cpp:2670:5: warning: add explicit braces to avoid dangling else [-Wdangling-else]
    MAKE_LONGGDL(index, indexLong)
    ^
list.cpp:95:11: note: expanded from macro 'MAKE_LONGGDL'
          else  { \
          ^
```

plus same in lines 1441, 2895 and 3436

### PR DESCRIPTION
**Pull request by rexso**
Fix #347 
Fix #348 
Fix #350 
Fix #351 
Fix #352

### CODE REVIEW

**Comment by rexso** [comment]
Seems like Travis job 2 failed to download gcc.
Gotta love waiting an hour for false positives :smile:

**Comment by slayoo** [comment]
restarted!

**Comment by GillesDuvert** [comment]
@rexso thanks for the fixes, @slayoo we could live with such petty compiler warnings for some time and fix them  just before releases... At the same time if one could get rid of the  clang warning about data::convert2 thingie, it would be granted a :medal_military:  :smile:

**Comment by slayoo** [comment]
Of course, these are just warnings, but in my opinion it would be great to actually report them during CI so that new ones are not introduced. Hence, I thought of campaigning for reducing them all now and introducing -Werror-like flags for CI (only for CI, i.e. not in CMakeLists.txt). This will only help with code quality, and will reduce release efforts.

**Comment by slayoo** [comment]
and big thanks to @rexso !

**Comment by rexso** [comment]
@GillesDuvert the templated friend thing? I started looking at it, and realised it would take more than 2 minutes to fix, so i did not bother last night :grin: Frankly it is a bit cumbersome to do any GDL hacking for me ATM since I work on a diverted branch due to #338. If anyone could review/evaluate that one so I could stay in sync with master, it would be highly appreciated.

**Comment by GillesDuvert** [comment]
@rexso As I am by no means a C++ expert and lost some time trying to understand and cure this warning, its a relief to know that it is not trivial :smiling_imp: 
And sorry for the disordered fashion in which the PR are reviewed and merged.

**Comment by slayoo** [comment]
@GillesDuvert apologies if I merged this one while you were reviewing it!

**Comment by rexso** [comment]
I love this disordered fashion that keeps you on the edge :grin: No apologies needed.
It sure beats long bureaucratic review processes that halts all the time because of the ordered nature.
Being able to tackle problems based on the complexity and time available is great. While I normally like tackling problems as they arise, it is sometimes good to have the opportunity to relax while fixing trivial compiler warning issues.

**Pull request merged**
