### PR TITLE
Various speedups and huge revamping

### PR DESCRIPTION
**Pull request by GillesDuvert**
huge revamping of basic GDL sources: by avoiding many #includes in datatypes.cpp, compilation time is reduced and it is easier to maintain and improve (for speed) the basic operators and functions.
- speedup of various types, especially on memory allocation, but also correction of misplaced parallell constructs (making gdl probably slower with them than without!) and, as far as possible, removal of if-else constructs and branching in "parallell for" sections, since having them is tantamount of no acceration at all.
Various bugs and style corrections.
Needs complete recomplilation from scratch of course.

### CODE REVIEW

**Comment by GillesDuvert** [comment]
OK this is going to be merged soon, it works perfectly.
The only remaining puzzle is the alleged absence of destructor of NullGDL seen by icc?
@maynardGK , it solves the Python warnings and other compiler messages.
@maynardGK the windows version has openmp and eigen3, but test_finite takes 40 seconds? What about test_matrix_multiply? (compare with gcc+Release on travis)
@slayoo , clang was always painful, but now it fails completely to start compiling --- homebrew problem I believ.

**Comment by maynardGK** [comment]
I hadn't noticed your work on this PR earlier today.  
  It is still a puzzle, how #650 ran on appveyor with only 4 errors in the x86_64 case.  
test_finite at 40 seconds is a good score, the 64-bit builds scored over 60 seconds.
The i686 case is less stable even when run from my home system: 
test_finite results:
````
$ gdl32-998
% WARNING: your version of the GraphicsMagick library will truncate images to 8 b

  GDL - GNU Data Language, Version 0.9.9 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
GDL> test_finite
% Compiled module: TEST_FINITE.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FINITE_BASIC:   NO errors encountered during TEST_FINITE_BASIC tests
% Compiled module: ERRORS_CUMUL.
% TEST_FINITE_BASIC:   NO errors encountered during TEST_FINITE_BASIC tests
% TEST_FINITE_BASIC:   NO errors encountered during TEST_FINITE_BASIC tests
% TEST_FINITE_BASIC:   NO errors encountered during TEST_FINITE_BASIC tests
% TEST_FINITE_VALUES:   NO errors encountered during TEST_FINITE_VALUES tests
Running this test with various numbers of points ...
Please wait ...
% TEST_FINITE_TIMETEST:   NO errors encountered during TEST_FINITE_TIMETEST tests
% TEST_FINITE_TIMETEST:   NO errors encountered during TEST_FINITE_TIMETEST tests
terminate called recursively
terminate called after throwing an instance of 'std::bad_alloc'

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
 Magick: abort due to signal 22 (SIGABRT) "Abort"...

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
 what():  std::bad_alloc

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
````
later I will show tests from this code base (which I just noticed is recent).

**Comment by GillesDuvert** [comment]
unfortunately this branch has evolved from gdl master BEFORE the revert #650 was performed.
So it's unclear for me if by merging it I will put back #626 .
Additionnally it inherits from #630 which was not intentional, but as #630 is going to be merged, this is not really a problem.
I better close this and open another, more pristine, PR without those.

**Comment by maynardGK** [comment]
I could not verify any new bug (aka the fits problem) introduced by  #626 and the only critical change was the use of getCommon() so to save you trouble you should just stay with this PR, (IMO).

**Comment by slayoo** [comment]
> @slayoo , clang was always painful, but now it fails completely to start compiling --- homebrew problem I believ.

seems genuinely unrelated to clang as it is ```brew install python@2``` that fails... with a message " already installed" - will try in a moment wha happes without this line in .travis.yml

**Comment by GillesDuvert** [comment]
hopefully replaced by #653

**Comment by GillesDuvert** [comment]
OK replaced by #653 , PR removed

**Pull request closed without merging**
