### PR TITLE
GDL_ACCEPT_CMAKE_3_0 CMake flag (was: Revert "WIP: relaxing CMake version requirement (buggy)")

### PR DESCRIPTION
**Pull request by alaingdl**
Reverts gnudatalanguage/gdl#409

### CODE REVIEW

**Comment by alaingdl** [comment]
difficult for me : I want to compile GIT version on a login node  where I am not root
without changing my script ...
with cmake 3.0.2 and gcc 4.9, which is perfectly OK for compilation

**Comment by slayoo** [comment]
Alain, I've just committed a new idea for how to solve it to this PR branch - please have a look if that would solve the issue?

**Comment by slayoo** [comment]
@alaingdl @acoulais would this work for you? Thanks

**Comment by alaingdl** [comment]
Not working for me, assuming "VERSION_GREATER_EQUAL" appeares later ?!

I have to compile GDL on another server where I am not admin with cmake 3.0.2
(And that broke too my script to frequently update the compilation :(

CMake Error at CMakeLists.txt:19 (if):
  if given arguments:

    "3.0.2" "VERSION_GREATER_EQUAL" "3.2"

  Unknown arguments specified

**Comment by slayoo** [comment]
@alaingdl Please try with the above change (VERSION_GREATER_EQUAL -> VERSION_GREATER OR VERSION_EQUAL). Thanks

**Comment by alaingdl** [comment]
After some changes in header of the CMakeList.txt
I made another test last days for cmake 3.0.2 , OK with Clang & GCC
but problem with Intel 

--> I hope to converge soon !


```
cmake_minimum_required(VERSION 3.0.0 FATAL_ERROR)
project(GDL)

# requirement for CMAKE_CXX_STANDARD (3.2 for Apple, 3.1 for non-Apple:
# https://public.kitware.com/Bug/bug_relationship_graph.php?bug_id=15355)
if (${CMAKE_VERSION} VERSION_LESS "3.2")
  if (UNIX)
    message("${CMAKE_CXX_COMPILER_ID}")
    # https://stackoverflow.com/questions/10046114/in-cmake-how-can-i-test-if-th
e-compiler-is-clang
    if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU|Clang")
      include(CheckCXXCompilerFlag)
      CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
      if(COMPILER_SUPPORTS_CXX11)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
      else()
	message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
      endif()
    else()
      message(FATAL_ERROR "We are not ready for this compiler !"
	"please consider upgrade CMake (> 3.2) to avoid this problem\n")
    endif()
  else()
    message(STATUS "no sure your OS + C++ compiler are OK, best way to ensure compilation"
      "is to move to Cmake >= 3.2\n\n")
  endif()
else()
  set(CMAKE_CXX_STANDARD 11)
endif()

cmake_policy(SET CMP0026 OLD) # LOCATION property

# X.X.X git becomes release X.X.X+1
set(VERSION "0.9.8 git")
enable_testing()

```

**Comment by slayoo** [comment]
Alain, this will prevent user from setting a custom --std flag, and more importantly (IIRC) will not work with Debug/Release modes. Wouldn't it be simpler just to echo a message asking for manual setting of CMAKE_CXX_FLAG?

**Comment by slayoo** [comment]
closing and reopening to trigger build against current master

**Comment by slayoo** [comment]
This is how the problem appears to a user IIUC:
https://github.com/gnudatalanguage/gdl/issues/566

**Comment by GillesDuvert** [comment]
closed as too difficult to see the point after so many changes. PLS make a new PR if needed.

**Comment by slayoo** [comment]
Just to clarify/for the record:

As of now, the`CmakeLists.txt` includes the logic below:
```
if (${CMAKE_VERSION} VERSION_LESS "3.2")
  string(FIND "${CMAKE_CXX_FLAGS}" "-std=c++11" tmp)
  if(tmp LESS 0)
    message(FATAL_ERROR "please upgrade CMake to a version 3.2 or higher OR rerun cmake with -DCMAKE_CXX_FLAGS=\"-std=c++11\"")
  endif()
else()
  set(CMAKE_CXX_STANDARD 11)
endif()
...
set(CMAKE_CXX_STANDARD 11)
```

It seems fishy for three reasons:
- the second `set(CMAKE_CXX_STANDARD 11)` likely makes the whole earlier block useless?
- `-std=c++11` will not work, e.g., on Windows or with Intel compiler
- (here I'm not so sure) what happens if a user sets a C++11 flag within `CMAKE_CXX_FLAGS_DEBUG` and not using `CMAKE_CXX_FLAGS`?

**Comment by GillesDuvert** [comment]
there are things in [the cmake doc](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#manual:cmake-compile-features(7)) like:
`target_compile_features(mylib PUBLIC cxx_std_11)`

**Pull request closed without merging**
