### PR TITLE
legacy_list: update for LIST,HASH: N_elements(), GDL_CONTAINER

### PR DESCRIPTION
**Pull request by maynardGK**
This branch begins the road to the modern versions of list/hash by preserving the old behavior (and actual code implementation) of the pre-existing features, while making the required peripheral modifications to other GDL internals.
The legacy code includes a small bug such that changes to list elements are mostly not possible:
  "alist[k] = findgen(8)" should replace the k'th element of list alist with the right-side expression. Fixing this simple problem in the legacy code would be a) pointless and b) change the apparent baseline code from what is has been for years.

Some of the changes exist in github development separately, awaiting merge/approvals, and are copied to here for use; since they are derived from the same code there should be no conflict issues when merged. In particular, the surgery mentioned in issue #236 - aka SF.net bug 696 (https://sourceforge.net/p/gnudatalanguage/bugs/696/) is made, and it has worked well.  The one adverse side effect required "foreach" coding to notice hashes and lists, and this is also present.

LIST methods move() and swap(), which didn't exist at all, have been copied into the file alongside the legacy code.  Another addition is the "GET" method (list__get) which is not really a list method but intended for the container object; before the GDL_CONTAINER declarations I used those of list to develop this method.  list__get() compiles and exists harmlessly as long as it is not invoked.

Subsequent improvements to list.cpp that are already coded:
   toarray() method is implemented with all features
   Multi-dimensional direct access to list or hash elements (see documention, and some examples in TEST_LIST).
   GDL_CONTAINER is defined, which may lead to IDL_CONTAINER - see in src/pro directory:
;-----------------------------------------
PRO IDL_CONTAINER__Define, class

   Compile_Opt hidden
   class = { IDL_CONTAINER, $
              INHERITS GDL_CONTAINER $
           }

END

Greg Jung (aka maynardGK)
gvjung@gmail.com

### CODE REVIEW

**Comment by maynardGK** [comment]
Most failing tests fail on master, also.  
test_list.pro checks for a substring in !gdl.release and will limit the extent of testing: IDL or a custom build (without the "svn" in the version string) will go on to test indirect addressing etc.
This is legacy list, not the fully modern version in order to compare performance and better view changes.  One known bug is that left-bracket element change does not work: ie. "alist[k] = findgen(3,4)"  A bug fix for this is pointless, because it is not a one-liner and would only confuse future "diff" perusals.  The  new LIST does not have this issue.
  Next commit to this branch will bring in the TOARRAY method, involving only a few other files to support.

  Results (opensuse 42.1) from make check on building the first commit:
96% tests passed, 9 tests failed out of 203
Total Test time (real) = 106.92 sec

The following tests FAILED:
         25 - test_bug_3086851.pro (Failed) - irrelevant.
 I planned to modify strsplit and hadn't noticed it already fixed in SVN.
         93 - test_fft_leak.pro (Failed)
         96 - test_file_delete.pro (Failed)
        103 - test_fix.pro (Failed)
        137 - test_n_tags.pro (Failed)
        145 - test_parse_url.pro (Failed)
        167 - test_resolve_routine.pro (Failed)
        169 - test_rounding.pro (Failed)
        191 - test_total.pro (Failed)

**Comment by slayoo** [comment]
Closing and reopening to trigger appveyor build

**Comment by maynardGK** [comment]
codecov/patch didn't pass: re-try. 
codecov/patch — 28.15% of diff hit (target 41.75%)
Codacy/PR Quality Review — Up to standards. A positive pull request.
codecov/project — 41.76% (+<.01%) compared to df0be67
continuous-integration/appveyor/pr — AppVeyor build succeeded
continuous-integration/travis-ci/pr — The Travis CI build passed

**Comment by maynardGK** [comment]
I will close this now that I have merged the inter-related branches into branch "combo" which built
and produced the following result on Linux "make check:"


7% tests passed, 7 tests failed out of 211

Total Test time (real) = 140.14 sec

The following tests FAILED:
         94 - test_fft_leak.pro (Failed)
         97 - test_file_delete.pro (Failed)
        142 - test_n_tags.pro (Failed)
        152 - test_parse_url.pro (Failed)
        175 - test_resolve_routine.pro (Failed)
        177 - test_rounding.pro (Failed)
        199 - test_total.pro (Failed)

 combo = legacy_list + basic_fun + basic_pro + gdlhelp_fin + legacy_hash
    
      This brings the list/hash code to a level just prior to the final enhancement that is ready
    to go, which allows in-place extraction and insertions from lists and hashes.
    file_etc branch has not yet been merged, it is not dependent on this.
    
      Changes in GDLParser, GDLInterpreter, etc. should all have their corresponding code in gdlc.g
    and gdlc.i.g.
    
    Greg Jung 29 May 2018
    gvjung@gmail.com

**Pull request closed without merging**
