### PR TITLE
benchmark for windows

### PR DESCRIPTION
**Pull request by eloirozier**
Very small corrections making benchmarks possible to be run and saved on MSWindows

### CODE REVIEW

**Comment by GillesDuvert** [comment]
@eloirozier I do not understand: mswindows does have this commands, so the procedure will fail on windows. ???

**Comment by eloirozier** [comment]
Sorry i should have detailed more

Well the command
"date"
exists on mswindows but it outputs more than one string which makes everything crash
So i looked for an other way to get the date, and it turned out that the simpliest was to use "powershell -command..."
And also on mswin the ':' char cannot be put into a file's name so the code had to be corrected anyway.
I hope this explanation is clear enough!

**Comment by GillesDuvert** [comment]
I was referring to 
`SPAWN, 'sysctl -n hw.cpufrequency', resu_Hz`
which is now valid under windows following your changes in `benchmark_generate_cpuinfo.pro ` and `benchmark_info_cpu.pro`

**Comment by eloirozier** [comment]
Now I see where I made a mistake. I didnt know that 'darwin' corresponded to MacOSx so I foolishky replaced it with 'windows', thinking of it as a weird mistake...
I should have completed the IF statement with something like
OR osname EQ 'windows'

**Pull request closed without merging**
