### PR TITLE
Implement DELVAR and update basic_fun (2 commits merged).

### PR DESCRIPTION
**Pull request by maynardGK**
The branch delvar-rnew was automatically tagged into the branch basic_fun which covers the majority
of work to be done for basic_fun.  I included an old routine that doesn't work, routine_filepath(),
because it looks like it should have worked at some point.  
   The persistent global vector holding command line args becomes a string vector which
makes it possible to change its contents while running GDL.  This is done with keywords that
one would need to rebuild to be able to use - making it compatible with stock IDL.  I use this to begin
debug tracing once GDL is operational:
```
traceon.pro:
p=command_line_args(set="trace")
pro traceoff
compile_opt hidden
p=command_line_args() & if p[0] eq '' then return
i=where(p ne 'trace',nc)
if(nc eq 0) then r=command_line_args(/reset) else r = command_line_args(/reset,set=p[i])
return
end
```

### CODE REVIEW

**Comment by maynardGK** [comment]
test_delvarrnew.pro:
 DELVAR can only be called from $MAIN; this is a documented IDL rule; an exception is thrown when it is called from a procedure or function.
The test_delvarrnew.pro code will thus spawn a new GDL process given the filename "delvarrnew.pro"
to execute (as from the command line: @). Then .RNEW is run for the (one-line) test program testproc
which is a compiled $MAIN program.  This was developed and tested in the Linux environment.

**Comment by slayoo** [comment]
Closing and reopening to trigger codecov and appveyor runs

**Comment by maynardGK** [comment]
The Travis CI build indicates a bogus error, it is missing characters or something!!

[ 37%] Building CXX object src/CMakeFiles/gdl.dir/extrat.cpp.o
/home/travis/build/gnudatalanguage/gdl/src/envt.cpp: In member function â€˜bool EnvBaseT::Remove(int*)â€™:
/home/travis/build/gnudatalanguage/gdl/src/envt.cpp:1324:44: error: expected â€˜;â€™ before â€˜)â€™ token
     ix,static_cast <const void *>(env[ix]) );
                                            ^
make[2]: *** [src/CMakeFiles/gdl.dir/envt.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/gdl.dir/all] Error 2
make: *** [all] Error 2
; Close and reopening

**Comment by slayoo** [comment]
It seems not bogus, see: https://github.com/gnudatalanguage/gdl/pull/161/files#diff-17c9a9f9c3d49d327eca5be96161e193R1322
(the two lines below should be commented out as well)

**Comment by maynardGK** [comment]
I was working on the file in the wrong branch.

**Comment by maynardGK** [comment]
I run these tests and do not get a failure:
`greg@linux-gc09:/f/github/gdlgit/testsuite> ../src/gdl

  GDL - GNU Data Language, Version 0.9.8 svn

- For basic information type HELP,/INFO
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at:
  http://sourceforge.net/projects/gnudatalanguage/

GDL> $ git branch | grep basic_fun
* basic_fun
GDL> print,getenv('GDL_PATH')
+/f/github/gdlgit
GDL> pwd
% Procedure not found: PWD
% Execution halted at: $MAIN$          
GDL> cd,cur=pdw & print,pwd
% PRINT: Variable is undefined: PWD
% Execution halted at: $MAIN$          
GDL> cd,cur=pdw & print,pdw
/f/github/gdlgit/testsuite
GDL> $cat fails.ls
The following tests FAILED:
         83 - test_delvarrnew.pro (Failed)
        133 - test_obj_hasmethod.pro (Failed)
        134 - test_obj_valid.pro (Failed)
        144 - test_ptr_valid.pro (Failed)

GDL> test_delvarrnew    
% Compiled module: TEST_DELVARRNEW.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
%  DELVAR-RNEW: ==========================
%  DELVAR-RNEW: =                        =
%  DELVAR-RNEW: =   works! (from $main)  =
%  DELVAR-RNEW: =                        =
%  DELVAR-RNEW: ==========================
GDL> test_obj_hasmethod
% Compiled module: TEST_OBJ_HASMETHOD.
SUCCESS
GDL> test_obj_valid
% Compiled module: TEST_OBJ_VALID.
SUCCESS
GDL> test_ptr_valid
% Compiled module: TEST_PTR_VALID.
%  TEST_PTR_VALID: ========================================================
%  TEST_PTR_VALID: =                                                      =
%  TEST_PTR_VALID: =  NO errors encountered during  TEST_PTR_VALID tests  =
%  TEST_PTR_VALID: =                                                      =
%  TEST_PTR_VALID: ========================================================
Success!`

**Comment by maynardGK** [comment]
I may be having a lucky day ... try this again.

**Comment by maynardGK** [comment]
I see now that test_delvarrnew does not work in the "make check" process because the
supporting files are not available under the build directory.  I wrote the test to work under gdl/testsuite and that works fine interactively because it references ../src/gdl to invoke gdl, and the support scripts are placed in testsuite.  I suppose I have to generate the dependent scripts from the test routine.

New status of "make check" after build on my Linux:
`
96% tests passed, 9 tests failed out of 209

Total Test time (real) = 107.31 sec

The following tests FAILED:
         84 - test_delvarrnew.pro (Failed)
         94 - test_fft_leak.pro (Failed)
         97 - test_file_delete.pro (Failed)
        140 - test_n_tags.pro (Failed)
        146 - test_obj_isa.pro (Failed)
        150 - test_parse_url.pro (Failed)
        173 - test_resolve_routine.pro (Failed)
        175 - test_rounding.pro (Failed)
        197 - test_total.pro (Failed)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
`
  Apparently test_obj_hasmethod might pass, as can test_obj_valid and test_ptr_valid

**Comment by maynardGK** [comment]
Now I only get the "test_obj" failures, the only change of test_ptr_valid that could have made
the difference was, to unpack p=(ptr_valid())[0] into two statements.

99% tests passed, 2 tests failed out of 187
Total Test time (real) = 183.97 sec
The following tests FAILED:
	135 - test_obj_hasmethod.pro (Failed)
	136 - test_obj_valid.pro (Failed)
Errors while running CTest

Next, I'll put that back and surround the suspected statement with print-outs:
; p = ptr_valid()
; p = p[0] ; transform to scalar
print,' test_ptr_valid 0' ; see if this is what wbrings the test down.
	p = (ptr_valid())[0] 
print,' test_ptr_valid 1:', err

**Comment by maynardGK** [comment]
At this point the travis tests are passing; they were previously failing due to an obscure assertion trap
found in gdlarray.hpp: "T& operator[]" on line 210.  This only happened from obj_valid() reliably (ptr_valid() is essentially the same code and should have also invoked the condition in test_ptr_valid).
So this should probably be considered an interim state until the cause can be discovered.  Meanwhile
when/if the condition happens a message will appear to alert the user.

Message left in the code:
//
// 2018 May 28 G. Jung: Note there is an inordinate separation of 
// scalar and non-scalar treament.  This is probably unnecessary 
// but it was my last line of attempt to quash error, due to an assert
// in gdlarray.cpp (line 210) which obj_valid() triggered in Travis tests.
// (Not an error that would show up under any other circumstance).
// Note that ptr_valid, which has an equivalent code, does not provoke this
// assertion.  In order that we have these functions, then, I have
// converted the assertion of GDLarray into a message to std::cout.
//

Update 29 May:
  It dawns on me why obj_valid was failing: the N_Elements() function of GDL still follows the old hack,
which returns the count of the LIST or HASH object instead of the number of objects themselves.

After testing this hypothesis I will rewind the latest back-and-forth, and leave tes_obj_valid
castrated with object instances of lists of length 1, so that the test will pass. The new message:
//
// 2018 May 29 G. Jung: Note there is an inordinate separation of  scalar and non-scalar treament.
//  This was my last line of attempt to quash an error, due to an assert
// in gdlarray.cpp (line 210) which obj_valid() triggered in Travis tests.
// I am now 99.5% convinced that this error is due to the incorrect hack in GDL
// that, for "SizeT nEl = p->N_Elements();" returns instead the count() of the list
// so in fact, a list is not a true object. 
//  Merge "legacy_list" branch to remedy this.
//

**Comment by maynardGK** [comment]
I tried to rewind but the changes to gdlarray stuck; as it turns out the assertion can be triggered
just by manipulating the object in an expression:
GDL> llist = list(3,4,5)
GDL> help,[llist]
GDLArray line 210 ix=1, sz = 1
GDLArray line 210 ix=2, sz = 1
<Expression>    OBJREF    = Array[1]

**Comment by maynardGK** [comment]
will close this now that I have merged the inter-related branches into branch "combo" which built
and produced the following result on Linux "make check:"


7% tests passed, 7 tests failed out of 211

Total Test time (real) = 140.14 sec

The following tests FAILED:
         94 - test_fft_leak.pro (Failed)
         97 - test_file_delete.pro (Failed)
        142 - test_n_tags.pro (Failed)
        152 - test_parse_url.pro (Failed)
        175 - test_resolve_routine.pro (Failed)
        177 - test_rounding.pro (Failed)
        199 - test_total.pro (Failed)

 combo = legacy_list + basic_fun + basic_pro + gdlhelp_fin + legacy_hash
    
      This brings the list/hash code to a level just prior to the final enhancement that is ready
    to go, which allows in-place extraction and insertions from lists and hashes.
    file_etc branch has not yet been merged, it is not dependent on this.
    
      Changes in GDLParser, GDLInterpreter, etc. should all have their corresponding code in gdlc.g
    and gdlc.i.g.
    
    Greg Jung 29 May 2018
    gvjung@gmail.com

**Pull request closed without merging**
