### PR TITLE
adding Thibault Huillet to the co-author list

### PR DESCRIPTION
**Pull request by slayoo**
@bouloukaouze (CC: @pjb7687), we are drafting a paper about GDL to be submitted to the J. Open Source Software.
This PR adds your name to the co-author list, please confirm.

The current draft of the paper can be generated at: https://whedon.theoj.org/
(repo: https://github.com/gnudatalanguage/gdl.git branch: master)
Any comments to the paper draft text very welcome.
Thanks,
Sylwester

### CODE REVIEW

**Comment by slayoo** [comment]
@bouloukaouze, ping :) please confirm

**Comment by slayoo** [comment]
@bouloukaouze, please let us know if you confirm to be included in the author list of GDL short "paper" to be submitted to the Journal of Open Source Software, thanks

**Comment by algorab-dream** [comment]
> @bouloukaouze, please let us know if you confirm to be included in the author list of GDL short "paper" to be submitted to the Journal of Open Source Software, thanks

Sorry for the delay... As far as I contributed (a very little bit, but I did^^), it would be a pleasure for me to be named in this paper :)

**Comment by slayoo** [comment]
Thanks!

**Pull request merged**
