### PR TITLE
Several bugfixes thanks to hessi instrument

### PR DESCRIPTION
**Pull request by GillesDuvert**
In the course of making the HESSI (and HSI) suite of satellite data reduction pipeline work (or at least trying to make it work), this is the first batch of needed changes.
see #425 for the background.

### CODE REVIEW

**Comment by slayoo** [comment]
no idea why it's not showing above, but Travis is working on it:
https://travis-ci.org/gnudatalanguage/gdl/builds/649162843

**Comment by GillesDuvert** [comment]
yes, with ~15 mins compilation, we also gained a lot of time on this side too.
Excellent, I'll commit fast.

**Comment by GillesDuvert** [comment]
ahem, #173 fixes have disappeared in the meantime. Git is not so clever after all. I'll check.

**Comment by slayoo** [comment]
> yes, with ~15 mins compilation, we also gained a lot of time on this side too.
> Excellent, I'll commit fast.

This is not 100% excellent as the reason is that the Intel compiler builds do not function anymore

**Comment by slayoo** [comment]
@GillesDuvert, I'm waiting with "-rc2" for this to get in into master, right?

**Comment by GillesDuvert** [comment]
@slayoo yes indeed, please merge at your convenience.

**Comment by GillesDuvert** [comment]
This is not the end (quite far from HSI support) but it will be the subject of other PRs.

**Pull request merged**
