### PR TITLE
Array_Equal(p0,p1,/not) implementation Array_Equal(p0,p1,/not) implementation (includes WShow, #ifdef _WIN32 for open_lun, obj_destroy, CMake CMP0012, FindXdr.cmake and PathSeparator unrelated changes)

### PR DESCRIPTION
**Pull request by maynardGK**

### CODE REVIEW

**Comment by maynardGK** [comment]
Complete implementation of Array Equal

ArrayNeverEqual is implemented as a keyword option (NOT_EQUAL) to ArrayEqual.
QUIET keyword avoids an exception for any of the possible rejections.
basegdl - declaration
basic_fun - coding to merge equal/neverequal
datatypes - arrayneverequal method.
libinit.cpp - New keywords for ARRAY_EQUAL

 tested for a simple case.
(Stage1)
Greg Jung (aka maynardGK)
gvjung@gmail.com
-------------
That is the message I had attached to the commit when I created it locally. A local/irrelevant FindXdr.cmake may also have tracked into the PR - what I need to build git but unintentional.
----
```
greg@Homerw7 MSYS /f/github/gdlgit
$ git commit -a -F commit_arrayequal.ls
[stage1 8f455c5] Complete implementation of Array Equal
 9 files changed, 136 insertions(+), 104 deletions(-)
 rewrite CMakeModules/FindXdr.cmake (98%)

greg@Homerw7 MSYS /f/github/gdlgit
$ git log
commit 8f455c5ba0c49b53ccc880963f36447a1428b4aa
Author: Greg Jung <gvjung@gmail.com>
Date:   Sun Apr 8 14:01:01 2018 -0700

    Complete implementation of Array Equal

    ArrayNeverEqual is implemented as a keyword option (NOT_EQUAL) to ArrayEqual.
    QUIET keyword avoids an exception for any of the possible rejections.
    basegdl - declaration
    basic_fun - coding to merge equal/neverequal
    datatypes - arrayneverequal method.
    libinit.cpp - New keywords for ARRAY_EQUAL

     tested for a simple case.
    (Stage1)
    Greg Jung (aka maynardGK)
    gvjung@gmail.com

$ git push --set-upstream origin stage1
Username for 'https://github.com':
Password for 'https://maynardGK@github.com':
Counting objects: 13, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 2.83 KiB | 0 bytes/s, done.
Total 13 (delta 11), reused 0 (delta 0)
remote: Resolving deltas: 100% (11/11), completed with 11 local objects.
To https://github.com/maynardGK/gdl.git
 * [new branch]      stage1 -> stage1
Branch stage1 set up to track remote branch stage1 from origin.

```

**Comment by slayoo** [comment]
Thank you!

The other files were commited as well because of the -a option to git commit:
```
git commit -a ...
```
commits all modified/added files on a given branch.

HTH

**Comment by slayoo** [comment]
Besides excluding the unrelated changes (I can help with it by submitting a pull request into your branch, if needed), it would be great to have a test routine.

**Comment by maynardGK** [comment]
Ok I'm learning what's going on, slowly, I was robotically giving "commit -a" command; now I am using a fixit script to mend the absence of "-lxdr" in the linkage list until a working FindXdr.cmake appears.

**Comment by slayoo** [comment]
Please note that reopening the PR does not modify the set of changes as it is still bound to the same branch.

**Comment by maynardGK** [comment]
Yeah I pressed button in error, didn't want it closed.

**Comment by maynardGK** [comment]
Now I'm going to close for real.  I have been creating branches when checked out to a branch,
and so the prior commits are merged with this to look like a compound pull request, wheras it was intended to just apply to ArrayEqual.
 The three commits merged into this are handled in prior PRs. So I will close this to make a new branch ArrayEqual from master, and when the new PR is made I will clean up as  much as possible without making a bigger mess.

**Comment by maynardGK** [comment]
Ok now I'm -really- going to close :)

**Pull request closed without merging**
