### PR TITLE
libtiff support

### PR DESCRIPTION
**Pull request by rexso**
Rebased and cleaned-up version of #288.

### CODE REVIEW

**Comment by rexso** [comment]
Added tests for **QUERY_TIFF**.

Since TIFF supports quite the variety of image configurations, various sample images should be generated in order to test the most ***commonly used*** configurations when writing tests for **READ_TIFF**:

- [x] Tile-based image
- [x] Strip-based image
- [x] 8-bits greyscale image
- [ ] 16-bits Colour indexed image
- [x] 24-bits RGB image
- [ ] 32-bits RGBA image
- [ ] 32-bits FLOAT image

In addition, all the various arguments and keywords should be tested:
- [ ] R, G, B
- [ ] CHANNELS
- [ ] DOT_RANGE (not yet implemented)
- [x] GEOTIFF (shares implementation with **QUERY_TIFF**)
- [ ] ICC_PROFILE (not yet implemented)
- [ ] IMAGE_INDEX
- [ ] INTERLEAVE
- [x] ORIENTATION (shares implementation with **QUERY_TIFF**)
- [ ] PHOTOSHOP (not yet implemented)
- [x] PLANARCONFIG (shares implementation with **QUERY_TIFF**)-
- [x] SUB_RECT

**Comment by rexso** [comment]
Seems like the tests fail specifically on MacOS:

```
99% tests passed, 1 tests failed out of 192
Total Test time (real) = 154.51 sec
The following tests FAILED:
	181 - test_tiff.pro (Failed)
```

I fail to see any indication why though. Any way to get the output from the test, so I can try fixing this?

**Comment by rexso** [comment]
Nevermind, I found it.

```
% Compiled module: TEST_TIFF.
% Compiled module: QUERY_TIFF.
tiff/e_tile.tif: could not open file for reading
% Compiled module: ERRORS_ADD.
% TEST_QUERY_TIFF: Error on operation : QUERY_TIFF failed to query tiff/e_tile.tif
tiff/bogota.tif: could not open file for reading
% TEST_QUERY_TIFF: Error on operation : QUERY_TIFF failed to query tiff/bogota.tif
```

I do not have any experience with development for MacOS, but I will see if I can figure this out. Seems like the sample images used for testing are not found using the relative path, so I suspect there is a problem related to the image paths and working directory.

This is the reported command and directory:

```
Command: "/Users/travis/build/gnudatalanguage/gdl/build/testsuite/launchtest" "test_tiff.pro"
Directory: /Users/travis/build/gnudatalanguage/gdl/build/testsuite
```

Any hints appreciated.

**Comment by rexso** [comment]
Maybe I am suppored to use **FILE_SEARCH_FOR_TESTSUITE** when referencing to specific files used in the test?

**Comment by GillesDuvert** [comment]
Hi @rexso , this works like a charm on my machine. No clue as to why it failed on appveyor. Test can be skipped on this platform, anyway.

**Comment by rexso** [comment]
@GillesDuvert that is weird indeed. The appveyor check passed prior to adding the tests, but now it times out. I wonder if it is related to both TIFF and GeoTIFF being stated as ON, while the libraries clearly are not found. TIFF related tests should be skipped when building without TIFF support.

```
TIFF                ON TIFF_LIBRARY-NOTFOUND
GeoTIFF             ON 
```

**Comment by slayoo** [comment]
I'm aiming at adding test log output to Appveyor today (and Debug/Release builds)

**Comment by rexso** [comment]
I think the latest commits will solve the problem.

Now **TIFF=OFF** and **GEOTIFF=OFF** must be explicitly defined unless the libraries are found, otherwise cmake will complain properly and stop building. Of course this is how I should have done it in the first place, but my cmake expertise is limited, so it has been some trial and error. Now I have gone through the documentation, so I finally have a better understanding how it works.

Appveyor is now also configured to download the TIFF library, and **-DGEOTIFF=OFF** has been added.

I suppose Travis should also be reconfigured in some builds to not include TIFF/GeoTIFF support, but I have not looked into this yet because Travis seems to succeed on both Linux and MacOS.

**Comment by slayoo** [comment]
Appveyor:
```
C:\projects\gdl\src\tiff.hxx: In member function 'void lib::TIFF::Handler::GetRequiredField(ttag_t, T&) const':
C:\projects\gdl\src\tiff.hxx:177:23: error: 'TIFFField' does not name a type
                 const TIFFField* field;
                       ^~~~~~~~~
C:\projects\gdl\src\tiff.hxx:179:25: error: 'field' was not declared in this scope
                     if((field = TIFFFieldWithTag(tiff_, tag)))
                         ^~~~~
C:\projects\gdl\src\tiff.hxx:180:46: error: there are no arguments to 'TIFFFieldName' that depend on a template parameter, so a declaration of 'TIFFFieldName' must be available [-fpermissive]
                     throw TIFFFieldName(field); else throw tag;
                                              ^
C:\projects\gdl\src\tiff.hxx:180:46: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
src\CMakeFiles\gdl.dir\build.make:1154: recipe for target 'src/CMakeFiles/gdl.dir/libinit_cl.cpp.obj' failed
mingw32-make[2]: *** [src/CMakeFiles/gdl.dir/libinit_cl.cpp.obj] Error 1
mingw32-make[2]: *** Waiting for unfinished jobs....
```

**Comment by rexso** [comment]
Latest commit disabled GeoTIFF in the linux build until the appropriate libgeotiff package has been added to Travis. TIFF is still found though, so building with TIFF support is left untouched.

Interestingly enough, both TIFF and GeoTIFF is found for the MacOS build.

For now I disabled TIFF and GeoTIFF support in appveyor while investigating the TIFFField support. This is probably due to an outdated version of libtiff, so I will add the appropriate version checks to the code.

**Comment by slayoo** [comment]
Just for the record: in the Travis setup the idea was to have two sets of builds: MINI and FULL - one with as many dependencies or optional features turned on (and installed if needed), the second one with everything OFF (even if installed by default). I'm aiming at introducing analogous setup for Appveyor soon.

**Comment by rexso** [comment]
@slayoo I assumed as much, so I disabled TIFF entirely for MINI builds in 4b02a95, regardless of platform on Travis. Adding this to appveyor should be trivial when your new setup is ready.

**Comment by rexso** [comment]
I just found out that accessor functions for [TIFFField](https://gitlab.com/libtiff/libtiff/commit/84595b4fd70575d233bed0ff5996331e0a2283df) were added to libtiff in version [4.0.3](https://gitlab.com/libtiff/libtiff/tree/21a904d74c72b86d7daf9e4d4e6301b6322894bc) from 2012, while the appveyor version I found is 3.8.2. If we can find a newer version for appveyor, enabling TIFF should be possible.

**Comment by GillesDuvert** [comment]
@rexso , Lena's colors and plotting directions are inverted when doing
```
GDL> image = READ_TIFF('tiff/24bit_color.tif',r,g,b,geotiff=geo)
GDL> tv,image,/true
```
RGB is Ok when inverting channels 1 and 2:
```
GDL> tv,image[0,*,*],chan=0
GDL> tv,image[1,*,*],chan=2
GDL> tv,image[2,*,*],chan=1
```
concerning the plotting direction, IDL plots Lena upside-down, not GDL.

**Comment by rexso** [comment]
@GillesDuvert thank you for the observation. I did not have much time to test out various TIFF configurations yet, which is also the reason I have not yet fully implemented the tests for READ_TIFF.

I do not personally have an IDL licence, so I have to rely on my colleagues to help me with verification, so my apologies for sometimes slow development in this area. We mostly work with single-channel GeoTIFF with floating point values, so this has been my main focus so far. So I am happy to recieve this kind of feedback, which certainly helps in the implementation.

When I started the implementation, I came across this note in the IDL documentation:
> Note: The order of the pixels contained in the returned image array is not affected by the orientation data stored in the TIFF file, or by the ORIENTATION keyword. That is, pixels are always stored in the IDL array in the same order as they are stored in the TIFF file. Since many image formats consider the upper left corner to be the origin, while IDL treats the lower left corner as the origin, this may mean that images read by READ_TIFF and displayed in IDL appear upside down. You are responsible for configuring the display to present the image in accordance with the stored ORIENTATION value. To easily create an image array that reflects orientation data stored in the TIFF file, use the IOPEN routine.

so I was somewhat aware that this might be a potential problem, but I have not done any thorough testing myself yet. Should be a trivial task to fix this problem based on your observations though.

Lately I have tried hard to fix the failing checks, and I really thought I had it done right with my last commit, but still appveyour seems to fail. Not sure if this is related to the TIFF code at all though.

Again, thank you for your feedback.

**Comment by rexso** [comment]
Also, :1st_place_medal: for recognising Lena :grinning:

**Comment by GillesDuvert** [comment]
@rexso, I accidentally found something about top & bottom of images
http://northstar-www.dartmouth.edu/doc/idl/html_6.2/WRITE_TIFFejk.html

**Comment by rexso** [comment]
I highly appreciate you guys working on this, thank you @GillesDuvert and @slayoo.
Lately I have been very busy with other tasks, and I will be quite busy the coming week as well, so right now I am not able to work much on GDL. However, after next week I will yet again have time to actively work on GDL.

**Comment by slayoo** [comment]
@GillesDuvert @rexso Our automation magic gives green light :)
Is there any reason not to merge it and follow up with further developments in new PRs?

**Comment by GillesDuvert** [comment]
Yes, that was the idea behind the magic gesture...

**Comment by slayoo** [comment]
@GillesDuvert ... yes = there is reason not to merge, or yes = let's merge? :)

**Comment by GillesDuvert** [comment]
yes = let's merge

**Comment by slayoo** [comment]
merging then (and will open a new issue with the above checkbox list prepared by @rexso)

**Comment by slayoo** [comment]
here it is: https://github.com/gnudatalanguage/gdl/issues/411

**Comment by alaingdl** [comment]
FYI on my old u14.04, after "sudo apt-get install libgeotiff-dev" I successfully compiled current version (and tested "test_tiff")

**Comment by slayoo** [comment]
Great, thanks!

**Pull request merged**
