### PR TITLE
new map_continents and support for IDLffShape objects

### PR DESCRIPTION
**Pull request by GillesDuvert**
Finished map_continents using sufficient implementation of IDLffShape + NaturalEarth data.
This implied writing IDLffShape and correcting a bug in LIST (PR #579). Also, an error was seen and corrected in save/restore (PR #577).
This PR modifies GDL sufficiently that a fresh install is necessary.
All references to gshhg are removed as GDL comes with the minimal set of Natural Earth shapes necessary to MAP_CONTINENTS. Nevertheless, converting gshhg files to shapefiles will be easy as soon as IDLffShape() is finished for writing shapefiles.
The only drawback with the NE shapes is that they are not contour oriented and thus not able to be properly filled. But so were gsshsg files! We shall appreciate the of a GIS specialist.

### CODE REVIEW

**Comment by GillesDuvert** [comment]
I've left the Shapelib requirement for windows build as I believe 1) shapelib  is easy to compile on windows, see http://download.osgeo.org/shapelib/ and https://github.com/OpendTect/shapelib and 2) windows users will be pleased to have the earth maps. Please modify the Appveyor scripts to deal with this.

**Comment by maynardGK** [comment]
<comment deleted>

**Comment by GillesDuvert** [comment]
@maynardGK , thanks for the test, but first what is the resut of `GDL> gdl_status` ? And what is your OS ?
Also, IDLffSHAPE is not a LIST, so the why the comparison?

**Comment by maynardGK** [comment]
I use a new list to compare, using help,/full, what I expect when creating a new object; with obje_new('list') you can see the method procedures and functions. It doesn't seem to happen for IDLffShape which is what I presumed to be the main issue.  I am running on windows 7; I brought the commit in by hand and merged the new code with my own - separate from, but current to, git.
I may not have all the extra bells and whistles in, here is gdl_status (and shapelib_exists()=0 so that may be missing a screw).

````
GDL> gdl_status
% Compiled module: GDL_STATUS.
Eigen3 ? :        1
FFTw ?   :        1
GRIB ?   :        0
GLPK ?   :        0
GSHHG ?  :        0
HDF ?    :        0
HDF5 ?   :        1
Magick ? :        1
NetCDF ? :        1
NetCDF4 ?:        1
OpenMP ? :        1
Proj4 ?  :        1
Proj4 new:        1
PSlib ?  :        0
Python ? :        0
UDUNITS  :        0
wxwidgets:        1
x11      :        0
GDL> print,shapelib_exists()
       0
````
I think the solution is as follows:
USE_SHAPELIB is not set, even though the code accomodates it then shapefiles.cpp is not compiled in. So the procedures which adds methods and references lib::shapelib__<methodname>
don't complain when that module is not present!  I'll fix USE_SHAPELIB in the cmake and check if that makes it work.

**Comment by maynardGK** [comment]
Ok , it now works good! In comparison to GSHHS (fill is not attempted in that test_map version) GSHHS seems to have more vertices that are well-filtered in the shapelib version.
I've made screen-grabs of comparison runs, test_map using shapelib (UPPER PLOT) and the previous test_map using gshhs.
shapelib_vs_gshhs
````
$ gdlf
string(GDLDATADIR): D:/installs/share/gnudatalanguage
2 GSHHS data dir : D:\installs\share\gnudatalanguage\resource\maps\\

  GDL - GNU Data Language, Version 0.9.8e (/f/gdl )

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
GDL> help,obj_new('idlffshape'),/full
<Expression>    OBJREF    = <ObjHeapVar1(IDLFFSHAPE)>
** Structure IDLFFSHAPE, 9 tags,memsize =72, data length=46/46:
   IDLFFSHAPE_TOP  LONG64                         0
   IDLFFSHAPEVERSION
                   INT              0
   FILENAME        STRING    ''
   ISOPEN          INT              0
   SHPTYPE         INT              0
   PATTRIBUTE      POINTER   <NullPointer>
   SHAPEHANDLE     LONG64                         0
   DBFHANDLE       LONG64                         0
   IDLFFSHAPE_BOTTOM
                   LONG64                         0
Method procedures (7):
 ADDATTRIBUTE CLEANUP CLOSE DESTROYENTITY GETPROPERTY PUTENTITY SETATTRIBUTES
Method functions (4):
 GETATTRIBUTES GETENTITY INIT OPEN
TODO Cleanup
GDL> .run d:\home\greg\testing\test_map
% Compiled module: INTERNAL_GDL_MAP_LIBS.
% Compiled module: GET_MAP_PROCEDURES.
% Compiled module: TEST_MAP_PROCEDURES.
% Compiled module: INTERNAL_GDL_MAP_CHECK.
% Compiled module: DOWEBREAK.
% Compiled module: TEST_MAP.
<snip>
GDL> cd,'D:\F Volume\gdl\gdl-44754430\src\pro\'
GDL> .run map_continents
% Compiled module: MAP_GETCOMPOUND.
% Compiled module: MAP_CONTINENTS.
GDL> test_map
Exemple 1: Should plot the whole world centered on the Japan time line
% Compiled module: GDLDRAWSHAPECOMPOUND.
Press F for filling continents, Q to quit, any key or Enter to continue F
Press Q to quit, any key or Enter to continue
Exemple 2: Should plot the whole world centered on the North America (with rotation)
Press F for filling continents, Q to quit, any key or Enter to continue
Exemple 3: Should plot the whole "classical view" of the world with a grid
% Compiled module: MAP_GRID.
Press F for filling continents, Q to quit, any key or Enter to continue
Exemple 4: Should plot Europa centered on Paris Observatory using Gnomic Projection
Press F for filling continents, Q to quit, any key or Enter to continue F
Press Q to quit, any key or Enter to continue
Exemple 4bis: Should plot Europa centered on Paris Observatory using Gnomic Projection
 countries)
TODO Cleanup
TODO Cleanup
Press F for filling continents, Q to quit, any key or Enter to continue
Exemple 5: Should plot North America using Gnomic Projection
Press F for filling continents, Q to quit, any key or Enter to continue
Exemple 6: Should plot North America using Satellite Projection
Press F for filling continents, Q to quit, any key or Enter to continue
Exemple 7: Should plot World using Robinson projection
<snip>
% MAP_SET: Goode's Homolosine: center is always on equator.
<snip>
TODO Cleanup
Press F for filling continents, Q to quit, any key or Enter to continue
Press F for filling continents, Q to quit, any key or Enter to continue
Press F for filling continents, Q to quit, any key or Enter to continue
Press F for filling continents, Q to quit, any key or Enter to continue
Press F for filling continents, Q to quit, any key or Enter to continue
Press F for filling continents, Q to quit, any key or Enter to continue
Press F for filling continents, Q to quit, any key or Enter to continue
% Compiled module: DIST.
% Compiled module: MAP_IMAGE.
last demo done
````
The fill gets inverted across a zero in the map coordinates

shapelib_vs_gshhs_3

**Comment by GillesDuvert** [comment]
@maynardGK wrote: "The fill gets inverted across a zero in the map coordinates". First, there is (still) a bug in contour-filling when projections define special great circles on the sphere where the contours need to be cut and closed along the meridians. This is a work in progress!
Besides, it seems that the NaturalEarth contours as well as the gshhsg contours are not properly closed or oriented to be correctly filled. IDL fails to fill them too...

**Comment by GillesDuvert** [comment]
@maynardGK so I get that you have the magic command for appveyor to get libshape-devel?

**Comment by maynardGK** [comment]
shapelib and proj4 are easy downloads from the msys2 repositories and so it should be trivial to accomodate into appveyor.yml
````
mingw32/mingw-w64-i686-shapelib 1.4.1-1 [installed: 1.3.0-2]
    simple C API for reading and writing ESRI Shapefiles (mingw-w64)
mingw64/mingw-w64-x86_64-shapelib 1.4.1-1 [installed: 1.3.0-2]
    simple C API for reading and writing ESRI Shapefiles (mingw-w64)

mingw32/mingw-w64-i686-proj 5.2.0-1 [installed: 4.9.2-1]
    Cartographic projection software (PROJ.4) (mingw-w64)
mingw64/mingw-w64-x86_64-proj 5.2.0-1 [installed: 4.9.2-1]
    Cartographic projection software (PROJ.4) (mingw-w64)
````
 USE_SHAPELIB is used to exclude shapelib.cpp from the list of compiled units in src/CMakelists.txt; the shapelib exclusion should probably occur inside the source code as it does for the other add-ons.
Also with no shapelib, there should be no built-in IDLffShape when USE_SHAPELIB is not in effect.

 plplot has a FindShapelib.cmake module that will also check on shapefil.h; we may as well just copy that one over.

**Comment by GillesDuvert** [comment]
Still in progress. Do not merge.

**Comment by GillesDuvert** [comment]
windows build is currently without map support.
appveyor script needs to be modified to compile libproj4 and libshape

**Comment by maynardGK** [comment]
download PR #520 and inspect scripts/appveyor_1.msys: there you find gdl-2.5 is downloaded from pre-compiled repository used by msys2.

also note the gdl build cmake.out at about line 990:
````
-- Options
OpenMP support         ON (flag: -fopenmp)
WxWidgets              ON (libs:-LC:/projects/gdl/mingw/wxWidgets-3.0.2-17/lib;-pipe;-lwx_baseu-3.0;-lwx_mswu_core-3.0;-lwx_mswu_adv-3.0; headers:)
ImageMagick            OFF
TIFF                   ON (libs:C:/projects/gdl/mingw/mingw64/lib/libtiff.dll.a; headers:C:/projects/gdl/mingw/mingw64/include)
GeoTIFF                ON (libs:C:/projects/gdl/mingw/mingw64/lib/libgeotiff.dll.a; headers:C:/projects/gdl/mingw/mingw64/include)
NetCDF                 OFF
HDF4                   OFF
HDF5                   OFF
FFTW                   ON (libs:C:/projects/gdl/mingw/mingw64/lib/libfftw3.dll.a;C:/projects/gdl/mingw/mingw64/lib/libfftw3f.dll.a; headers:C:/projects/gdl/mingw/mingw64/include)
Libproj4               ON (libs:C:/projects/gdl/mingw/mingw64/lib/libproj.dll.a; headers:C:/projects/gdl/mingw/mingw64/include)
MPI                    OFF
Python                 OFF
UDUNITS-2              OFF
EIGEN3                 ON (libs:; headers:C:/projects/gdl/mingw/mingw64/include/eigen3)
GRAPHICSMAGICK         ON (libs:C:/projects/gdl/mingw/graphicsmagick-1.3.27-Q8/lib/libGraphicsMagick.dll.a;C:/projects/gdl/mingw/graphicsmagick-1.3.27-Q8/lib/libGraphicsMagick++.dll.a; headers:C:/projects/gdl/mingw/graphicsmagick-1.3.27-Q8/include/GraphicsMagick)
GRIB                   OFF
GLPK                   OFF
GSHHG                  ON (libs:; headers:)
pslib                  OFF
XPortMinGW (Win32 Xlib)                OFF
libpng                 ON (libs:; headers:)
-- Mandatory modules
Plplot                 ON (libs:C:/projects/gdl/mingw/plplot-5.13/lib/libplplot.dll.a;C:/projects/gdl/mingw/plplot-5.13/lib/libplplotcxx.dll.a; headers:C:/projects/gdl/mingw/plplot-5.13/include)
GNU Readline           ON (libs:C:/projects/gdl/mingw/mingw64/lib/libreadline.dll.a;C:/projects/gdl/mingw/mingw64/lib/libhistory.dll.a; headers:C:/projects/gdl/mingw/mingw64/include)
BSD Editline           OFF
GSL                    ON (libs:C:/projects/gdl/mingw/mingw64/lib/libgsl.dll.a;C:/projects/gdl/mingw/mingw64/lib/libgslcblas.dll.a; headers:C:/projects/gdl/mingw/mingw64/include)
Zlib                   ON (libs:C:/projects/gdl/mingw/mingw64/lib/libz.dll.a; headers:C:/projects/gdl/mingw/mingw64/include)
RPC                    ON (libs:; headers:RPC_INCLUDE_DIR-NOTFOUND)
-- Configuring done
-- Generating done
CMake Warning:

````

libshape and proj4 are already incorporated but it needs to be incorporated into master, so that a working baseline is established before additional packages are added.

**Comment by GillesDuvert** [comment]
@maynardGK OK many many thanks. Thus, to be concluded soon!

**Comment by GillesDuvert** [comment]
everything OK, on windows, too:
gdl_on_windows7_64bits_wxwidgets_proj4_shape

**Comment by maynardGK** [comment]
Test_container hung appveyor, maybe for an error in container::equals ? 
Does a test hang if there is a simple IDL error causing execution to halt?
````
$ greg@Homerw7  /f/github/gdlgit
$ gdl64
% WARNING: your version of the GraphicsMagick library will truncate images to 8 bits per pixel

  GDL - GNU Data Language, Version 0.9.9 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > this->
() (which is 0)
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > this->
() (which is 0)
GDL> test_container
% Compiled module: TEST_CONTAINER.
% EQUALS: Incorrect number of arguments.
% Error occurred at: TEST_CONTAINER     233 F:\github\gdlgit\testsuite\test_container.pro
%                    $MAIN$
% Execution halted at: TEST_CONTAINER     233 F:\github\gdlgit\testsuite\test_container.pro
GDL> test_byte_conversion
% Compiled module: TEST_BYTE_CONVERSION.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_BYTE_BUG_586:   NO errors encountered during TEST_BYTE_BUG_586 tests
% Compiled module: ERRORS_CUMUL.
% TEST_BYTE_BASIC_32768:   NO errors encountered during TEST_BYTE_BASIC_32768 tests
% TEST_BYTE_BASIC_32768:   NO errors encountered during TEST_BYTE_BASIC_32768 tests
% TEST_BYTE_STRING2BYTE:   NO errors encountered during TEST_BYTE_STRING2BYTE tests
2017-03-11 : First run should be OK in GDL
````
````
greg@Homerw7 MINGW32 /f/github/gdlgit
$ grep -in equals testsuite/test_container.pro
233:match = p.Equals(5)
236:  MYMESS, nb_errors,' testing CONTAINER::EQUALS unlikely ...'
243:jj=where(p.equals(ndgen),n6)
247:  MYMESS, nb_errors,' testing CONTAINER::EQUALS unlikely ...'
253:  MYMESS, nb_errors,' testing CONTAINER::EQUALS unlikely ...'
261:jj=where(p.equals(ndgen),n6)
263:jj=where(p.equals(ndgen),n6)
````

**Comment by GillesDuvert** [comment]
Hi, @maynardGK .
Looks like #43 .  The code was patched in testsuite/CMakeLists.txt for unix, but bug may be there for windows. The idea is to "..reopen /dev/null as stdin. This causes gdl to exit after running a test with an error instead of hanging at a prompt."

**Comment by GillesDuvert** [comment]
yepee.

**Comment by GillesDuvert** [comment]
Hmm need to check why sone travis test do not pass now.

**Review by maynardGK — APPROVED** [review]

**Comment by maynardGK** [comment]
TEST_MAP uses MAP_SET which I only found from exelislib download, not in git:
````
GDL> test_map
% Compiled module: TEST_MAP.
Exemple 1: Should plot the whole world centered on the Japan time line
% Compiled module: MAP_SET.
% Compiled module: MAP_CLIP_SET.
% Compiled module: MAP_CONTINENTS.
% Compiled module: FILEPATH.
% Compiled module: GDLDRAWSHAPECOMPOUND.
Press F for filling continents, Q to quit, any key or Enter to continue q
GDL> help,/sour
Compiled Procedures:
$MAIN$
GDLDRAWSHAPECOMPOUND     F:\github\gdlgit\src\pro\gdldrawshapecompound.pro
GDLDRAWSINGLESHAPE       F:\github\gdlgit\src\pro\gdldrawshapecompound.pro
GDLFREESHAPECOMPOUND     F:\github\gdlgit\src\pro\gdldrawshapecompound.pro
GET_MAP_PROCEDURES       F:\github\gdlgit\testsuite\test_map.pro
INTERNAL_GDL_MAP_CHECK   F:\github\gdlgit\testsuite\test_map.pro
MAP_CLIP_SET             F:\github\gdlgit\src\pro\map_clip_set.pro
MAP_CONTINENTS           F:\github\gdlgit\src\pro\map_continents.pro
MAP_SET                  D:\home\greg\gdlpro\exelislib\map_set.pro
TEST_MAP                 F:\github\gdlgit\testsuite\test_map.pro

Compiled Functions:
DOWEBREAK                F:\github\gdlgit\testsuite\test_map.pro
FILEPATH                 F:\github\gdlgit\src\pro\filepath.pro
INTERNAL_GDL_MAP_LIBS    F:\github\gdlgit\testsuite\test_map.pro
MAP_GETCOMPOUND          F:\github\gdlgit\src\pro\map_continents.pro
PATH_SEP                 D:\home\greg\gdlpro\new\path_sep.pro
TEST_MAP_PROCEDURES      F:\github\gdlgit\testsuite\test_map.pro
````

**Comment by GillesDuvert** [comment]
Indeed, at the moment MAP_SET and MAP_PROJ_INIT are not available with GDL. 
That's why test_map is not in testsuite/Makefile.am
All this map projection stuff will be complete only with a writing of those two procedures above.
It is not as complicated as it could appear at first glance, I'll probably tackle it at some point.

**Pull request merged**
