### PR TITLE
More radical CMake fixes

### PR DESCRIPTION
**Pull request by pjb7687**
I have tried to completely get rid of the `launchtest` and found that it still works well, and tests got much faster on Windows.

From: 
```
Total Test time (real) = 100.80 sec
```

To:
```
Total Test time (real) =  53.48 sec
```

All you need to do is `make test` instead of `make check`.

### CODE REVIEW

**Comment by slayoo** [comment]
I'll have a look and test on my machine asap

**Comment by GillesDuvert** [comment]
first return, build on linux mageia 7:
```
97% tests passed, 5 tests failed out of 189

Total Test time (real) = 106.14 sec

The following tests did not run:
        100 - test_grib.pro (Skipped)
        126 - test_mpi.pro (Skipped)

The following tests FAILED:
         23 - test_bug_3086851.pro (Failed)
         65 - test_call_external.pro (Failed)
         76 - test_delvarrnew.pro (Failed)
         93 - test_fixprint.pro (Failed)
        154 - test_same_name.pro (Failed)
```
concerning the tests, doing 
```
GDL> cd,"~/gdl/testsuite/                  
GDL> test_bug_3086851
% Compiled module: TEST_BUG_3086851.
```
So: WORKS

On the contrary, test_call_external fails:
```
GDL> test_call_external
% Compiled module: TEST_CALL_EXTERNAL.
% LOOKING_FOR_CE_LIB: library >>libtest_ce.so<< not found or not compiled !
```
but it does not mean call_external does not work. On the contrary, it works well.

**Comment by pjb7687** [comment]
Thanks for the review!

1. I have added a 'fixture' (https://cmake.org/cmake/help/latest/prop_test/FIXTURES_SETUP.html) which builds `libtest_ce` before running tests - this should fix `test_call_external`.
2. Fixed path separator - this should be relevant to the other tests.

**Comment by alaingdl** [comment]
build on CI on MSwin is very slow because          76 - test_delvarrnew.pro (Failed)
takes a while ... (stuck just 1h in fact ... thanks to the 3600 in CmakeLists ;)

@eloirozier will try to have a look on that

**Comment by pjb7687** [comment]
> build on CI on MSwin is very slow because 76 - test_delvarrnew.pro (Failed)
> takes a while ... (stuck just 1h in fact ... thanks to the 3600 in CmakeLists ;)
> 
> @eloirozier will try to have a look on that

This seems to be a really tricky problem to fix... Because I can't reproduce this on my machine, this only happens on Github Actions! I suspect SPAWN on Windows, but have no clues yet.

**Comment by alaingdl** [comment]
preliminary test here with problematic system are OK :+1: 
(more tests to come, ASAP, but compiling on a 48-cores machine is sooo fast !)

**Comment by eloirozier** [comment]
The test_delvarrnew problem on MSWin seems to be caused by these 2 lines in the generated 'delvarrnew.pro' file

`i=1 & j=2 & k=3`
`.rnew rnewtest`

rnewtest.pro :

; RNEW testproc
delvar,i,j,k,igstr
end

No error if i execute `.rnew rnewtest` in a clean GDL, nor if i initialize, prior to the .rnew call one of the deleted variables (i, j or k) but if 2 or more variables are set (i=1 & j=5 $ .rnew rnewtest) then GDL crashes completly

GDL> i=1 & j=5
GDL> .rnew rnewtest
Assertion failed: i<sz, file C:/gdl/gdl/src/datalistt.hpp, line 124

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Magick: abort due to signal 22 (SIGABRT) "Abort"...

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by GillesDuvert** [comment]
build on Catalina, (prep, build) on a fresh VM.
OK except
```
[100%] Built target gdl
failed to create symbolic link '/Users/gildas/gdl/src/gdl' because existing path cannot be removed: Operation not permitted
make[2]: *** [CMakeFiles/symlink_gdl] Error 1
make[1]: *** [CMakeFiles/symlink_gdl.dir/all] Error 2
```
this because the zip file of [cmake-fixes](https://github.com/gnudatalanguage/gdl/tree/cmake-fixes) still contained erroneous directory src/gdl. removing this spurious gdl, everything fine.

Question: why the symbolic link?

**Comment by alaingdl** [comment]
All is OK for me on 6 different machines (debian 9 & 10, ubuntu, OSX 10.14), what was not OK yesterday seems to be fixed. Thank @pjb7687 for high reactivity and patience ! I feel better we can compile as long as compiler is c++11 compatible & cmake 3.7+

Why not delivering soon ? What we have to wait for ?

@eloirozier is working on Qhull, making significant progress, but he needs more time to fix the 8+ check & to write some tests,
will be perfect for a 1.1 soon ;)

**Comment by GillesDuvert** [comment]
Last test: on windows 10, prep OK but build says:
```
-- Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS NumPy) (found suitable version "3.9.5", minimum required is "3")
CMake Error at CMakeLists.txt:899 (message):
  Python is required but was not found.
```
I do not find anything like mingw-w64-x86_64-python-devel ...

BTW forcing DPYTHON=OFF for Windows may not be so outrageous...

**Comment by pjb7687** [comment]
@GillesDuvert The recent PRs include changes in #886, you will need a native Python instead, not the one from MSYS

But it's interesting to know that it doesn't properly work with MinGW Python..?

> -- Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS NumPy) (found suitable version "3.9.5", minimum required is "3")

It seems that CMake found Python, but just not NumPy. Could you confirm whether you already installed `mingw-w64-x86_64-python-numpy`?.

**Comment by GillesDuvert** [comment]
Yes, such as:
`pacman -Sy mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-numpy`

**Comment by pjb7687** [comment]
@GillesDuvert I can reproduce this. Can you try this: `which python`? I think that's because CMake seems to prefer the MSYS Python (3.9.5 is the latest) over MinGW Python (3.8.9 is the latest).

**Comment by GillesDuvert** [comment]
```
$ which python
/mingw64/bin/python

```

**Comment by GillesDuvert** [comment]
installing Windows Python (https://www.python.org/) does not help.

**Comment by pjb7687** [comment]
I introduced a new environment variable "PYTHON_EXECUTABLE" (https://github.com/gnudatalanguage/gdl/commit/7ddb8b3e1ce9e9ac3b1ff2884472af5348663496). With this you can choose which python should be linked to GDL.

Usage (example):
```
export PYTHON_EXECUTABLE=/c/Python39/python.exe
.ci/build.sh build
```

**Comment by GillesDuvert** [comment]
Works! But with exactly the 'good' version in the mingw case:
 `export PYTHON_EXECUTABLE=/mingw64/bin/python3.8.exe ` --> OK
` export PYTHON_EXECUTABLE=/mingw64/bin/python3.exe`  --> NOK
` export PYTHON_EXECUTABLE=/mingw64/bin/python.exe`  --> NOK
(all 3 'executables' existing)

OK in the windows-installed python case, although perhaps a bit complicated to find where it is installed and convert the windows path to a unix path, not for beginners? 
 `export PYTHON_EXECUTABLE=/c/Users/gildas/AppData/Local/Programs/Python/Python38/python.exe`

**Comment by slayoo** [comment]
> I'll have a look and test on my machine asap

Trying out current git version on Debian, I came across the following issues:
- the ``libwxgtk2.8-dev`` Ubuntu/Debian package hint seems wrong, ``libwxgtk3.0-gtk3-dev`` worked for me
- the suggested Debian ImageMagick package does not ship the required ``Magick++-config`` tool, switched to GraphicsMagick

Compilation went OK with one warning:
```
[ 20%] Building CXX object src/CMakeFiles/gdl.dir/datatypes.cpp.o
In file included from /usr/include/python3.9/numpy/ndarraytypes.h:1822,
                 from /usr/include/python3.9/numpy/ndarrayobject.h:12,
                 from /usr/include/python3.9/numpy/arrayobject.h:4,
                 from /home/slayoo/devel/gdl/src/topython.cpp:22,
                 from /home/slayoo/devel/gdl/src/datatypes.cpp:38:
/usr/include/python3.9/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
```

Linking also one warning:
```
[100%] Linking CXX executable gdl
/usr/bin/ld: warning: libproj.so.19, needed by /usr/lib/x86_64-linux-gnu/libgeotiff.so, may conflict with libproj.so.22
```

... and all tests fail with segfault due to:
```
free(): invalid pointer
```
gdb suggests that the segfaults are caused by the sgeo::proj::common::UnitOfMeasure::~UnitOfMeasure() desctructor:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff53a3537 in __GI_abort () at abort.c:79
#2  0x00007ffff53fc708 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff550ae31 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff54039fa in malloc_printerr (str=str@entry=0x7ffff550905e "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff5404bb4 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007ffff6304c8f in osgeo::proj::common::UnitOfMeasure::~UnitOfMeasure() () at /lib/x86_64-linux-gnu/libproj.so.22
#6  0x00007ffff53bca66 in __cxa_finalize (d=0x7ffff4066000) at cxa_finalize.c:83
#7  0x00007ffff3db0083 in  () at /lib/x86_64-linux-gnu/libproj.so.19
#8  0x00007fffffffe080 in  ()
#9  0x00007ffff7fe2343 in _dl_fini () at dl-fini.c:138
```
@GillesDuvert is it a know issue?
I guess the linker warning might be somewhat related

**Comment by GillesDuvert** [comment]
clearly.
This is annoying and strange as distributions shoudl not permit this ?

**Comment by pjb7687** [comment]
Perhaps we can report Debian packagers to recompile libgeotiff.

**Comment by slayoo** [comment]
I guess this is because I'm using "sid" - the unstable version of Debian. Anyhow, switching off geotiff, the warning and segfaults go away (and of course, geotiff is not to blame). 

With the updated code from master (pulled just now), I get:

```
100% tests passed, 0 tests failed out of 190

Total Test time (real) =  40.09 sec
```
Great! Bravo! Kudos to all active developers!

**Pull request merged**
