### PR TITLE
Create gdl.desktop

### PR DESCRIPTION
**Pull request by alexmyczko**
allow launching from menu system, should be installed in /usr/share/applications, and icon should also be added and put in /usr/share/icons called gdl as svg or png preferably.

### CODE REVIEW

**Comment by alaingdl** [comment]
Hi

Could you consider to put in the CMakeLists.txt what is requered to 
propagate this in packages (in order they  can add this file in the right place) ?
Tanks !

(It would be great too to add the testsuite/ (+bench) in the package !)

**Comment by GillesDuvert** [comment]
Welcome addition, we now need a good icon and somehow have a script to get this .desktop put  at the good location in the (freedesktop.org?) system. Probably our fellows packagers can tell what is needed?

**Comment by slayoo** [comment]
@gnudatalanguage/gdlpackagers ?

**Comment by olebole** [comment]
In Debian, we put it under `/usr/share/applications/`, but there is a freedesktop.org specification for it (however it seems to be not simple go get the canonical definition). From [this](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html#desktop-file-id), I would think that it goes to an `application` subdir of one of the paths in `$XDG_DATA_DIRS`.

**Comment by GillesDuvert** [comment]
This PR is dormant as:
1) writing a .desktop for GDL is easy but having it put at the right (freedesktop compliant) place by the installer seems to be another piece of cake --- certainly better done by one of the GDL packagers (sorry).
2) and we need an icon.

**Comment by alexmyczko** [comment]
Please see https://github.com/gnudatalanguage/gdl/issues/644 for some example icons

**Pull request merged**
