### PR TITLE
Benchmark on windows 2 - the return

### PR DESCRIPTION
**Pull request by eloirozier**
I hope this time it's right...

### CODE REVIEW

**Comment by GillesDuvert** [comment]
Hi Eloi, do you have a windows machine with gdl installed to test these scripts first? Because **this is not going to work**...
SPAWN sends a command to the OS. the Windows OS does not know about 'sysctl' and this will end in error.
Concerning the code in generate_filename.pro, as GDL has the command 'SYSTIME' that  does the job irrespective of the operating system, I suggest to use it instead of a dangerous SPAWN command. Use also PATH_SEP() function to deal with the peculiarities of Windows vs. Unix+Mac instead of painstakingly teste if the OS is Windows or Linux etc.

**Review by GillesDuvert — CHANGES_REQUESTED** [review]
GDL does not have (yet) timestamp()
Either use cgtimestamp() or create a timestamp() for GDL (easy: take example from cgtimestamp() )

**Comment by eloirozier** [comment]
Thanks for telling me
I assumed timestamp() existed on GDL because i tested my code while IDL librairies where included in my !path variable... I'll use cgtimestamp() instead

**Comment by alaingdl** [comment]
maybe we shall consider to add it, using c++ code ?
https://stackoverflow.com/questions/9527960/how-do-i-construct-an-iso-8601-datetime-in-c

**Pull request merged**
