### PR TITLE
added script to generate windows installer

### PR DESCRIPTION
**Pull request by pjb7687**

### CODE REVIEW

**Comment by pjb7687** [comment]
Solving #602.

**Comment by GillesDuvert** [comment]
Looks nice, installer works!
Two caveats, first, launching the installer is awkward because the .exe is not trusted by Microsoft (normal)
Second, !PATH is empty (try `plot,dist(3)` )

**Comment by pjb7687** [comment]
It seems like when the installer launches GDL, it cannot find envvars properly. Could you try relaunching GDL and run the command again? And for plotting, this one is needed: https://github.com/gnudatalanguage/gdl/pull/864#issuecomment-757503007

**Comment by pjb7687** [comment]
Seems like mine works well..
image

**Comment by GillesDuvert** [comment]
Thanks, for me now a plot appears...
But then disappears instantly. Will the future installers contain the patched plplot?

**Comment by pjb7687** [comment]
I think you are not using the patched `GDL.exe` from https://github.com/gnudatalanguage/gdl/pull/864. You can download the artifact there and replace `GDL.exe` for testing.
And yes, the patched plplot will be automatically included when MSYS2 repo is updated. Maybe after several days.

**Pull request merged**
