### PR TITLE
Quiet possible uninitialized variable warning

### PR DESCRIPTION
**Pull request by opoplawski**

### CODE REVIEW

**Comment by slayoo** [comment]
Thanks Orion! 
GDLInterpreter.cpp is a generated file, hence the changes need also to be reflected in gdlc.i.g

**Comment by opoplawski** [comment]
Hmm, no idea to to make this change in gdlc.i.g.

**Comment by GillesDuvert** [comment]
Yes, l'll make this small change in one of the future updates of the .g files
Being in sync between .g and .cpp/.hpp files is very important, and all commits should be checked for that before merging. They should be tagged "todo-generated-files" also.

**Comment by GillesDuvert** [comment]
Should be present now that #308 is done.

**Pull request closed without merging**
