### PR TITLE
correcting to new declaration of WShow(int, bool,int); CmakeLists.txt policy 0012 set to old to reduce warnings; Enhance obj_destroy to allow multiple parameters; Provide PathSeparator() as static routine instead of lib::

### PR DESCRIPTION
**Pull request by maynardGK**
(devicewin.hpp) will probably allow me to proceed with MingW compilation of git code.
CmakeLists.txt policy 0012 set to old to reduce warnings from FindopenMP.cmake (using cmake 10)

### CODE REVIEW

**Comment by slayoo** [comment]
@maynardGK Thank you!

Shall we try to split these changes so each PR (and hence each branch) correspond to separate update (i.e. WShow vs. obj_destroy).

Why is the change to CMakeLists.txt needed?

I though of also waiting with merging any win32 #ifdefed changes till we have continuous integration set up for Windows (see https://github.com/gnudatalanguage/gdl/issues/1)

**Comment by GillesDuvert** [comment]
Hello, @maynardGK ! 
concerning devicewin.cpp:
Could you try first to remove wshow from devicewin and test? Indeed, "normally", the win device "wshow" should be inherited from GraphicsMultiDevice::WShow and does not need to be overloaded locally. This to ensure a common behaviour for the 3 variants of "multi-windows", X, wxWidgets and Win.
If this is asking too much, there is no problem in accepting this patch of course.

**Comment by GillesDuvert** [comment]
@slayoo 
the three patches are unrelated. I am not familiar with Git, but I suspect it would be better to make 3 successive changes.

**Comment by GillesDuvert** [comment]
I forgot to mention the basic_pro.cpp patches are OK. Makes code simpler, also!

**Comment by slayoo** [comment]
Then I highly recommend splitting them into three PRs... or at least doing so in the future :)

**Comment by maynardGK** [comment]
Hi guys,

devicewin: I just tried it with WShow removed, window behavior is different and maybe worse
but I can't tell as the new gdlstream functions are just in and plotting is not yet fixed.

cmake_policy change is there only by accident it tagged along with devicewin.  I got a long
cmake diatribe in cmake.out about a line of code in FindOpenMP (because if(TRUE) happened) and 
this is the cause.

obj_destroy was separately committed and pushed but got merged when I did the pull request.  It seems to be automatically done .

**Comment by slayoo** [comment]
Github's pull requests are updated whenever something is pushed to the branch the PR is based on.
To prevent it, and to allow separate simultaneous PRs the changes need to ge to separate branches.
HTH

**Comment by GillesDuvert** [comment]
@maynardGK : I do not see why file.cpp would not continue to be the unique location where PathSeparator() is defined? It is advantageous to factorize code and maintain only at one place. As dialog.cpp include file.hpp there is no need for this patch?.

**Comment by maynardGK** [comment]
Ok this is confusing.   Now I've pushed another commit on trivia branch (it is more trivia) and without further action (no PR) it has appeared in these comments (under slayoo's CMake warnings comment.) 
as if it was already appended to the pull requests. I'll let the situation settle a bit  here before pushing more trivia.  Is there a way to provide separated multiple commits in a single branch?

@Gilles PathSeparator is so simple I believe it is better kept local.

**Comment by slayoo** [comment]
@maynardGK Indeed, the commit-branch-clone-fork-pull-request logic is often confusing.

Basically, the prerequisite is to have a separate branch per every feature (and separate from the master branch). The pull requests are bound to a specific branch and not a set of commits. As a consequence, if there is a correction needed to be done within a given PR, it is enough to commit something to the given branch, then push, and then the changes will appear here and any continuous integration actions will be triggered. 

On the other hand, any non-related development needs to be done in separate branches, and then a new pull request can be opened pointing to this separate branch. Note that creation of these separate branches generally needs to be done based on a "clean" master to avoid containing changes from on PR in the other from the beginning of the branch existence.

HTH

**Comment by GillesDuvert** [comment]
@maynardGK : factorization is a key for simpler code maintainance. irrespective of the (at the moment) simple aspect of PathSeparator, which is factorized, what is the need to redefine it locally?

**Comment by maynardGK** [comment]
@GillesDuvert : PathSeparator() will not be used by file.cpp after it has completed its modifications.
The routine is dangling there in file.cpp and its only purpose is to be there for Dialog.cpp.  
More often, file.cpp routines are  checking for either separator.  _WIN32 runs can use the forward slash as easily as the backwards - to me the forwards is preferable since the filesystems are shared with a Linux. (A backwards slash is needed for the raw CMD.exe which uses forward-slash for command switch.)

**Comment by maynardGK** [comment]
@slayoo Separate branches is ok but there are many cases at the moment with a lot of
edits and some cross-fertilization.  For instance, in file.cpp my mods for file_search, file_move,
each will use a subroutine related to path search.  So I think it makes sense to incrementally
change that file in multiple commits on the same branch. 
  In a similar vein, changes to basic_pro.cpp are ready in addition to the trivia here and the heap_refcount
branch.  heap_refcount would be useful to have nailed down for testing/usage, and also to un-complicate the differencing view.  Heap_refcount is pretty self-contained and not difficult, but more complicated examples can be anticipated.

**Comment by maynardGK** [comment]
I will close this pull request soon:
WShow issue will become a single branch
obj_destroy will be a commit in a series of patches for basic_pro.
The CMake change is only relevant to the use of late-model CMake (I am using 3.10 here) and
I can live without it.
Path_separator() change to dialog() will move to where file.cpp is changed. 
Probably have file.cpp host PathSeparator().

**Comment by maynardGK** [comment]
Closing this PR. obj_destroy will be committed in a series of patches for basic_pro.

**Comment by maynardGK** [comment]
Now I'm really closing

**Pull request closed without merging**
