### PR TITLE
Change in REBIN() and test_rebin

### PR DESCRIPTION
**Pull request by Jeanne-jw**
1. I made some changes in the order of calculation in datatypes.cpp, where there are functions for rebin(). 
2. The old test_rebin.pro isn't OK with IDL, because the results of GDL and IDL for one command are different. Now this bug is fixed.

### CODE REVIEW

**Comment by GillesDuvert** [comment]
Dear @Jeanne-jw , excellent! 
Could you however remove the statements `SizeT count_t = 0;` and the commented test lines (`//tic //toc //std::cout...` ) in order to keep the changes to the minimum? Thanks.

**Comment by Jeanne-jw** [comment]
Ok ! No problem. Sorry to have left it there.

**Comment by Jeanne-jw** [comment]
#### Notes:
1. Complex, double complex and string are not usable, in both IDL and GDL.
2. For float data, the speed has been increased to the same level of IDL, no matter for expand or compress/ sample or not sample. 
3. For int / long data, when **new dimension < original dimension**  or when **sample=1** the new version runs great. While when we try to expand a matrix in not sample way, it runs as slow as the old version. As shown in the ***right part of the first image*** (y : how long time it takes; x : different steps), the green line is much higher than the blue line. Need to continue in the future. 
speed_rebin_idl_vs_gdl

**Comment by alaingdl** [comment]
It would be great to add a bench based on that around.

**Pull request merged**
