### PR TITLE
WIP: re-insert some tests that should work ok with Appveyor builds.

### PR DESCRIPTION
**Pull request by maynardGK**
This should be a minimal change to Appveyor.yml, further attempts to change it (#766 ) have done very poorly!

### CODE REVIEW

**Comment by maynardGK** [comment]
Again, Appveyor's runtime environment did not correctly run the 32-bit builds.
from build 1301, running tests that failed for 1303:
````
$ gdl32
  GDL - GNU Data Language, Version 1.0.0-rc.2 git
- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL> test_gh00716
% Compiled module: TEST_GH00716.
GDL> test_fz_roots
% Compiled module: TEST_FZ_ROOTS.
% TEST_FZ_ROOTS_ON_POLY: Polynomial 0 : No Errors founded
% TEST_FZ_ROOTS_ON_POLY: Polynomial 1 : No Errors founded
% TEST_FZ_ROOTS_ON_POLY: Polynomial 2 : No Errors founded
% TEST_FZ_ROOTS_ON_POLY: Polynomial 3 : No Errors founded
% TEST_FZ_ROOTS_ON_POLY: Polynomial 4 : No Errors founded
GDL> test_fx_roots
% Procedure not found: TEST_FX_ROOTS
% Execution halted at: $MAIN$
GDL> test_fx_root
% Compiled module: TEST_FX_ROOT.
% Compiled module: ROUTINE_NAME.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% Compiled module: ERRORS_CUMUL.
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% TEST_FX_ROOT_ON_FUNC:   NO errors encountered during TEST_FX_ROOT_ON_FUNC tests
% WHERE_DO_WE_CONVERGE: convergence on expected roots well done
% WHERE_DO_WE_CONVERGE:   NO errors encountered during WHERE_DO_WE_CONVERGE tests
% COMPLEX_ROOT_OF_POLYNOM:   NO errors encountered during COMPLEX_ROOT_OF_POLYNOM tests
% TEST_FX_ROOT: =====================================================
% TEST_FX_ROOT: =                                                   =
% TEST_FX_ROOT: =  NO errors encountered during TEST_FX_ROOT tests  =
% TEST_FX_ROOT: =                                                   =
% TEST_FX_ROOT: =====================================================
GDL>
````

**Comment by maynardGK** [comment]
That is build 1321, successful again.

**Comment by slayoo** [comment]
@maynardGK I've just fixed here a conflict with master appveyor.yml - hope works OK, please pull to your fork and local repo

**Comment by maynardGK** [comment]
@slayoo I've pulled into Apptests from your merge, then modified appveyor.yml back to gcc6.3 x86+i686, Release+debug.  Appveyor appears stalled on 2672365 (?) and travis also doesn't appear here (I've cancelled the travis jobs at 2672365)

**Comment by slayoo** [comment]
It seems there was just a long queue of jobs, cleaned it up, now the newest one is running: https://ci.appveyor.com/project/slayoo/gdl/builds/33628148

**Comment by slayoo** [comment]
Please, let's fix #615 on this occasion - making appveyor indicate builds as failed if the tests fail. Of course, we can make two runs - one that checks a predefined list of tests that were previously passing on Windows (and this would trigger build failure), and another one with more tests to run (which would just print failures to the logs without failing the whole job). This would enable us to catch regressions, and early detect new features that do not work on Windows.

**Comment by maynardGK** [comment]
For each platform that is built (currently only gcc6.3 platforms can be built and tested on Appveyor) there are several tests from testsuite/test_* that are excluded because they will never pass.
The most problematic are excluded from the testing in Appveyor.yml but some will pass when the artifact is run on a real system.  This latter category is excluded fr4om testing during the Appveyor run via the powershell script located in scripts/ps1/appveyor_skip_tests.ps1.
  The list of non-lethal tests that are mostly runable from a live system using the downloaded artifact, are found in testsuite/app<platform>_skipped.pro, where <platform> is either 630x8664 or 640i686.  These can be run with a simple @<file> command.

**Comment by maynardGK** [comment]
in (169071a) For some reason an exit,status=77 was not invoked from test_python_module_0,
when it should have been:
````
;
if (STRlowCase(!version.os_family) EQ 'windows') then begin
   MESSAGE, /continue, 'Not ready for MSwin, please contribute (!fixme!)'
   exit, status=77
endif

````

**Comment by slayoo** [comment]
I suggest removing test_python_module_*.pro entirely.
This is now tested much more elegantly using pytest with testsuite/python/test-GDL.py

**Comment by maynardGK** [comment]
Notice, now, that i686 caught the exit status 77s and didn't properly skip them for netcdf, simplex, and python.

**Comment by maynardGK** [comment]
continued in #828

**Pull request closed without merging**
