### PR TITLE
removing editline as an alternative to readline

### PR DESCRIPTION
**Pull request by alaingdl**
* It was my mistake long time ago, see discussion in #754 and older bugs reports

* preparing new tests for READS & complex imputs (not ready) #701 

* small update of doc/gdl.1 (man)

* a bug in bench.

* Know issue : on OSX we have be more strict on the way Readline files are detected because OSX SDK and also EditLine are around with interference. TBC.

### CODE REVIEW

**Comment by maynardGK** [comment]
build 1267 of the 64-bit release artifacts in Appveyor tests ok, all except the three 
tests - memory, step, wordexp - which haven't been adapted to windows' environments.
Output from the remaining "filed" tests:
````
GDL> test_scope_varfetch
% Compiled module: TEST_SCOPE_VARFETCH.
    1234
% ASTRON_READCOL1: inside
      0.00000      1.00000      2.00000      3.00000      4.00000      5.00000      6.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL1BIS: inside
      0.00000      1.00000      2.00000      3.00000      4.00000      5.00000      6.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL2: inside
      0.00000      1.00000      2.00000      3.00000      4.00000      5.00000      6.00000
      7.00000      8.00000      9.00000
    1234
% ASTRON_READCOL1: inside
      0.00000      1.00000      2.00000      3.00000      4.00000      5.00000      6.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL1BIS: inside
      0.00000      1.00000      2.00000      3.00000      4.00000      5.00000      6.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL2: inside
      0.00000      1.00000      2.00000      3.00000      4.00000      5.00000      6.00000
      7.00000      8.00000      9.00000
GDL> test_routine_filepath
% Compiled module: TEST_ROUTINE_FILEPATH.
% Compiled module: ROUTINE_NAME.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TH_PRO1234:   NO errors encountered during TH_PRO1234 tests
% Compiled module: ERRORS_CUMUL.
% TH_FUNC1234:   NO errors encountered during TH_FUNC1234 tests
% TH_STRUCT::PROC1:   NO errors encountered during TH_STRUCT::PROC1 tests
% TH_STRUCT::FUNC1:   NO errors encountered during TH_STRUCT::FUNC1 tests
% TEST_ROUTINE_FILEPATH: ==============================================================
% TEST_ROUTINE_FILEPATH: =                                                            =
% TEST_ROUTINE_FILEPATH: =  NO errors encountered during TEST_ROUTINE_FILEPATH tests  =
% TEST_ROUTINE_FILEPATH: =                                                            =
% TEST_ROUTINE_FILEPATH: ==============================================================
GDL> test_readf_with_crlf
% Compiled module: TEST_READF_WITH_CRLF.
%  TEST_READF_WITH_CRLF: ==============================================================
%  TEST_READF_WITH_CRLF: =                                                            =
%  TEST_READF_WITH_CRLF: =  NO errors encountered during  TEST_READF_WITH_CRLF tests  =
%  TEST_READF_WITH_CRLF: =                                                            =
%  TEST_READF_WITH_CRLF: ==============================================================
GDL> test_math_function_dim
% Compiled module: TEST_MATH_FUNCTION_DIM.
all Dims Tests done with SUCCESS for function : BESELI and TYPE : INT
all Dims Tests done with SUCCESS for function : BESELI and TYPE : LONG
all Dims Tests done with SUCCESS for function : BESELI and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : BESELI and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : BESELI and TYPE : COMPLEX
all Dims Tests done with SUCCESS for function : BESELI and TYPE : DCOMPLEX
all Dims Tests done with SUCCESS for function : BESELJ and TYPE : INT
all Dims Tests done with SUCCESS for function : BESELJ and TYPE : LONG
all Dims Tests done with SUCCESS for function : BESELJ and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : BESELJ and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : BESELJ and TYPE : COMPLEX
all Dims Tests done with SUCCESS for function : BESELJ and TYPE : DCOMPLEX
all Dims Tests done with SUCCESS for function : BESELK and TYPE : INT
all Dims Tests done with SUCCESS for function : BESELK and TYPE : LONG
all Dims Tests done with SUCCESS for function : BESELK and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : BESELK and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : BESELK and TYPE : COMPLEX
all Dims Tests done with SUCCESS for function : BESELK and TYPE : DCOMPLEX
all Dims Tests done with SUCCESS for function : BESELY and TYPE : INT
all Dims Tests done with SUCCESS for function : BESELY and TYPE : LONG
all Dims Tests done with SUCCESS for function : BESELY and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : BESELY and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : BESELY and TYPE : COMPLEX
all Dims Tests done with SUCCESS for function : BESELY and TYPE : DCOMPLEX
all Dims Tests done with SUCCESS for function : VOIGT and TYPE : INT
all Dims Tests done with SUCCESS for function : VOIGT and TYPE : LONG
all Dims Tests done with SUCCESS for function : VOIGT and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : VOIGT and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : VOIGT and TYPE : COMPLEX
all Dims Tests done with SUCCESS for function : VOIGT and TYPE : DCOMPLEX
all Dims Tests done with SUCCESS for function : EXPINT and TYPE : INT
all Dims Tests done with SUCCESS for function : EXPINT and TYPE : LONG
all Dims Tests done with SUCCESS for function : EXPINT and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : EXPINT and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : EXPINT and TYPE : COMPLEX
all Dims Tests done with SUCCESS for function : EXPINT and TYPE : DCOMPLEX
all Dims Tests done with SUCCESS for function : GAUSSINT and TYPE : INT
all Dims Tests done with SUCCESS for function : GAUSSINT and TYPE : LONG
all Dims Tests done with SUCCESS for function : GAUSSINT and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : GAUSSINT and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : GAUSSINT and TYPE : COMPLEX
all Dims Tests done with SUCCESS for function : GAUSSINT and TYPE : DCOMPLEX
all Dims Tests done with SUCCESS for function : BETA and TYPE : INT
all Dims Tests done with SUCCESS for function : BETA and TYPE : LONG
all Dims Tests done with SUCCESS for function : BETA and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : BETA and TYPE : DOUBLE
all Dims Tests done with SUCCESS for function : IGAMMA and TYPE : INT
all Dims Tests done with SUCCESS for function : IGAMMA and TYPE : LONG
all Dims Tests done with SUCCESS for function : IGAMMA and TYPE : FLOAT
all Dims Tests done with SUCCESS for function : IGAMMA and TYPE : DOUBLE
% TEST_MATH_FUNCTION_DIM: ===============================================================
% TEST_MATH_FUNCTION_DIM: =                                                             =
% TEST_MATH_FUNCTION_DIM: =  NO errors encountered during TEST_MATH_FUNCTION_DIM tests  =
% TEST_MATH_FUNCTION_DIM: =                                                             =
% TEST_MATH_FUNCTION_DIM: ===============================================================
% TEST_MATH_FUNCTION_DIM: re-run with /verbose for details
GDL> test_la_least_squares
% Compiled module: TEST_LA_LEAST_SQUARES.
% TEST_LA_LEAST_SQUARES: ==============================================================
% TEST_LA_LEAST_SQUARES: =                                                            =
% TEST_LA_LEAST_SQUARES: =  NO errors encountered during TEST_LA_LEAST_SQUARES tests  =
% TEST_LA_LEAST_SQUARES: =                                                            =
% TEST_LA_LEAST_SQUARES: ==============================================================
GDL> test_call_procedure
% Compiled module: TEST_CALL_PROCEDURE.
% BASIC_CALL_PROCEDURE: testing CALL_PROCEDURE: No Errors found
GDL> test_byte_conversion
% Compiled module: TEST_BYTE_CONVERSION.
% TEST_BYTE_BUG_586:   NO errors encountered during TEST_BYTE_BUG_586 tests
% TEST_BYTE_BASIC_32768:   NO errors encountered during TEST_BYTE_BASIC_32768 tests
% TEST_BYTE_BASIC_32768:   NO errors encountered during TEST_BYTE_BASIC_32768 tests
% TEST_BYTE_STRING2BYTE:   NO errors encountered during TEST_BYTE_STRING2BYTE tests
2017-03-11 : First run should be OK in GDL
% TEST_BYTE_WITH_LOOP:   NO errors encountered during TEST_BYTE_WITH_LOOP tests
2017-03-11 : Second run should be BAD in GDL
% TEST_BYTE_WITH_LOOP:   NO errors encountered during TEST_BYTE_WITH_LOOP tests
% TEST_BYTE_CONVERSION: =============================================================
% TEST_BYTE_CONVERSION: =                                                           =
% TEST_BYTE_CONVERSION: =  NO errors encountered during TEST_BYTE_CONVERSION tests  =
% TEST_BYTE_CONVERSION: =                                                           =
% TEST_BYTE_CONVERSION: =============================================================
GDL>
````

**Comment by slayoo** [comment]
Re ``build 1267 of the 64-bit release artifacts in Appveyor tests ok, all except the three``, please note that there are apparently still many tests disabled in appveyor.yml:
https://github.com/gnudatalanguage/gdl/blob/master/appveyor.yml#L199

Namely:
  - test_bug_3300626.pro
  - test_bug_3275334.pro
  - test_bug_3104214.pro
  - test_bug_2876161.pro
  - test_bug_2610174.pro
  - test_bug_1779553.pro
  - test_bug_3376577.pro
  - test_bug_3394430.pro
  - test_bug_3595172.pro
  - test_bug_635.pro
  - test_bug_709.pro
  - test_bug_719.pro
  - test_bug_n000587.pro
  - test_bug_n000608.pro
  - test_bug_n000720.pro
  - test_call_external.pro
  - test_clip.pro
  - test_contour.pro
  - test_delvarrnew.pro
  - test_device.pro
  - test_dicom.pro
  - test_extra_keywords.pro
  - test_file_move.pro
  - test_fixprint.pro
  - test_formats.pro
  - test_fx_root.pro
  - test_fz_roots.pro
  - test_gc.pro
  - test_get_lun.pro
  - test_get_screen_size.pro
  - test_gh00178.pro
  - test_hist_2d.pro
  - test_idlneturl.pro
  - test_indgen.pro
  - test_interpol.pro
  - test_matrix_multiply.pro
  - test_moment.pro
  - test_obj_new.pro
  - test_plot_oo.pro
  - test_plot_ranges.pro
  - test_plot_usersym.pro
  - test_plotting_ranges.pro
  - test_pmulti.pro
  - test_point_lun.pro
  - test_postscript.pro
  - test_ps_decomposed.pro
  - test_python.pro
  - test_image_statistics.pro
  - test_python_module_0.pro
  - test_python_module_1.pro
  - test_python_module_2.pro
  - test_readf.pro
  - test_resolve_routine.pro
  - test_spawn_unit.pro
  - test_systime.pro
  - test_tic_toc.pro
  - test_total.pro
  - test_rounding.pro
  - test_tv.pro
  - test_wait.pro
  - test_window_background.pro
  - test_zip.pro

**Comment by maynardGK** [comment]
If a test fails - cleanly - then it remains in the list to attempt.  But some will hang up the whole process
and those are commented out in the scripts so that they are inactive.  This is the case for the numbered tests and I've run the artifact on several of the remainder:
````
test_dicom.pro  - the example used is too big for the windows build.
test_extra_keywords.pro -** WORKS from home
test_file_move.pro -** WORKS from home
test_fixprint.pro -** WORKS from home
test_formats.pro
test_fx_root.pro -** WORKS from home
test_fz_roots.pro -** WORKS from home
test_gc.pro
test_get_lun.pro
test_get_screen_size.pro
test_gh00178.pro
test_hist_2d.pro -** WORKS from home
test_idlneturl.pro
test_indgen.pro
test_interpol.pro
test_matrix_multiply.pro -** WORKS from home
test_moment.pro -** WORKS from home
test_obj_new.pro -** WORKS from home
test_plot_oo.pro
test_plot_ranges.pro -** WORKS from home
test_plot_usersym.pro
test_plotting_ranges.pro
test_pmulti.pro
test_point_lun.pro
test_postscript.pro
test_ps_decomposed.pro
test_python.pro
test_image_statistics.pro
test_python_module_0.pro
test_python_module_1.pro
test_python_module_2.pro
test_readf.pro -** WORKS from home
test_resolve_routine.pro -** WORKS from home
test_spawn_unit.pro
test_systime.pro
test_tic_toc.pro -** WORKS from home
test_total.pro -** WORKS from home
test_rounding.pro -** WORKS from home
test_tv.pro
test_wait.pro - (parameter fail)
test_window_background.pro =  15 errors encountered during TEST_WIN_BACK_DECOMPOSED 
test_zip.pro
````
see results in #766
test summary for new appveyor run:
````
92% tests passed, 15 tests failed out of 187
Total Test time (real) = 135.09 sec
The following tests FAILED:
	 55 - test_byte_conversion.pro (Exit code 0xc0000374
)
	 59 - test_call_procedure.pro (Exit code 0xc0000374
)
	 74 - test_extra_keywords.pro (Exit code 0xc0000374
)
	108 - test_la_least_squares.pro (Exit code 0xc0000374
)
	113 - test_math_function_dim.pro (Exit code 0xc0000374
)
	114 - test_matrix_multiply.pro (Exit code 0xc0000374
)
	115 - test_memory.pro (Failed)
	143 - test_readf_with_crlf.pro (Exit code 0xc0000374
)
	146 - test_resolve_routine.pro (Exit code 0xc0000374
)
	149 - test_routine_filepath.pro (Exit code 0xc0000374
)
	153 - test_scope_varfetch.pro (Exit code 0xc0000374
)
	162 - test_step.pro (Failed)
	179 - test_wait.pro (Failed)
	182 - test_wordexp.pro (Failed)
	184 - test_xdr.pro (Exit code 0xc0000374
)
````

**Comment by slayoo** [comment]
Thanks for looking into it!
BTW, it would super super great to make Appveyor fail on failed tests and failed builds (#615)

**Pull request merged**
