### PR TITLE
Win build: Revise appveyor build for windows

### PR DESCRIPTION
**Pull request by maynardGK**
GDL is built in appveyor using mingw-w64 compiler and support libraries built with this
    compiler.   The  scripts/appveyor_1.msys sequence obtains those, pre-built, needed from the msys repository.    Some of these repository distros have been found to not be compatible with the appveyor build - for whatever reason, readilne/pcre has been restricted to the readline5 of win32libs and pcre7 also of that source.  So, "version upgrades" need to be tested methodically.
      wxwidgets and graphicsmagick are the next two behemoth support libraries to be integrated.
    The CMakelists.txt script is modified to survive the absence of these libraries, so that
    the build command need not be changed to adjust the build.
    Also, an entry for the plplot-driver selector USE_WINGDI_NOT_WINGCC allow the wingdi.dll
    device to be used - improvements in axis and labelling will be noticed, but there is
     still no anti-alias in the plot line.

### CODE REVIEW

**Comment by maynardGK** [comment]
Sourceforge is quite iffy tonight but the release version came out ok: no widgets, fft, or Magick.

**Comment by maynardGK** [comment]
sourceforge server is messed up. trying a different http address on sourceforge

**Comment by maynardGK** [comment]
fails Exit code 0xc0000135 when fftw, graphicksmagick brought in.

**Comment by maynardGK** [comment]
another SF download failure
switch out now the 6.3.0 compiler for 5.3.0, which I have on home computer.
-- Could NOT find GRAPHICSMAGICK (missing: GRAPHICSMAGICK_LIBRARIES GRAPHICSMAGICK_INCLUDE_DIR) 
-- GRAPHICSMAGICK was requested but was not found. MAGICK=OFF set.
        Use -DGRAPHICSMAGICKDIR=DIR to specify the GraphicsMagick directory tree.
        Use -DGRAPHICSMAGICK=OFF to not use it.
                (suitable Fedora package: GraphicsMagick-c++-devel
           Debian/Ubuntu package: libgraphicsmagick++1-dev)
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS) 
-- wxWidgets are requested but were not found.
Use -DWXWIDGETSDIR=DIR to specify the wxWidgets directory tree.
(suitable Debian/Ubuntu package: libwxgtk2.8-dev)
(suitable Fedora package: wxGTK-devel)
-- Use -DWXWIDGETS=OFF to not use it.
 proceeding with WXWIDGETS=OFF 
-- libtiff v4.0.3 or newer is required for TIFF support but was not found.
Use -DTIFFDIR=DIR to specify the libtiff directory tree.
Use -DTIFF=OFF to not use it.
-- FFTW3 is requested but was not found.
Use -DFFTWDIR=DIR to specify the FFTW directory tree.
Use -DFFTW=OFF to not use it. (set for this build)
(suitable Debian/Ubuntu package: libfftw3-dev)
(suitable Fedora package: fftw-devel)

**Comment by maynardGK** [comment]
Failing with Exception: Exit code 0xc0000135

**Comment by slayoo** [comment]
@maynardGK please just pull from gnudatalanguage/gdl master into your win_build branch, and commit -> should fix the conflict, I really don't think there is any access restriction issue - you have more rights to the win_build branch then anyone else :)

**Comment by maynardGK** [comment]
100 more times and I'll have this down :)

**Comment by slayoo** [comment]
Greg, please note that after uncommenting the last two lines in appveyor.yml (the on_finish block), you can simply log in to the vm and experiment interactively. HTH, Sylwester

**Comment by maynardGK** [comment]
Appveyor #497, contains a large artifact dump of win32libs and mingw (from f334eaec).  Also, 
the "mingw32-make check" was skipped to be sure it didn't bomb out before the artifact could be made.
to run, the *.dll files from install/gdl/bin/gcc_dll directory need to be copied or moved to install/gdl/bin.
This will be done from here on as follows:
  - ps: copy -r C:/projects/gdl/win32libs/wxWidgets-3.0.4/lib/gcc_dll c:\projects\gdl\install\gdl\bin
  - ps: move  ./install/gdl/bin/gcc_dll/*.dll ./install/gdl/bin
  - ps: rm -r ./install/gdl/bin/gcc_dll
  - cd c:\projects\gdl
  - 7z a gdl_build.zip install

Because plplot never hooks into wxwidgets, there are no wxwidgets plplot drivers even though GDL
thinks there are: as soon as the 'MAC' plot device is tried it will crash out.  Also, regular plot windows 
are sick; this is not a condition in build 484 which has no wxwidgets built in.  This behavior is typical but has been purged in my home builds (which use MSYS2 and include the other improvements).

**Comment by maynardGK** [comment]
commit ae9d753 works well from explorer, not from a CMD shell - except one running bash.
GraphicsMagick is 8 bits as it comes from MSYS2 pacman, which creates a problem for some test routines.
Any tests which use SPAWN will usually be bad for win32, although run from an msys shell survives a lot of them.

**Comment by maynardGK** [comment]
After commit 598aadf we got this result from :make check":
[00:10:26] The following tests FAILED:
[00:10:26] 	 67 - test_file_copy.pro (SEGFAULT)
[00:10:26] 	 70 - test_file_lines.pro (SEGFAULT)
[00:10:26] 	 71 - test_file_move.pro (SEGFAULT)
[00:10:26] 	 73 - test_file_test.pro (SEGFAULT)
[00:10:26] 	 74 - test_file_which.pro (SEGFAULT)
[00:10:26] 	 75 - test_get_lun.pro (SEGFAULT)
[00:10:26] 	 93 - test_obj_isa.pro (SEGFAULT)
[00:10:26] 	 95 - test_obj_valid.pro (SEGFAULT)
[00:10:26] 	 98 - test_ptr_valid.pro (SEGFAULT)
So I will revert the exclusion list to include these.

**Comment by maynardGK** [comment]
In commit 24b3933 the build was allowed to proceed to the "make check" whereupon it failed on a 
single test, test_file_search.  
the error:
% TEST_FULLY_QUALIFY_PATH: Error on operation : pb with N_elements RES1
is due to how GDL is run, without a bash shell underneath it.
Also, test_bug_635 shold work.

**Comment by maynardGK** [comment]
Hanging on CMake invocation from CMD.exe script.

**Comment by SIAMAR** [comment]
hello @maynardGK 
with @sflinois we are trying out your PR and we found that Help,/Path doesn't work when the path is valid and we add an #ifdef for win32 and that work fine. Do you want us to make a PR to your fork so you can check it out ?
Thank you

**Comment by maynardGK** [comment]
@SIAMAR That just a bug in the routine (maybe sysvar::GDLPath()) so create an issue for it.  It is unusual to have a platform-specific bug!

**Comment by maynardGK** [comment]
@slayoo  This was ready to go anyway, but I accidentally created the hashlist_prep branch coming off of this win_build. -???

**Comment by slayoo** [comment]
Thanks @maynardGK! It seems that this PR does not feature test execution or Debug/Release builds (both of which are there in the current appveyor.yml file) - is it intentional?

**Comment by maynardGK** [comment]
@slayoo I am re-doing this PR to be a single commit (so we don't have 100 trivial commits).
The tests will be back but failure will not trash the test now - when it builds but doesn't have a library it is helpful to dowload an artifact and run it through a WIN system which will tell you what's missing.  Doing just release to save time, still needs more progress to build graphicksmagick at 32-bits.

**Comment by slayoo** [comment]
@maynardGK multiple commits are fine - we can just squash when merging.
On the other hand, not failing a build with failed tests will render the CI incapable of noticing us of regressions. Perhaps we could make failures failures on Release builds and make them not err the build for Debug ones - this way a red flag would be transmitted to github, but one could still download the Debug artifact to debug?

**Comment by maynardGK** [comment]
Ok I'll stop doing the transfer and we can leave it all in the hashlist PR #431 , which contains this and re-inserts tests - but don't squash the two hash/list commits at the end.

**Comment by maynardGK** [comment]
I tried to squash a subset at home, but it didn't work out like I expected
so I will leave it alone,
PR 431 has everything PR 408 had plus the hash/list upgrade.  I was able to
reset the travis build and the appveyor run
creates a release version - much smaller (32 MB) than the Debug variant
(110 MB).  The test_bug_635 was failing even after
I "fixed" it to find the file it needed (it does work ok at home).

I'm afraid that if the CMD build script (mingw-bldgdl.bat) does exit with a
non-zero exit code, then it hangs the appveyor script
so you will simply get a 1-hour delay if the release is being built at that
time.  Perhaps a CALL will behave better instead of CMD /K

**Pull request closed without merging**
