### PR TITLE
Update FILE_MKDIR to create a missing directory path 

### PR DESCRIPTION
**Pull request by maynardGK**
Previously FILE_MKDIR simply called the library "mkdir" and didn't worry about it.
Now, the command "mkdir -p" is emulated to create intervening directories that may not
have existed.  
Errors that may occur, such as trying to create a directory with a pre-existing name, or failing to create directories, generate a message to stdout but otherwise pass.  
  test_file_mkdirs.pro is added to testsuite.

### CODE REVIEW

**Comment by slayoo** [comment]
failures should make file_mkdir fail:
```
IDL> file_mkdir, '/dev/aqq'
% FILE_MKDIR: Unable to create directory: /dev/aqq
  Permission denied
% Execution halted at: $MAIN$  
```

trying to create an existing one is OK:
```
IDL> file_mkdir, '/tmp'
IDL> 
```

**Comment by maynardGK** [comment]
Thank you for that. I'm having trouble generating an error I can catch in the test routine. 
What does the following produce in IDL?:

````
afile = 'aaafile'
if file_test(afile) eq 0 then begin &$
  openw,/get_lun,lu,'./aaafile' & free_lun,lu & endif

catch, mkdir_err
if mkdir_err ne 0 then begin &$
  catch,/cancel & print,' oops' & endif $
  else $
file_mkdir,afile

````

OK, nevermind, I thought I'd see the message when I caught it in the script but it doesn't show.

````
In File.cpp file_mkdir(Envt* e)
 ...
           if( isaDir) continue;
//            std::cout << " File_mkdir error: a file (not directory) already exists:"<<tmp<<std::endl;
            throw GDLException(  " a file (not directory) already exists:"+tmp);

````

**Comment by maynardGK** [comment]
@slayoo I'm done with this, now - could you please push it back into master?

**Comment by slayoo** [comment]
Why the testsuite/launchtest.c file is removed in this PR?

**Comment by maynardGK** [comment]
> Why the testsuite/launchtest.c file is removed in this PR?

I don't ever edit this but it shows up now in my "untracked" list of files, now modified for my system here:
````
_putenv("GDL_PATH=F:/github/gdlgit/testsuite/;F:/github/gdlgit/src/pro/");
char *tmp = (char *)malloc( sizeof(char) * (strlen("D:/bld/gdl/mingw32-git/src/gdl -quiet -e ") + strlen(v[1]) + 1));

````
I've retrieved the original and pushed it

**Comment by maynardGK** [comment]
1) New Ubuntu version used is 16.04 and does not have libwx2.8, evidently.  Try libwx3.0.
2) Imagemagick version 5 has been used in the old (working) system.  New system uses libmagick version  6 and version 7 is current which will need some re-working of GDL source.

Build 952 (from pr #592 ) passes all tests in travis, 
   including test_fx_root which the new builds are failing at.  
   (Windows builds fail this test also, at same place.)

On OSX, the new clang is not happy trying to use C++17 on the code.

**Comment by maynardGK** [comment]
"-Wdeprecated-register" flag stifles C++17 complaints ion the case of homebrew/py2.7

@GillesDuvert The travis build using wx 3.0.2 is having difficulties in (gcc) debug mode.  Previously working travis builds used wx 2.8.12, no longer a viable download.
````
04:36:52: Error: Unable to initialize GTK+, is DISPLAY set properly?
WARNING: wxWidgets not initializing
% Compiled module: TEST_WINDOW_BACKGROUND.
% Compiled module: ROUTINE_NAME.
% Compiled module: CHECK_IF_DEVICE_IS_OK.
requesting GetDecomposed() on unexistent window 
% TEST_WIN_BACK_DECOMPOSED: PLplot installation lacks the requested driver: xwin
% Execution halted at: TEST_WIN_BACK_DECOMPOSED   205 /home/travis/build/gnudatalanguage/gdl/testsuite/test_window_background.pro
%                      TEST_WINDOW_BACKGROUND   205 /home/travis/build/gnudatalanguage/gdl/testsuite/test_window_background.pro
%                      $MAIN$          
````
I attempted to fix the nullgdl:: complaint, in icc, with overloaded delete functions, to no avail.

**Comment by slayoo** [comment]
@maynardGK please do try next time to split unrelated changes into multiple branches and PRs (here we have file_mkdir, Travis/Wx/OSX, fx_roots, various whitespace cleanups, and more...)

Thanks!

**Pull request merged**
