### PR TITLE
 include a posix option for windows' operation from a posix shell.

### PR DESCRIPTION
**Pull request by maynardGK**
Normally the file specification under windows is a mixed bag: the forward slash
is acceptable usage but the backslash is always present.  Under Unix, however, a backslash
disappears under normal shell operation - it is a special character in the posix shell.
For Instance, when running GDL from an MSYS2/cygwin posix shell, the user cannot use the
file reported by GDL without manually editing the string.
 For that reason much of the file_search output included the conversion to unix-style, (posix)
allowing inter-operation on common file systems, i.e. an NTFS disk can be mounted under
Linux and operated with as if it were another native-linux filesystem.  Nevertheless this
conflicts with standard windows' usage and IDL behavior.

 To allow for posix file output in GDL a "posixpaths" logical was created which can be set to
 "true" when run from windows

 1) by invoking the command-line argument "--posix" at startup.
 2)  A backdoor way

The system variable !GDL has been modified with a !GDL.GDL_POSIX variable to reflect this
 condition, it will be set =1 for any non-Win32 run and when run under Win32 with --posix.
Procedure PATH_SEP() uses this to provide a correct character- precautions have been made to
 side-step usage of !GDL.GDL_POSIX if it does not exist (an earlier GDL version, or IDL
  may be running the procedure).
If the backdoor way is used to set the logical, !GDL will remain unchanged.

### CODE REVIEW

**Comment by maynardGK** [comment]
After downloading the artifact and running it directly on my system, the tests that show failure passed:

````
$ ls
bld1041.ls  build/  install/

greg@Homerw7  /f/github/gdl64
$ cd ~

greg@Homerw7  ~
$ gdl64
% WARNING: your version of the GraphicsMagick library will truncate images to 8 bits per pixe

  GDL - GNU Data Language, Version 0.9.9 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > thi
() (which is 0)
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > thi
() (which is 0)
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > thi
() (which is 0)
GDL> test_file_which
% Compiled module: TEST_FILE_WHICH.
% Compiled module: FILE_WHICH.
% TEST_FILE_WHICH:  run from a non-production location (no ../src/gdl found)
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FILE_WHICH: ========================================================
% TEST_FILE_WHICH: =                                                      =
% TEST_FILE_WHICH: =  NO errors encountered during TEST_FILE_WHICH tests  =
% TEST_FILE_WHICH: =                                                      =
% TEST_FILE_WHICH: ========================================================
GDL> test_routine_filepath
% Compiled module: TEST_ROUTINE_FILEPATH.
% Compiled module: ROUTINE_NAME.
% TH_PRO1234:   NO errors encountered during TH_PRO1234 tests
% Compiled module: ERRORS_CUMUL.
% TH_FUNC1234:   NO errors encountered during TH_FUNC1234 tests
% TH_STRUCT::PROC1:   NO errors encountered during TH_STRUCT::PROC1 tests
% TH_STRUCT::FUNC1:   NO errors encountered during TH_STRUCT::FUNC1 tests
% TEST_ROUTINE_FILEPATH: ==============================================================
% TEST_ROUTINE_FILEPATH: =                                                            =
% TEST_ROUTINE_FILEPATH: =  NO errors encountered during TEST_ROUTINE_FILEPATH tests  =
% TEST_ROUTINE_FILEPATH: =                                                            =
% TEST_ROUTINE_FILEPATH: ==============================================================
GDL> test_scope_varname
% Compiled module: TEST_SCOPE_VARNAME.
% TH_PROC1:   NO errors encountered during TH_PROC1 tests
% TH_FUNC1:   NO errors encountered during TH_FUNC1 tests
% TEST_SCOPE_VARNAME: ===========================================================
% TEST_SCOPE_VARNAME: =                                                         =
% TEST_SCOPE_VARNAME: =  NO errors encountered during TEST_SCOPE_VARNAME tests  =
% TEST_SCOPE_VARNAME: =                                                         =
% TEST_SCOPE_VARNAME: ===========================================================
GDL> help,/sour
Compiled Procedures:
$MAIN$
BANNER_FOR_TESTSUITE     F:\github\gdlgit\testsuite\banner_for_testsuite.pro
ERRORS_CUMUL             F:\github\gdlgit\testsuite\errors_cumul.pro
TEST_FILE_WHICH          F:\github\gdlgit\testsuite\test_file_which.pro
TEST_ROUTINE_FILEPATH    F:\github\gdlgit\testsuite\test_routine_filepath.pro
TEST_SCOPE_VARNAME       F:\github\gdlgit\testsuite\test_scope_varname.pro
TH_PRO1234               F:\github\gdlgit\testsuite\test_routine_filepath.pro
TH_PROC1                 F:\github\gdlgit\testsuite\test_scope_varname.pro

Compiled Functions:
FILE_WHICH               F:\github\gdlgit\src\pro\file_which.pro
GDL_IDL_FL               F:\github\gdlgit\testsuite\gdl_idl_fl.pro
ISA_IDL                  F:\github\gdlgit\testsuite\banner_for_testsuite.pro
ISA_INTERNAL             F:\github\gdlgit\testsuite\banner_for_testsuite.pro
PATH_SEP                 D:\home\greg\gdlpro\new\path_sep.pro
ROUTINE_NAME             F:\github\gdlgit\src\pro\utilities\routine_name.pro
TH_FUNC1                 F:\github\gdlgit\testsuite\test_scope_varname.pro
TH_FUNC1234              F:\github\gdlgit\testsuite\test_routine_filepath.pro
GDL> exit

greg@Homerw7  ~
````
 now in posix mode:

````
greg@Homerw7  ~
$ bash -c "export PATH=.:$PATH && /f/github/gdl64/install/gdl/bin/gdl --posix
> "
% WARNING: your version of the GraphicsMagick library will truncate images to 8 bits per pi

  GDL - GNU Data Language, Version 0.9.9 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > t
() (which is 0)
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > t
() (which is 0)
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > t
() (which is 0)
GDL> !gdl
{ 0.9.9 git Sep 21 2019  1569049200   0   0   1 CRUDE}
GDL> help,!gdl
<Expression>    STRUCT    = -> !GNUDATALANGUAGE Array[1]
** Structure !GNUDATALANGUAGE, 7 tags,memsize =104, data length=32/32:
   RELEASE         STRING    '0.9.9 git'
   BUILD_DATE      STRING    'Sep 21 2019'
   EPOCH           LONG        1569049200
   GDL_NO_DSFMT    BYTE         0
   GDL_USE_WX      BYTE         0
   GDL_POSIX       BYTE         1
   MAP_QUALITY     STRING    'CRUDE'
GDL> test_file_which
% Compiled module: TEST_FILE_WHICH.
% Compiled module: FILE_WHICH.
% TEST_FILE_WHICH:  run from a non-production location (no ../src/gdl found)
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FILE_WHICH: ========================================================
% TEST_FILE_WHICH: =                                                      =
% TEST_FILE_WHICH: =  NO errors encountered during TEST_FILE_WHICH tests  =
% TEST_FILE_WHICH: =                                                      =
% TEST_FILE_WHICH: ========================================================
GDL> test_routine_filepath
% Compiled module: TEST_ROUTINE_FILEPATH.
% Compiled module: ROUTINE_NAME.
% TH_PRO1234:   NO errors encountered during TH_PRO1234 tests
% Compiled module: ERRORS_CUMUL.
% TH_FUNC1234:   NO errors encountered during TH_FUNC1234 tests
% TH_STRUCT::PROC1:   NO errors encountered during TH_STRUCT::PROC1 tests
% TH_STRUCT::FUNC1:   NO errors encountered during TH_STRUCT::FUNC1 tests
% TEST_ROUTINE_FILEPATH: ==============================================================
% TEST_ROUTINE_FILEPATH: =                                                            =
% TEST_ROUTINE_FILEPATH: =  NO errors encountered during TEST_ROUTINE_FILEPATH tests  =
% TEST_ROUTINE_FILEPATH: =                                                            =
% TEST_ROUTINE_FILEPATH: ==============================================================
GDL> help,/sour
Compiled Procedures:
$MAIN$
BANNER_FOR_TESTSUITE     F:/github/gdlgit/testsuite/banner_for_testsuite.pro
ERRORS_CUMUL             F:/github/gdlgit/testsuite/errors_cumul.pro
TEST_FILE_WHICH          F:/github/gdlgit/testsuite/test_file_which.pro
TEST_ROUTINE_FILEPATH    F:/github/gdlgit/testsuite/test_routine_filepath.pro
TH_PRO1234               F:/github/gdlgit/testsuite/test_routine_filepath.pro

Compiled Functions:
FILE_WHICH               F:/github/gdlgit/src/pro/file_which.pro
GDL_IDL_FL               F:/github/gdlgit/testsuite/gdl_idl_fl.pro
ISA_IDL                  F:/github/gdlgit/testsuite/banner_for_testsuite.pro
ISA_INTERNAL             F:/github/gdlgit/testsuite/banner_for_testsuite.pro
PATH_SEP                 D:/home/greg/gdlpro/new/path_sep.pro
ROUTINE_NAME             F:/github/gdlgit/src/pro/utilities/routine_name.pro
TH_FUNC1234              F:/github/gdlgit/testsuite/test_routine_filepath.pro
GDL> test_scope_varname
% Compiled module: TEST_SCOPE_VARNAME.
% TH_PROC1:   NO errors encountered during TH_PROC1 tests
% TH_FUNC1:   NO errors encountered during TH_FUNC1 tests
% TEST_SCOPE_VARNAME: ===========================================================
% TEST_SCOPE_VARNAME: =                                                         =
% TEST_SCOPE_VARNAME: =  NO errors encountered during TEST_SCOPE_VARNAME tests  =
% TEST_SCOPE_VARNAME: =                                                         =
% TEST_SCOPE_VARNAME: ===========================================================
GDL>
````

**Comment by GillesDuvert** [comment]
Many thaks @maynardGK 
Looks a good answer to the cygwin use, as the posix shell under windows is something unknown to IDL, no generic solution can be mimicked. Enabling this is mandatory I guess as soon we merge #627 .
This is a windows-only (#ifdef _WIN32) patch, yes?
Would it be possible to deduce the use of a POSIX shell (from env. variables) and avoid the --posix at all?

**Comment by maynardGK** [comment]
(This PR overrides #627)
I've enclosed everything in #ifdef except for the variable in !GDL.GDL_POSIX, set to 1 in the not-windows cases. So the not-windows code isn't even touched by the external variable posixpaths.

  Cygwin itself should look like actual unix these days - I doubt WIN32 is even set in that case.
 From GDL I still specify files with F:/ or D:/ whereas in the shell I would use /f/ and /d/ (without directory entries) which are internally tracked.  The F:/ usage is also acceptable to the cygwin (which is the MSYS2) shell.
In MSYS2 (and in a cygwin shell over windows with {cygwin}/usr in path) one can do the following:
````
GDL> spawn,'cygpath -w /',output
GDL> print,output
C:\msys64\
GDL> spawn,'cygpath -w /f',output
GDL> print,output
F:\
```` 
when run from a Win/command shell (or another posix shell which doesn't have a cygpath) then "output" will be ("").

**Comment by maynardGK** [comment]
Re-submitted as PR #654

**Pull request closed without merging**
