### PR TITLE
Patching #343 and #345

### LINKED ISSUE #343: warning: 'register' storage class specifier is deprecated and incompatible with C++1z
```
basic_fun.cpp:4063:11: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
          ELEM_SWAP(array[ll], array[hh])
          ^
/Users/travis/build/slayoo/gdl/src/basic_fun.cpp:4026:26: note: expanded from macro 'ELEM_SWAP'
#define ELEM_SWAP(a,b) { register DFloat t=(a);(a)=(b);(b)=t; }
                         ^
```

### PR DESCRIPTION
**Pull request by rexso**
This PR should fix #343 and #345.

### CODE REVIEW

**Comment by slayoo** [comment]
@GillesDuvert Gilles, any concerns about removing the register thing?

**Comment by rexso** [comment]
Nothing to worry about :smile_cat: 

According to the C++ standard, section *7.1.1, Storage class specifiers*:
> A register specifier is a hint to the implementation that the variable so declared will be heavily used. [Note: The hint can be ignored and in most implementations it will be ignored if the address of the variable is taken. This use is deprecated (see D.2). —end note]

The reality is that modern C++ compilers completely ignore this hint, and many of them always did. Since C++11 this specifier has been *deprecated*, and it has been *removed* since C++17.

Even if you could find a compiler that actually honours this hint and is not capable of doing such optimisations automatically, worst case scenario would be a time penalty no one would ever notice.

**Comment by rexso** [comment]
Travis job 9 timed out? :open_mouth: 
False positive?

**Comment by slayoo** [comment]
restarted!

**Comment by rexso** [comment]
What is the implication of the failing codecov/patch check?

**Comment by slayoo** [comment]
no implication, just a hint that the code patched is not yet executed anywhere in the testsuite :(

**Comment by rexso** [comment]
Ah, I see.. Thank you for the clarification.
At least the compiler output should be a bit nicer with this patch though :smile_cat:

**Comment by GillesDuvert** [comment]
yes, register is ignored by compilers. No worry.

**Pull request merged**
