### PR TITLE
merge changes by Maynard and me

### PR DESCRIPTION
**Pull request by alaingdl**
unclear why this is a new PR :(

### CODE REVIEW

**Comment by alaingdl** [comment]
the problem within MSwin remained the same but the way we try to correct was a mess (you and me loose time). Let's try to merge then to solve it later. Sorry @maynardGK

**Comment by maynardGK** [comment]
When you merged your stuff onto #753 it un-did what I did for terminfo.  So #756 takes that result and branches, adding a _WIN32 version of get_kbrd() and removing all "#ifndef _WIN32" references in the code that brings in readline.h.

**Comment by alaingdl** [comment]
Sorry for that, I follow some instructions provided by the system. At the end I was lost :(

**Comment by alaingdl** [comment]
hon ca I do ?

**Pull request merged**
