### PR TITLE
 Patch 3 tests: file_lines, size, file_test

### PR DESCRIPTION
**Pull request by maynardGK**
Test_file_lines - now finds the oldest procedure in src/pro to count lines.
 test_size       - looks at size array for hashes and lists.
 test_file_test  - now recognizes the improbability of creating links in windows, but
  will do it if you try hard. And it succeeds!

### CODE REVIEW

**Comment by slayoo** [comment]
Appveyor logs:

```
93/101 Testing: test_size.pro
93/101 Test: test_size.pro
Command: "C:/projects/gdl/build/testsuite/launchtest.exe" "test_size.pro"
Directory: C:/projects/gdl/build/testsuite
"test_size.pro" start time: Jun 21 09:15 Coordinated Universal Time
Output:
----------------------------------------------------------
% Compiled module: TEST_SIZE.
The following message is OK
% TEST_BUG_675: Out of range subscript encountered (dimension of insert exceeds array boundaries for dimension 2).
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_BUG_675:   NO errors encountered during TEST_BUG_675 tests  
% Compiled module: ERRORS_CUMUL.
% TEST_SIZE_STRUCTURE: ===================================
% TEST_SIZE_STRUCTURE: =                                 =
% TEST_SIZE_STRUCTURE: =  missing code, please fix it !  =
% TEST_SIZE_STRUCTURE: =                                 =
% TEST_SIZE_STRUCTURE: ===================================
% TEST_SIZE_ARRAY: begin of test
Circulating (shift) on dims : 
       1       2       3
       4
% TEST_SIZE_ARRAY:   NO errors encountered during TEST_SIZE_ARRAY tests  
% TEST_SIZE_ARRAY: begin of test
Circulating (shift) on dims : 
       1       1       1
       1       1
% TEST_SIZE_ARRAY:   NO errors encountered during TEST_SIZE_ARRAY tests  
% TEST_SIZE_ARRAY: begin of test
Circulating (shift) on dims : 
       1      10       1
      10       1
% TEST_SIZE_ARRAY:   NO errors encountered during TEST_SIZE_ARRAY tests  
% Compiled module: ERRORS_ADD.
% TEST_SIZE_HASH: Error on operation :  size(object array)  wrong
% TEST_SIZE_LIST: Error on operation :  size(object array)  wrong
% TEST_SIZE: =================================================
% TEST_SIZE: =                                               =
% TEST_SIZE: =  2 errors encountered during TEST_SIZE tests  =
% TEST_SIZE: =                                               =
% TEST_SIZE: =================================================
<end of output>
Test time =   0.12 sec
----------------------------------------------------------
Test Failed.
```

**Comment by maynardGK** [comment]
@slayoo @GillesDuvert would you please check on what IDL says about this, it came out accidentally like this because, in my own code, I had separated the structure creation from the main routine and took
struct.n _elements = p0->N_Elements(). So when I saw it come as typename="OBJREF', n_elements=1 it made sense, and I kept the answer "1" in the test.  But the git code returns nEl =HASH_count() - probably the correct answer.

**Comment by maynardGK** [comment]
7/191 Testing: test_file_test.pro
97/191 Test: test_file_test.pro
Command: "/home/travis/build/gnudatalanguage/gdl/build/testsuite/launchtest" "test_file_test.pro"
Directory: /home/travis/build/gnudatalanguage/gdl/build/testsuite
"test_file_test.pro" start time: Jun 21 22:50 UTC
Output:
----------------------------------------------------------
% Compiled module: TEST_FILE_TEST.
Error on operation : file is considered as Dir.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FILE_TEST: ======================================================
% TEST_FILE_TEST: =                                                    =
% TEST_FILE_TEST: =  1 errors encountered during TEST_FILE_TEST tests  =
% TEST_FILE_TEST: =                                                    =
% TEST_FILE_TEST: ======================================================
<end of output>
Test time =   0.05 sec
----------------------------------------------------------
Test Failed.
"test_file_test.pro" end time: Jun 21 22:50 UTC
"test_file_test.pro" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by maynardGK** [comment]
Previous travis build had all passes except for 1 test_file_test mistook a file for a directory.
I added a new test_list which goes a bit further while still skipping legacy shortcomings; hopefully the
new travis build will go without a fail. Here are the results of "make check" on the opensuse leap 42 build:
98% tests passed, 5 tests failed out of 214

Total Test time (real) = 135.15 sec

The following tests FAILED:
         94 - test_fft_leak.pro (Failed)
        144 - test_n_tags.pro (Failed)
        177 - test_resolve_routine.pro (Failed)
        179 - test_rounding.pro (Failed)
        201 - test_total.pro (Failed)
Errors while running CTest

**Review by GillesDuvert — COMMENTED** [review]
@maynardGK in test_files_lines.pro, I would not use "swap_endian.pro" for test as this file can be modified, for good reasons (including writing the function in C++ for efficiency). It is probably best to have a fixed test file in the testsuite directory, eventually one generated on the fly.

**Comment by GillesDuvert** [comment]
test_size, as it is here, passes with IDL. test_list has a problem:
```
 IDL> test_list
% Variable is undefined: ISGIT.
```
which prevents checking its compliance.
test_file_test does not pass also.
```
IDL> test_file_test
% FILE_DELETE: Unable to delete file. File: testSymlinkDirectory_for_FILE_TEST
  No such file or directory
% Execution halted at: TEST_FILE_TEST     47 /tmp/test_file_test.pro
%                      TEST_LIST         101 /tmp/test_list.pro
%                      TEST_LIST         101 /tmp/test_list.pro
%                      $MAIN$   
```

**Comment by maynardGK** [comment]
test_file_test now (from MSYS):
GDL> tdirsym='testSymlinkDirectory_for_FILE_TEST' & spawn,'touch '+tdirsym
GDL> test_file_test,/verbose
...
% TEST_FILE_TEST: =  NO errors encountered during TEST_FILE_TEST tests  =
...
without administrator privileges:
GDL> test_file_test,/verbose
...
% TEST_FILE_TEST: =  5 errors encountered during TEST_FILE_TEST tests  =
greg@Homerw7  ~

26-June: A new appveyor.yml has been added, modification of FindPCRE.cmake, and a dummy file_link.pro in the last commit.  Appveyor tests complete in under 20 minutes. Travis tests pass (1 error for gcc download problem).

**Comment by slayoo** [comment]
I guess we should report the plplot patches upstream, opening a ticket for it: https://github.com/gnudatalanguage/gdl/issues/405

**Comment by maynardGK** [comment]
@slayoo the failing travis build is the one that includes codecov.  It looks like "make -j 2" instead of "make -j2" may be the problem.

**Comment by slayoo** [comment]
@maynardGK thanks for info. The problem is elsewhere: https://github.com/bilke/cmake-modules/pull/29/files#diff-d282063ecb3b250e4b08eacf854f94a6L130
There was a change of the CMake macro name there, will submit a PR in a moment

**Comment by slayoo** [comment]
Should be fixed: https://github.com/gnudatalanguage/gdl/commit/f3b6e012ff645c93268cfb9da7f61792630c34ee
Please pull new .travis.yml from master to make it work here
Thanks again

**Comment by maynardGK** [comment]
sourceforge issue?

**Comment by maynardGK** [comment]
Travis test restarted, 1 test failure in one of the 10 builds.  restarted.
test_file_test can give error: "file is considered as Dir."
at apparently random points.

Whoops I restarted th elot of them. Now 572.1 is ok but the icc jobs are getting internet problems:
"Unable to connect to Intel(R) Software Development Products Registration Center"

**Comment by maynardGK** [comment]
This stuff is rolled up into #431

**Pull request closed without merging**
