### PR TITLE
use the general library whereami for getting the path of the excutable on all platforms.

### PR DESCRIPTION
**Pull request by GillesDuvert**
Blind test.

### CODE REVIEW

**Comment by alaingdl** [comment]
Thanks ! Tested (yes 32 cores ;) just now with **success** on 3 configurations : debian 10 + script, debian 10 + cmake + cmake_install_path  and OSX + script

Sorry but my VM with a BSD system is down now (TBC tomorrow ?) Better to have feedback from @thierry-FreeBSD and others ! Thanks !

**Comment by slayoo** [comment]
@GillesDuvert, let's perhaps use a git submodule (https://git-scm.com/book/en/v2/Git-Tools-Submodules) for bringing in the `whereami` files into `gdl`. This will make updates easier as it will be clear which revision of which repo we point to. From the point of view of compilation, nothing changes. It's just that when cloning gdl repo, one will need to do `git clone --recurse-submodules` instead of `git clone`. Thanks

**Comment by GillesDuvert** [comment]
Yes I knew about submodules and tried it but did wrong, hence the first failure in compilation in this PR, because the whereami folder did not propagate into github correclty.
Unfortunately I only use NetBeans for all the git stuff. Apparently it does not understand submodules, hence my problem.
I'm very marginally interested in a solution that would force me to use a git line command externally to NetBeans each time I make a git push/pull etc...

**Comment by slayoo** [comment]
@GillesDuvert, this should help to include the submodules while checking out for CI: https://github.com/gnudatalanguage/gdl/pull/1482

**Pull request merged**
