### PR TITLE
Linkimage

### PR DESCRIPTION
**Pull request by hillbergt**
Re-implementing linkimage, and also adding unlinkimage & unlinksymbol.
The old implementation had a hardcoded limit of 20 procedures/functions and also did not do cleanup or supported keywords.
The new linkimage accepts the keywords FUNCT, MIN_ARGS, MAX_ARGS (with the same meaning as the IDL version) and "KEYWORDS", which is a string-array listing the allowed keywords to pass to the routine/function. N.B. IDL does *not* use "KEYWORDS" this way (because they can resolve the keywords at execution-time).
This new implementation unlinks the DLLs when either the last symbol is unlinked, or unlinkimage (or .FULL_RESET_SESSION) is called.
Now you can do e.g.:
linkimage, 'func_name', 'dll-path', /FUNCT, MIN_ARGS=0, MAX_ARGS=1, KEYWORDS=['HELP','MY_KEY1']
linkimage, 'proc_name', 'dll-path', 'symbol_name', MIN_ARGS=0, MAX_ARGS=1, KEYWORDS=['HELP','MY_KEY2']
in a startup-script, and then have full keyword support in your DLL functions.
(so at least this implementation is half-way to "DLM support")

### CODE REVIEW

**Comment by GillesDuvert** [comment]
Hi, thanks for your contribution!
However, I do not see in GDL code any way to make LINKIMAGE really work, or am I wrong? Is there a working example somewhere? This in constrast with CALL_EXTERNAL that in my experience works perfectly.

**Comment by hillbergt** [comment]
Hi,

I did not add any example-code, I just described it briefly in the commit-message/pull-request (as you should see above). But it's "almost" faitful to the IDL linkimage, with the difference that "KEYWORDS" is not just a flag, but rather a list of accepted keywords. (in IDL's DLM functionality, the keyword-names are actually detected at runtime, but GDL can't do that)

As a concrete example, this is (part of) what I have in a startup-script that I use to load one of my IDL-DLM's that I re-wrote to work with GDL:

PRO link_dlm
    
    lib_name = '/path/to/lib/librdx_gdl.so'

    print, 'Linking DLM: ' + lib_name

    linkimage, 'rdx_cache', lib_name, MIN_ARGS=2, MAX_ARGS=2
    linkimage, 'rdx_cacheclear', lib_name, MIN_ARGS=0, MAX_ARGS=0
    linkimage, 'rdx_cachedel', lib_name, MIN_ARGS=1, MAX_ARGS=1, KEYWORDS=['COUNT']
    linkimage, 'rdx_cacheinfo', lib_name, MIN_ARGS=0, MAX_ARGS=0
    linkimage, 'rdx_cacheget', lib_name, /FUNCT, MIN_ARGS=1, MAX_ARGS=1, KEYWORDS=['COUNT']
    linkimage, 'rdx_readdata', lib_name, /FUNCT, MIN_ARGS=0, MAX_ARGS=1, KEYWORDS=['ALL','DATE_BEG','FRAMENUMBERS','HEADER','HELP','RAW','STATUS']
    linkimage, 'rdx_readhead', lib_name, /FUNCT, MIN_ARGS=0, MAX_ARGS=1, KEYWORDS=['ALL','DATE_BEG','FRAMENUMBERS','HELP','RAW','STATUS']
    
END

I hope this helps.
/Tomas

**Comment by GillesDuvert** [comment]
close and reopen due to large changes in base GDL

**Comment by GillesDuvert** [comment]
reopen for continuous integration tests

**Comment by GillesDuvert** [comment]
OK, 'all tests have failed' but not due to this PR. Not at all. The Travis builds fail consistently for clag/mac os (nothing to do with gdl) and the Appveyor has problems with GDL in 32 bits since at least last May. Nothing to worry, and this PR gonna be merged.

**Comment by slayoo** [comment]
Travis had all green on master 10 days ago: 
https://travis-ci.org/gnudatalanguage/gdl/builds/593972818
but indeed, the problem has nothing to do with GDL... looking into it

**Pull request merged**
