### PR TITLE
Add support for HDF5 attributes/datasets with H5T_ARRAY type

### PR DESCRIPTION
**Pull request by ogressel**
Hi guys,

hope you find this useful. Coming back to GDL after 15 years. Trying to finally get my legacy IDL code/ existing data to work with GDL. Any general advice on coding style/conventions welcome. 

Best wishes,
Oliver

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you!
It would be great to add some test coverage as well.
What is tested now wrt HDF5 is here: https://github.com/gnudatalanguage/gdl/blob/master/testsuite/test_hdf5.pro
(this is run with the continuous integration builds and can be locally executed with "make check")

**Comment by GillesDuvert** [comment]
reopening to trigger a new compilation on GH

**Comment by ogressel** [comment]
Thanks. I have added a test script now with a reference HDF5 data file (created with IDL, but in principle possible to create with that script at a later point). ~~[Was not aware that the commits to my fork will automatically show up in the pull request. How can I control that?]~~ What's the matter with the unsuccessful builds, are those related to my changes?

**Comment by ogressel** [comment]
> "Add more commits by pushing to the master branch on ogressel/gdl."
Okay... should've branched first... still a newbie with regards to github.

**Comment by GillesDuvert** [comment]
> What's the matter with the unsuccessful builds, are those related to my changes?

Hm, as usual, rebuilds are stuck, this time for different reasons, all unrelated to your changes of course.
And, it's only normal that it automatically rebuilds at every change you commit on your side.
To avoid that, you can probably close the PR, take your time to do changes, and reopen the closed PR (or make another) when ready.

**Comment by ogressel** [comment]
Since the changes for h5d_read_fun are basically identical, I have included them in this pull request. Hope that's okay.

**Comment by ogressel** [comment]
Great you could fix the build tests! :)

**Comment by ogressel** [comment]
Cool, thanks.
```
 hid_t elem_datatype = H5Tget_super(datatype);
 H5Tclose(datatype);
 datatype = elem_datatype;
 ```
 Wondering, whether this conforms to the `hdf5_type_guard` mechanism...?

**Comment by GillesDuvert** [comment]
Seems the hdf**guards class defined are there to call H5TClose() automatically.
I suppose H5TClose will not misbehave (such as closing something already closed, or a super_type) but this is indeed a bit touchy.

**Comment by ogressel** [comment]
Hi Gilles,
thanks for the prompt response and for sharing your assessment. I have created a new pull request, where I have re-factored things so that no `hid_t` handles have to be copied. 
Cheers,
Oliver

**Pull request merged**
