### PR TITLE
correction POINT_LUN following bug report #441

### PR DESCRIPTION
**Pull request by alaingdl**
accepted bug report #441 from @pstrub

I tested that on 2 Linux ...

### CODE REVIEW

**Comment by alaingdl** [comment]
Travis for OSX seems to be broken :(

**Comment by pstrub** [comment]
Hi @alaingdl! What's the issue/error msg with Travis OSX? I didn't have any problems building it on my OSX  10.13.6 Macbook. 

Anyway, if the pull request is closed because patch leads to regressions, shouldn't we reopen this in the issue tracker?

**Comment by slayoo** [comment]
Let's keep it open! 
The issue is around homebrew numpy installation - it's not a regression, just a coincidence with some recent change in homebrew.

**Comment by pstrub** [comment]
Thanks for the clarification and for reopening, @slayoo ! I'll keep following the thread!

**Comment by alaingdl** [comment]
I am lost ! the code is OK and the problem with Travis is unrelated !

I would like to merge it :)

may be we can open a bug report for the Travis issue ? I have no time now to look at Travis, some codes pending

**Comment by slayoo** [comment]
@pstrub @alaingdl it would also be great to add a test for this one!

**Comment by slayoo** [comment]
I'll look this evening into the homebrew/numpy issue

**Comment by alaingdl** [comment]
1/ we already have a "test_point_lun"

2/ unclear for me if we need to have a 2+ Go file or not
because we can play with the index above the limit
(unclear for me why)

3/ much more concern by the other place(s) we may have not
taken into account the 64b limit ... I made months ago a review
on some /L64 options (and I have computers to test arrays with such size !)

**Comment by slayoo** [comment]
travis/homebrew/numpy problem fixed (#444)

**Pull request merged**
