### PR TITLE
Better gaussfit, closes #1548

### LINKED ISSUE #1548: GAUSSFIT don't work well whit nterms > 4
GAUSSFIT in GDL don't  resist in the presence of polynomial (nterm > 4)

I have no idea today how to fix it, sorry.

### PR DESCRIPTION
**Pull request by GillesDuvert**

### CODE REVIEW

**Comment by alaingdl** [comment]
It is working way better *but* on my tests the result in case of nterns 5 or 6 are less good that with the original. Please wait a few I can check where the discrepancy comes from

**Comment by slayoo** [comment]
@alaingdl @GillesDuvert let's add a test here!

**Comment by GillesDuvert** [comment]
replaced by #1556

**Comment by GillesDuvert** [comment]
this is closed and replaced by #1556

**Pull request closed without merging**
