### PR TITLE
sync with SF's CVS --- Mainly Parallelizing of MinMax()

### PR DESCRIPTION
**Pull request by GillesDuvert**

### CODE REVIEW

**Comment by slayoo** [comment]
This one fails with clang on the above Travis build with:
```
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:109:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:135:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:222:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:248:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:341:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:371:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
In file included from /Users/travis/build/gnudatalanguage/gdl/src/datatypes.cpp:4393:
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:109:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:222:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
/Users/travis/build/gnudatalanguage/gdl/src/minmax_include.cpp:341:27: error: use of undeclared identifier 'omp_get_thread_num'
          int thread_id = omp_get_thread_num();
                          ^
```

**Comment by GillesDuvert** [comment]
yes of course some compilers do not even know about #openmp clauses.
Please somebody finds the "good" way to persudade clang to use openmp. A special cmake-added link library?
In the meantime I'll #ifdef the whole thing.

**Comment by slayoo** [comment]
Is this PR being replaced with #31?

**Comment by GillesDuvert** [comment]
Yes. Please remove this PR.

**Pull request closed without merging**
