### PR TITLE
WIP: Initial attempt to implement throwImmediately in ANTLR grammar

### PR DESCRIPTION
**Pull request by opoplawski**
This is an initial attempt to implement the changes in #510 in the ANTLR sources.  However, I'm not able to pass arguments in the statement rules.  Reading https://stackoverflow.com/questions/21747097/antlr-rules-with-arguments leaves me to believe that it should be possible, though highly discouraged, but it isn't working for me with antlr 2.7.7 at least.

### CODE REVIEW

**Comment by opoplawski** [comment]
Okay, looks like perhaps had to re-order.  Harder to compare the differences in the generated files now though.  Starting to run builds...

**Comment by opoplawski** [comment]
Builds seem to be fine here.  Someone should double check these changes, but I think they are correct at this point.

**Comment by slayoo** [comment]
#198 - would be great to kill two birds with one stone

**Comment by slayoo** [comment]
The travis script now includes a block with instructions for checking if the generated files match in input .g files

**Comment by GillesDuvert** [comment]
I suggest to resubmit a patch with minimal changes in the .g file (here some blocks of text has been unnecessarily moved). The only reason is to see clearly the small incremental change in an otherwise cryptic language, given that a better solution to bug #498 could be sooner or later be proposed by our ANTLR expert, Marc S.

**Comment by GillesDuvert** [comment]
Besides, thanks @slayoo for the travis patch and closing of #198 .
Still, there will always be the doubt about how GDL behaves with or without using different flavours of stock ANTLR (not speaking about old versions of ANTLR being dropped at some point). Compared to the need to reconstruct with C++ compiler only on mr everybody's machine.

**Comment by slayoo** [comment]
@GillesDuvert First step - revert: https://github.com/gnudatalanguage/gdl/pull/543

**Pull request merged**
