### PR TITLE
try re-enabling tests in travis

### PR DESCRIPTION
**Pull request by sflinois**

### CODE REVIEW

**Comment by sflinois** [comment]
On OSX
```
The following tests FAILED:
	187 - test_wait.pro (Failed)
```

**Comment by slayoo** [comment]
```
% TEST_WAIT: Tolerance Time error was exceed  3 times.
<end of output>
Test time =   5.73 sec
----------------------------------------------------------
Test Failed.
```

**Comment by sflinois** [comment]
test_bytscl.pro,  test_modulo.pro, test_tic_toc.pro, test_resolve_routine  and test_total were re-enabled in .travis

In libinit.cpp, the X11 condition for the get_screen_size function definition was changed.
The test_screen_size is still incomplete and the screen_size function still need some changes (see #389 )

The test_total routine handle more cases and the total function handle more special cases
tests on total with NAN and INF value should still be made to cover all of the total function
(I'll try completing the tests on total :) )

**Comment by sflinois** [comment]
I'm not really sure why the tests are all failing in appveyor
I don't think i changed anything related to the appveyor build

**Comment by slayoo** [comment]
please just ignore this one failure (in fact the Release build was 100% pass, the Debug one seems to have had an irreproducible problem with DLL path - the error code translates to  STATUS_DLL_NOT_FOUND)

**Comment by sflinois** [comment]
I think this PR is ready to be merged too 
Should I make some changes ?

**Comment by alaingdl** [comment]
do we have access to a Travis ENV var. when we are on Travis ? 
(via GETENV()) just to put a 100% margin for test_wait !
(this test is not critical, but we have to have it to remember the OSX issue)

**Comment by slayoo** [comment]
Yes: https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

**Comment by slayoo** [comment]
All green as of now -> merging and creating a new ticket for test_wait

**Comment by slayoo** [comment]
https://github.com/gnudatalanguage/gdl/issues/413

**Pull request merged**
