### PR TITLE
Update PROJ support

### PR DESCRIPTION
**Pull request by opoplawski**
This reworks PROJ support fairly significantly and uses the new PROJ API with version 5+.  Some basic testing with PROJ 6.3.2.  Should address #893

### CODE REVIEW

**Review by maynardGK — APPROVED** [review]
I can only build, not run, with the mingw/msys2 gcc 10 on win10: runtime doesn't find
the $PATH where shared libraries are kept.  It builds fine (with proj version 6.3.2).

**Comment by GillesDuvert** [comment]
@opoplawski  wow huge work, I'll test it ASAP, but already looks good!

**Comment by slayoo** [comment]
Just tested it on a fresh Debian with proj 8.0.0 from Debian experimental. Compilation ok, but running map_set I get:
```
GDL> map_set
% Compiled module: MAP_SET.
% Compiled module: MAP_ADJLON.
% Compiled module: FILEPATH.
% Compiled module: PATH_SEP.
% MAP_PROJ_INIT: Tag name: PROJNAME is undefined for STRUCT.
% Error occurred at: MAP_PROJ_INIT      138 /usr/local/share/gnudatalanguage/lib/map/map_proj_init.pro
%                    MAP_SET            160 /usr/local/share/gnudatalanguage/lib/map/map_set.pro
%                    $MAIN$          
% Execution halted at: $MAIN$          
GDL> 

```

**Comment by opoplawski** [comment]
> Just tested it on a fresh Debian with proj 8.0.0 from Debian experimental. Compilation ok, but running map_set I get:
> 
> ```
> GDL> map_set
> % Compiled module: MAP_SET.
> % Compiled module: MAP_ADJLON.
> % Compiled module: FILEPATH.
> % Compiled module: PATH_SEP.
> % MAP_PROJ_INIT: Tag name: PROJNAME is undefined for STRUCT.

Ah, I believe this is because while I changed the variable "proj4name" in the code, I didn't change it in the projDefinitions.sav file.  I guess my question at this point is whether or not I should undo that name change, or go through the process of changing the .sav file.

**Comment by GillesDuvert** [comment]
indeed, there is a small problem when installed. I look into that.

**Review by GillesDuvert — CHANGES_REQUESTED** [review]
Hi Orion, I've submitted a PR on your PR. Probably not the best way to handle that.
With my (lazy) patches, all is well!

**Comment by opoplawski** [comment]
Yeah, hard to see what's up in the history here now - but if you're happy with the changes, I'm fine too.

**Comment by GillesDuvert** [comment]
(post commit) works:
image

**Pull request merged**
