### PR TITLE
Projection support

### PR DESCRIPTION
**Pull request by GillesDuvert**
This PR include a complete and original support of ALL projections (those known by IDL and also the numerous known by the proj4 library, so ~190 projections in total). The number of supported projections is not limited as a simple procedure described in the resource/maps/README suffice to make new PROJ projections known.
Most of the MAP_* procedures have been written from scratch and suffice for most uses.
see map_proj_init's 'test_all-proj" for a demo.

### CODE REVIEW

**Comment by slayoo** [comment]
```
/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1149:35: error: use of undeclared identifier 'epsilon'

    while (abs(distanceToPlane) < epsilon) { //just displace a bit on the same "side" but at a larger distance.

                                  ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1150:23: error: use of undeclared identifier 'epsilon'

      x += sideCode * epsilon * a;

                      ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1151:23: error: use of undeclared identifier 'epsilon'

      y += sideCode * epsilon * b;

                      ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1152:23: error: use of undeclared identifier 'epsilon'

      z += sideCode * epsilon * c;

                      ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1188:35: error: use of undeclared identifier 'epsilon'

    while (abs(distanceToPlane) > epsilon && i < 10) {

                                  ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1245:35: error: use of undeclared identifier 'epsilon'

    while (abs(distanceToPlane) < epsilon && vertex != p.VertexList.end()) {

                                  ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1429:5: error: unknown type name 'LPTYPE'

    LPTYPE idata;

    ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1430:5: error: unknown type name 'XYTYPE'

    XYTYPE odata;

    ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1542:5: error: unknown type name 'LPTYPE'

    LPTYPE idata;

    ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1543:5: error: unknown type name 'XYTYPE'

    XYTYPE odata;

    ^

/Users/travis/build/gnudatalanguage/gdl/src/projections.cpp:1765:29: error: use of undeclared identifier 'epsilon'

          if (abs(before) < epsilon) sideCode = findSign((*p), a, b, c, d); //if we start too close to the plane, 

                            ^

```

**Comment by GillesDuvert** [comment]
hm. Bug in test_congrid. unexpected! TBC

**Comment by GillesDuvert** [comment]
actually it is congrid.pro that is wrong!
a separate PR will be sent for this.

**Comment by GillesDuvert** [comment]
removing temporarily -- to be opened again

**Pull request closed without merging**
