### PR TITLE
re-enable test_finite on travis

### PR DESCRIPTION
**Pull request by sflinois**

### CODE REVIEW

**Comment by alaingdl** [comment]
I don't know where is the right place to discuss it, and I don't know where to find the problem, but I am surprise that some tests are deactivaed : 

test_bytscl.pro
test_modulo.pro
test_tic_toc.pro
test_wait.pro
...

do we have or could we have a bug entry for each ? thanks !
(all of them are working like a charm on the +10th machines I am testing GDL on)

**Comment by slayoo** [comment]
For tic_toc there is already one: https://github.com/gnudatalanguage/gdl/issues/209
And... I guess the best way to investigate would be to just open a new PR as this one.
Please also consider re-enabling the in appveyor.yml
Thanks!

**Comment by sflinois** [comment]
I'll create a new PR
I'm currently working on test_total :)

**Comment by slayoo** [comment]
thank you!

**Comment by slayoo** [comment]
seems there is an issue with intel compiler:
https://travis-ci.org/gnudatalanguage/gdl/jobs/394431156#L6494
```
99/192 Testing: test_finite.pro
99/192 Test: test_finite.pro
Command: "/home/travis/build/gnudatalanguage/gdl/build/testsuite/launchtest" "test_finite.pro"
Directory: /home/travis/build/gnudatalanguage/gdl/build/testsuite
"test_finite.pro" start time: Jun 20 07:38 UTC
Output:
----------------------------------------------------------
% Compiled module: TEST_FINITE.
% Compiled module: ERRORS_ADD.
% TEST_FINITE_BASIC: Error on operation : problem with Case        4
% TEST_FINITE_BASIC: Error on operation : problem with Case        5
% TEST_FINITE_BASIC: Error on operation : problem with Case        7
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FINITE_BASIC:   3 errors encountered during TEST_FINITE_BASIC tests  
% Compiled module: ERRORS_CUMUL.
% TEST_FINITE_BASIC: Error on operation : problem with Case        4
% TEST_FINITE_BASIC: Error on operation : problem with Case        5
% TEST_FINITE_BASIC: Error on operation : problem with Case        7
% TEST_FINITE_BASIC:   3 errors encountered during TEST_FINITE_BASIC tests  
% TEST_FINITE_BASIC: Error on operation : problem with Case        4
% TEST_FINITE_BASIC: Error on operation : problem with Case        5
% TEST_FINITE_BASIC: Error on operation : problem with Case        7
% TEST_FINITE_BASIC:   3 errors encountered during TEST_FINITE_BASIC tests  
% TEST_FINITE_BASIC: Error on operation : problem with Case        4
% TEST_FINITE_BASIC: Error on operation : problem with Case        5
% TEST_FINITE_BASIC: Error on operation : problem with Case        7
% TEST_FINITE_BASIC:   3 errors encountered during TEST_FINITE_BASIC tests  
% TEST_FINITE_VALUES: Error on operation : case 1g
% TEST_FINITE_VALUES: Error on operation : case 2 (NaN & Sign)
% TEST_FINITE_VALUES: Error on operation : case 1
% TEST_FINITE_VALUES: This platform does not distinguish between +Inf and -Inf
% TEST_FINITE_VALUES: Error on operation : case 1
% TEST_FINITE_VALUES:   4 errors encountered during TEST_FINITE_VALUES tests  
Running this test with various numbers of points ...
Please wait ...
% TEST_FINITE_TIMETEST: 
  2 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  2 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  2 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  2 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  2 errors encountered during TEST_FINITE_TIMETEST tests  
Same test with various numbers of points and /Inf...
% TEST_FINITE_TIMETEST: 
  3 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  3 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  3 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  3 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE_TIMETEST: 
  3 errors encountered during TEST_FINITE_TIMETEST tests  
% TEST_FINITE: ====================================================
% TEST_FINITE: =                                                  =
% TEST_FINITE: =  41 errors encountered during TEST_FINITE tests  =
% TEST_FINITE: =                                                  =
% TEST_FINITE: ====================================================
<end of output>
Test time = 154.99 sec
----------------------------------------------------------
Test Failed.
"test_finite.pro" end time: Jun 20 07:41 UTC
"test_finite.pro" time elapsed: 00:02:34
----------------------------------------------------------
```

**Comment by slayoo** [comment]
if we assume this is low priority we could simply disable this test in .travis.yml only for icc with
```
if [ $COMPILER == icc ]; then $SEDCMD '/test_finite.pro/d' testsuite/Makefile.am; fi
```

**Comment by sflinois** [comment]
I'll try to see where the test is failing

**Comment by alaingdl** [comment]
We do have ICC licence for Linux and Sylvain will try to fix that

**Comment by slayoo** [comment]
thanks!

**Comment by sflinois** [comment]
I think this PR is ready to be merged
Should I make some changes ?

**Pull request merged**
