### PR TITLE
several small changes; bug detected in FILE_TEST()

### PR DESCRIPTION
**Pull request by alaingdl**
several small changes
* merging two test_contour (basic & extra) into one "test_contour.pro"
* improving idlneturl + related test (4 cases + SimbadQuery)
* "test_file_test.pro" : improving & splitting into several dedicated procedures : yes we do have a bug in c++ code for dangling sym link 
* initial import of "test_plot_usersym.pro"

### CODE REVIEW

**Comment by alaingdl** [comment]
I don't understand why it is "red cross" in both CI :(

**Comment by slayoo** [comment]
```
CMake Error at CTestTestfile.cmake:407:
  Parse error.  Function missing ending ")".  End of file reached.
```

**Comment by slayoo** [comment]
https://travis-ci.org/gnudatalanguage/gdl/jobs/434808979#L3546

**Comment by slayoo** [comment]
this is for CODECOV=yes, I'll look at it this evening

**Comment by alaingdl** [comment]
sorry for the mess I introduced, I just would like to comment the 2 test files not wotking now in Makefile.am
(test_container.pro & test_file_test.pro)

**Comment by slayoo** [comment]
the Makefile.am is parsed from within our CMake scripts, and the parsing logic cannot cope with comments in Makefile.am, I've just moved these comments to .travis.yml to fix it:
- https://github.com/gnudatalanguage/gdl/commit/b1b4e1da11ee55a719c4db91e54d82b80ed54ba2
- https://github.com/gnudatalanguage/gdl/commit/d934a2e673038dec57ee720306378a98cae1a92d

**Pull request merged**
