### PR TITLE
WIP Work on plotting functions

### PR DESCRIPTION
**Pull request by GillesDuvert**
WIP
many changes to get several options like tickunits and ticklayout work.
Will need more work.
Already Solves #1587 
Hope for #1585

### CODE REVIEW

**Comment by GillesDuvert** [comment]
Hi folks,

I'm under the impression that codecov gives strange results. Consider https://github.com/gnudatalanguage/gdl/pull/1603#issuecomment-1569117912
where the whole edits are on the plotting.*pp files and codecov finding 61 files changed!!
I guess it compares with  two different "trunks". I would argue that codecov is only "working" during a commit in the main trunk (merging) and not during a PR. Actually it delays the tests for the PR (by 13 minutes!!!) and is not at all useful.
I would thus use codecov **only during merging pull requests**.
Cheers

**Comment by slayoo** [comment]
@GillesDuvert 
> Actually it delays the tests for the PR (by 13 minutes!!!) 

It adds 13 minutes of workload, but should not delay anything given that the jobs run concurrently.

CC: @Saynkas, could you comment on the number of files changed detected? Thanks

**Comment by slayoo** [comment]
Also, the intent of codecov is to red-flag PRs which reduce test coverage, and to force inclusion of tests before merging. Reporting it after merging would render it futile.

**Comment by GillesDuvert** [comment]
@slayoo you are right, I forgot the jobs were concurrent.
But I do not understand why the ~250 indirectly impacted files reported above, and especially why their coverage will vary in both directions?

**Comment by Saynkas** [comment]
> @GillesDuvert
> 
> > Actually it delays the tests for the PR (by 13 minutes!!!)
> 
> It adds 13 minutes of workload, but should not delay anything given that the jobs run concurrently.
> 
> CC: @Saynkas, could you comment on the number of files changed detected? Thanks

codecov uses github's API to get the source code which isn't foolproof, sometimes it doesn't work properly and fails to upload the correct coverage, look all the way at the bottom of the 'Upload coverage to Codecov' tab of the codecov action
I'd wager that's why it says a bunch of files were changed when in reality they were not (can restart the codecov action manually so it hopefully works this time)

I've yet to see with @alaingdl which option we pick to fix this : either add it as a CI/CD environment secret but given that forks don't copy secrets codecov wouldn't really work for PRs, or hardcode it in the workflow file which is questionable security-wise

from a developer post :
_A malicious actor would be able to upload incorrect or misleading coverage reports to a specific repository if they have access to your upload token, but would not be able to pull down source code or make any code changes._

they said they're working on a solution to reduce how much they use the API but there isn't a fix yet

source : https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

**Comment by Saynkas** [comment]
> ## [Codecov](https://app.codecov.io/gh/gnudatalanguage/gdl/pull/1603?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage) Report
> 
> Patch coverage: **`57.00`**% and project coverage change: **`-0.67`** warning
> 
> > Comparison is base [(`c94e31c`)](https://app.codecov.io/gh/gnudatalanguage/gdl/commit/c94e31c34feaefd1793d4d313e06cbbb8117d185?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage) 41.83% compared to head [(`97a2468`)](https://app.codecov.io/gh/gnudatalanguage/gdl/pull/1603?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage) 41.16%.
> 
> > exclamation Current head [97a2468](https://github.com/gnudatalanguage/gdl/commit/97a24689d78880144adf8a9ad0160bfb7b807269) differs from pull request most recent head [b6d18bd](https://github.com/gnudatalanguage/gdl/commit/b6d18bdf35f86cc5fa53a95cf38c68f9c7811d5c). Consider uploading reports for the commit [b6d18bd](https://github.com/gnudatalanguage/gdl/commit/b6d18bdf35f86cc5fa53a95cf38c68f9c7811d5c) to get more accurate results
> 
> Additional details and impacted files
> 
> [umbrella View full report in Codecov by Sentry](https://app.codecov.io/gh/gnudatalanguage/gdl/pull/1603?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage). loudspeaker Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage).

also this message makes me think codecov isn't capable of dealing with updated pull requests, it says it's out-of-date compared to the latest PR's commit, but that's most likely my fault for not telling codecov explicitly to restart the coverage if it detects a new commit, will investigate

**Comment by Saynkas** [comment]
> > ## [Codecov](https://app.codecov.io/gh/gnudatalanguage/gdl/pull/1603?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage) Report
> > Patch coverage: **`57.00`**% and project coverage change: **`-0.67`** warning
> > > Comparison is base [(`c94e31c`)](https://app.codecov.io/gh/gnudatalanguage/gdl/commit/c94e31c34feaefd1793d4d313e06cbbb8117d185?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage) 41.83% compared to head [(`97a2468`)](https://app.codecov.io/gh/gnudatalanguage/gdl/pull/1603?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage) 41.16%.
> > 
> > 
> > > exclamation Current head [97a2468](https://github.com/gnudatalanguage/gdl/commit/97a24689d78880144adf8a9ad0160bfb7b807269) differs from pull request most recent head [b6d18bd](https://github.com/gnudatalanguage/gdl/commit/b6d18bdf35f86cc5fa53a95cf38c68f9c7811d5c). Consider uploading reports for the commit [b6d18bd](https://github.com/gnudatalanguage/gdl/commit/b6d18bdf35f86cc5fa53a95cf38c68f9c7811d5c) to get more accurate results
> > 
> > 
> > Additional details and impacted files
> > [umbrella View full report in Codecov by Sentry](https://app.codecov.io/gh/gnudatalanguage/gdl/pull/1603?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage). loudspeaker Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gnudatalanguage).
> 
> also this message makes me think codecov isn't capable of dealing with updated pull requests, it says it's out-of-date compared to the latest PR's commit, but that's most likely my fault for not telling codecov explicitly to restart the coverage if it detects a new commit, will investigate

nevermind, it seems to take note of new commits appearing after the pull request has been made, except since the 2 checks failed to upload to codecov, it thinks that no new coverage was uploaded and therefore gives this warning (shouldn't happen if it manages to successfully upload coverage data)
will see what to do about upload failures today (hopefully)

**Comment by GillesDuvert** [comment]
@Saynkas thanks I merge this to keep successive changes to GDL small..

**Pull request merged**
